// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

import { expect, test } from '@playwright/test'
import { signInAsOperator } from './helpers/auth'

const proposal = {
  id: 'proposal-42',
  title: 'Raise transaction monitoring threshold',
  rationale: 'The agent detected an evidence-backed false-positive cluster.',
  suggestedAction: 'Create a governed configuration change for human review.',
  proposedBy: 'service-account-compliance-officer',
  proposedAt: '2026-08-31T12:00:00Z',
  state: 'PROPOSED',
  decidedBy: null,
  decidedAt: null,
  decisionReason: null,
  modelId: 'governed-model-v2',
}

test.describe('approval workbench', () => {
  test.beforeEach(async ({ context, baseURL }) => {
    await signInAsOperator(context, baseURL!)
  })

  test('shows incomplete domain evidence and records one human AI-proposal decision', async ({ page }) => {
    let decided = false
    let decisionRequests = 0

    // Matches both the GET list read (…/proposals?state=all) and the POST decision
    // write (…/proposals, no query string) — the two differ only by query string and
    // method, and a pattern anchored on the literal "?state=all" suffix would only ever
    // catch the GET, silently letting the POST fall through to the real (unmocked)
    // network and leaving `decided` stuck false forever (#7814).
    await page.route('**/api/agent/proposals*', async route => {
      if (route.request().method() === 'GET') {
        const row = decided ? {
          ...proposal,
          state: 'APPROVED',
          decidedBy: 'e2e-operator@openbank.test',
          decidedAt: '2026-08-31T12:05:00Z',
          decisionReason: 'Evidence independently checked.',
        } : proposal
        return route.fulfill({ contentType: 'application/json', body: JSON.stringify([row]) })
      }

      decisionRequests += 1
      expect(route.request().method()).toBe('POST')
      expect(await route.request().postDataJSON()).toEqual({
        proposalId: proposal.id,
        approve: true,
        decidedBy: 'e2e-operator@openbank.test',
        reason: 'Evidence independently checked.',
      })
      if (decisionRequests === 1) {
        return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'temporary decision-store outage' }) })
      }
      decided = true
      await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ status: 'APPROVED' }) })
    })
    await page.route('**/api/approvals/pending', route => route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        items: [{
          id: 'sct-inst-approval-7', domain: 'sepa-instant', action: 'payment.release',
          resourceId: 'payment-7', maker: 'maker.operator', proposedAt: '2026-08-31T11:59:00Z',
        }],
        sources: { 'sepa-instant': 'ok', ledger: 'unavailable' },
      }),
    }))
    await page.route('**/api/governance/agent-identities', route => route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        available: true,
        agents: [{
          id: 'compliance-officer', plane: 'compliance',
          charter: 'Proposes compliance controls; never executes them.', requiresHuman: ['approve'],
        }],
      }),
    }))

    await page.goto('/approvals')

    await expect(page.getByText(/This queue is incomplete|Fronta není úplná/)).toContainText('ledger')
    await expect(page.getByText('payment.release')).toBeVisible()
    await expect(page.getByText(proposal.title)).toBeVisible()
    await expect(page.getByText(/This proposal was generated by AI|Tento návrh vytvořila AI/)).toBeVisible()
    await expect(page.getByTestId('agent-identity')).toHaveAttribute('data-state', 'chartered')

    await page.getByRole('button', { name: new RegExp(`Review and approve proposal ${proposal.title}|Zkontrolovat a schválit návrh ${proposal.title}`) }).click()

    const dialog = page.getByRole('alertdialog')
    await expect(dialog).toContainText(proposal.title)
    await expect(dialog).toContainText(proposal.suggestedAction)
    const confirm = dialog.getByRole('button', { name: /Confirm approval|Potvrdit schválení/ })
    await expect(confirm).toBeDisabled()
    await dialog.getByLabel(/Decision reason|Důvod rozhodnutí/).fill('Evidence independently checked.')
    await confirm.click()

    await expect(dialog.getByRole('alert')).toContainText(/could not be recorded|nepodařilo uložit/)
    await expect(dialog).toBeVisible()
    await confirm.click()

    await expect(dialog).toBeHidden()
    await expect(page.getByRole('cell', { name: proposal.title })).toBeVisible()
    await expect(page.getByRole('cell', { name: /Approved|Schváleno/ })).toBeVisible()
    await expect(page.getByRole('cell', { name: 'e2e-operator@openbank.test' })).toBeVisible()
    await expect(page.getByRole('cell', { name: 'Evidence independently checked.' })).toBeVisible()
    expect(decisionRequests).toBe(2)
  })

  test('filters domain work and hands a sanctions item to its governed checker', async ({ page }) => {
    const sanctionsApproval = {
      id: 'sanctions-approval / 42', domain: 'sanctions', action: 'sanctions.clear',
      resourceId: 'check-42', maker: 'maker.sanctions', proposedAt: '2026-08-31T08:00:00Z',
    }
    const notificationApproval = {
      id: 'notification-approval-7', domain: 'notification', action: 'opsmessage.compose',
      resourceId: null, maker: 'maker.notifications', proposedAt: '2026-08-31T09:00:00Z',
    }
    const balanceApproval = {
      id: 'balance-approval-3', domain: 'balance', action: 'balance.debit',
      resourceId: 'account-3', maker: 'maker.balance', proposedAt: '2026-08-31T10:00:00Z',
    }
    const billingApproval = {
      id: 'billing-approval-4', domain: 'billing', action: 'fee.post',
      resourceId: 'fee-4', maker: 'maker.billing', proposedAt: '2026-08-31T11:00:00Z',
    }

    await page.route('**/api/agent/proposals*', route =>
      route.fulfill({ contentType: 'application/json', body: '[]' }),
    )
    await page.route('**/api/approvals/pending', route => route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        items: [billingApproval, balanceApproval, sanctionsApproval, notificationApproval],
        sources: { sanctions: 'ok', notification: 'ok', balance: 'ok', billing: 'ok' },
      }),
    }))
    await page.route('**/api/governance/agent-identities', route => route.fulfill({
      contentType: 'application/json', body: JSON.stringify({ available: true, agents: [] }),
    }))
    await page.route('**/api/sanctions/checks', route =>
      route.fulfill({ contentType: 'application/json', body: '[]' }),
    )
    await page.route('**/api/sanctions/lists', route =>
      route.fulfill({ contentType: 'application/json', body: '[]' }),
    )
    await page.route('**/api/sanctions/approvals', route =>
      route.fulfill({ contentType: 'application/json', body: JSON.stringify([{
        id: sanctionsApproval.id,
        action: sanctionsApproval.action,
        resourceId: sanctionsApproval.resourceId,
        status: 'PENDING',
        makerId: sanctionsApproval.maker,
        createdAt: sanctionsApproval.proposedAt,
      }]) }),
    )

    await page.goto('/approvals')

    const rows = page.locator('[data-testid^="domain-approval-"]')
    await expect(rows).toHaveCount(4)
    await expect(rows.nth(0)).toContainText(sanctionsApproval.action)
    await page.getByLabel(/^(Order|Pořadí)$/).selectOption('newest')
    await expect(rows.nth(0)).toContainText(billingApproval.action)

    await page.getByLabel(/^(Domain|Doména)$/).selectOption('sanctions')
    await expect(rows).toHaveCount(1)
    await expect(rows.first()).toContainText(sanctionsApproval.action)
    await page.getByLabel(/Search queue|Hledat ve frontě/).fill('maker.sanctions')
    await expect(rows).toHaveCount(1)

    const handoff = page.getByRole('link', { name: new RegExp(`Open governed review for approval ${sanctionsApproval.id}|Otevřít řízenou kontrolu žádosti ${sanctionsApproval.id}`) })
    await expect(handoff).toHaveAttribute('href', '/sanctions?approvalId=sanctions-approval%20%2F%2042#sanctions-approval-id')
    await handoff.click()

    await expect(page).toHaveURL(/\/sanctions\?approvalId=sanctions-approval%20%2F%2042#sanctions-approval-id$/)
    await expect(page.getByLabel(/Approval id|ID žádosti/)).toHaveValue(sanctionsApproval.id)
  })

  test('never reports an empty domain queue when the federated read itself failed', async ({ page }) => {
    await page.route('**/api/agent/proposals*', route =>
      route.fulfill({ contentType: 'application/json', body: '[]' }),
    )
    await page.route('**/api/approvals/pending', route =>
      route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'aggregator unavailable' }) }),
    )
    await page.route('**/api/governance/agent-identities', route => route.fulfill({
      contentType: 'application/json', body: JSON.stringify({ available: true, agents: [] }),
    }))

    await page.goto('/approvals')

    await expect(page.getByText(/Domain approval inbox could not be loaded|Doménovou schvalovací frontu se nepodařilo načíst/)).toBeVisible()
    await expect(page.getByText(/No domain approvals pending|Žádná doménová schvalování nečekají/)).toHaveCount(0)
  })
})
