// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

import { expect, test } from '@playwright/test'
import { signInAsOperator } from './helpers/auth'

const proposal = {
  id: 'proposal-42',
  title: 'Raise transaction monitoring threshold',
  rationale: 'The agent detected an evidence-backed false-positive cluster.',
  suggestedAction: 'Create a governed configuration change for human review.',
  proposedBy: 'service-account-compliance-officer',
  proposedAt: '2026-08-31T12:00:00Z',
  state: 'PROPOSED',
  decidedBy: null,
  decidedAt: null,
  decisionReason: null,
  modelId: 'governed-model-v2',
}

test.describe('approval workbench', () => {
  test.beforeEach(async ({ context, baseURL }) => {
    await signInAsOperator(context, baseURL!)
  })

  test('shows incomplete domain evidence and records one human AI-proposal decision', async ({ page }) => {
    let decided = false
    let decisionRequests = 0

    await page.route('**/api/agent/proposals?state=all', async route => {
      if (route.request().method() === 'GET') {
        const row = decided ? {
          ...proposal,
          state: 'APPROVED',
          decidedBy: 'e2e-operator@openbank.test',
          decidedAt: '2026-08-31T12:05:00Z',
          decisionReason: 'Evidence independently checked.',
        } : proposal
        return route.fulfill({ contentType: 'application/json', body: JSON.stringify([row]) })
      }

      decisionRequests += 1
      expect(route.request().method()).toBe('POST')
      expect(await route.request().postDataJSON()).toEqual({
        proposalId: proposal.id,
        approve: true,
        decidedBy: 'e2e-operator@openbank.test',
        reason: 'Evidence independently checked.',
      })
      decided = true
      await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ status: 'APPROVED' }) })
    })
    await page.route('**/api/approvals/pending', route => route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        items: [{
          id: 'sct-inst-approval-7', domain: 'sepa-instant', action: 'payment.release',
          resourceId: 'payment-7', maker: 'maker.operator', proposedAt: '2026-08-31T11:59:00Z',
        }],
        sources: { 'sepa-instant': 'ok', ledger: 'unavailable' },
      }),
    }))
    await page.route('**/api/governance/agent-identities', route => route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        available: true,
        agents: [{
          id: 'compliance-officer', plane: 'compliance',
          charter: 'Proposes compliance controls; never executes them.', requiresHuman: ['approve'],
        }],
      }),
    }))

    await page.goto('/approvals')

    await expect(page.getByText(/This queue is incomplete|Fronta není úplná/)).toContainText('ledger')
    await expect(page.getByText('payment.release')).toBeVisible()
    await expect(page.getByText(proposal.title)).toBeVisible()
    await expect(page.getByText(/This proposal was generated by AI|Tento návrh vytvořila AI/)).toBeVisible()
    await expect(page.getByTestId('agent-identity')).toHaveAttribute('data-state', 'chartered')

    await page.getByLabel(/Proposal decision reason|Důvod rozhodnutí návrhu/).fill('Evidence independently checked.')
    await page.getByRole('button', { name: new RegExp(`Approve proposal ${proposal.title}|Schválit návrh ${proposal.title}`) }).click()

    await expect(page.getByRole('cell', { name: proposal.title })).toBeVisible()
    await expect(page.getByRole('cell', { name: /Approved|Schváleno/ })).toBeVisible()
    await expect(page.getByRole('cell', { name: 'e2e-operator@openbank.test' })).toBeVisible()
    await expect(page.getByRole('cell', { name: 'Evidence independently checked.' })).toBeVisible()
    expect(decisionRequests).toBe(1)
  })
})
