// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

import { expect, test } from '@playwright/test'
import { signInAsOperator } from './helpers/auth'
import { APPROVAL_DOMAINS, type ApprovalSourceState } from '../src/lib/approvals/evidence'

function approvalSources(overrides: Record<string, ApprovalSourceState> = {}) {
  return Object.fromEntries(APPROVAL_DOMAINS.map(domain => [domain, overrides[domain] ?? 'not-configured']))
}

const proposal = {
  id: '11111111-1111-4111-8111-111111111142',
  title: 'Raise transaction monitoring threshold',
  rationale: 'The agent detected an evidence-backed false-positive cluster.',
  suggestedAction: 'Create a governed configuration change for human review.',
  proposedBy: 'service-account-compliance-officer',
  proposedAt: '2026-08-31T12:00:00Z',
  state: 'PROPOSED',
  decidedBy: null,
  decidedAt: null,
  decisionReason: null,
  modelId: 'governed-model-v2',
}

test.describe('approval workbench', () => {
  test.beforeEach(async ({ context, baseURL }) => {
    await signInAsOperator(context, baseURL!)
  })

  test('shows incomplete domain evidence and records one human AI-proposal decision', async ({ page }) => {
    let decided = false
    let decisionRequests = 0

    // Matches both the GET list read (…/proposals?state=all) and the POST decision
    // write (…/proposals, no query string) — the two differ only by query string and
    // method, and a pattern anchored on the literal "?state=all" suffix would only ever
    // catch the GET, silently letting the POST fall through to the real (unmocked)
    // network and leaving `decided` stuck false forever (#7814).
    await page.route('**/api/agent/proposals*', async route => {
      if (route.request().method() === 'GET') {
        const row = decided ? {
          ...proposal,
          state: 'APPROVED',
          decidedBy: 'e2e-operator@openbank.test',
          decidedAt: '2026-08-31T12:05:00Z',
          decisionReason: 'Evidence independently checked.',
        } : proposal
        return route.fulfill({ contentType: 'application/json', body: JSON.stringify([row]) })
      }

      decisionRequests += 1
      expect(route.request().method()).toBe('POST')
      expect(await route.request().postDataJSON()).toEqual({
        proposalId: proposal.id,
        approve: true,
        decidedBy: 'e2e-operator@openbank.test',
        reason: 'Evidence independently checked.',
      })
      if (decisionRequests === 1) {
        return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'temporary decision-store outage' }) })
      }
      decided = true
      await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ status: 'APPROVED' }) })
    })
    await page.route('**/api/approvals/pending', route => route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        items: [{
          id: 'sct-inst-approval-7', domain: 'sepa-instant', action: 'payment.release',
          resourceId: 'payment-7', maker: 'maker.operator', proposedAt: '2026-08-31T11:59:00Z',
        }],
        sources: approvalSources({ 'sepa-instant': 'ok', ledger: 'unavailable', transaction: 'forbidden' }),
      }),
    }))
    await page.route('**/api/governance/agent-identities', route => route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        available: true,
        agents: [{
          id: 'compliance-officer', plane: 'compliance',
          charter: 'Proposes compliance controls; never executes them.', requiresHuman: ['approve'],
        }],
      }),
    }))

    await page.goto('/approvals')

    // The auth guard may verify the synthetic session after navigation before mounting the inbox.
    const incompleteQueue = page.getByText(/This queue is incomplete|Fronta není úplná/)
    await expect(incompleteQueue).toContainText(/ledger \((request failed|požadavek selhal)\)/, { timeout: 15_000 })
    await expect(incompleteQueue).toContainText(/transaction \((access denied|přístup odepřen)\)/)
    await expect(page.getByText('payment.release')).toBeVisible()
    await expect(page.getByText(proposal.title)).toBeVisible()
    await expect(page.getByText(/This proposal was generated by AI|Tento návrh vytvořila AI/)).toBeVisible()
    await expect(page.getByTestId('agent-identity')).toHaveAttribute('data-state', 'chartered')

    const trigger = page.getByRole('button', { name: new RegExp(`Review and approve proposal ${proposal.title}|Zkontrolovat a schválit návrh ${proposal.title}`) })
    await trigger.click()

    const dialog = page.getByRole('alertdialog')
    await expect(dialog).toContainText(proposal.title)
    await expect(dialog).toContainText(proposal.suggestedAction)
    const confirm = dialog.getByRole('button', { name: /Confirm approval|Potvrdit schválení/ })
    await expect(confirm).toBeDisabled()
    const reason = dialog.getByLabel(/Decision reason|Důvod rozhodnutí/)
    await expect(reason).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(dialog).toBeHidden()
    await expect(trigger).toBeFocused()
    expect(decisionRequests).toBe(0)

    await trigger.click()
    await expect(dialog).toBeVisible()
    await expect(dialog.getByLabel(/Decision reason|Důvod rozhodnutí/)).toHaveValue('')
    await dialog.getByLabel(/Decision reason|Důvod rozhodnutí/).fill('Evidence independently checked.')
    await confirm.click()

    await expect(dialog.getByRole('alert')).toContainText(/could not be recorded|nepodařilo uložit/)
    await expect(dialog).toBeVisible()
    await confirm.click()

    await expect(dialog).toBeHidden()
    await expect(page.getByRole('cell', { name: proposal.title })).toBeVisible()
    await expect(page.getByRole('cell', { name: /Approved|Schváleno/ })).toBeVisible()
    await expect(page.getByRole('cell', { name: 'e2e-operator@openbank.test' })).toBeVisible()
    await expect(page.getByRole('cell', { name: 'Evidence independently checked.' })).toBeVisible()
    expect(decisionRequests).toBe(2)
  })

  test('filters domain work and hands a sanctions item to its governed checker', async ({ page }) => {
    const sanctionsApproval = {
      id: 'sanctions-approval / 42', domain: 'sanctions', action: 'sanctions.clear',
      resourceId: 'check-42', maker: 'maker.sanctions', makerActorKind: 'AI_AGENT', proposedAt: '2026-08-31T08:00:00Z',
    }
    const notificationApproval = {
      id: 'notification-approval-7', domain: 'notification', action: 'opsmessage.compose',
      resourceId: null, maker: 'maker.notifications', proposedAt: '2026-08-31T09:00:00Z',
    }
    const balanceApproval = {
      id: 'balance-approval-3', domain: 'balance', action: 'balance.debit',
      resourceId: 'account-3', maker: 'maker.balance', proposedAt: '2026-08-31T10:00:00Z',
    }
    const billingApproval = {
      id: 'billing-approval-4', domain: 'billing', action: 'fee.post',
      resourceId: 'fee-4', maker: 'maker.billing', makerActorKind: 'HUMAN', proposedAt: '2026-08-31T11:00:00Z',
    }

    await page.route('**/api/agent/proposals*', route =>
      route.fulfill({ contentType: 'application/json', body: '[]' }),
    )
    await page.route('**/api/approvals/pending', route => route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        items: [billingApproval, balanceApproval, sanctionsApproval, notificationApproval],
        sources: approvalSources({ sanctions: 'ok', notification: 'ok', balance: 'ok', billing: 'ok' }),
      }),
    }))
    await page.route('**/api/governance/agent-identities', route => route.fulfill({
      contentType: 'application/json', body: JSON.stringify({ available: true, agents: [] }),
    }))
    await page.route('**/api/sanctions/checks', route =>
      route.fulfill({ contentType: 'application/json', body: '[]' }),
    )
    await page.route('**/api/sanctions/lists', route =>
      route.fulfill({ contentType: 'application/json', body: '[]' }),
    )
    await page.route('**/api/sanctions/approvals', route =>
      route.fulfill({ contentType: 'application/json', body: JSON.stringify([{
        id: sanctionsApproval.id,
        action: sanctionsApproval.action,
        resourceId: sanctionsApproval.resourceId,
        status: 'PENDING',
        makerId: sanctionsApproval.maker,
        makerActorKind: sanctionsApproval.makerActorKind,
        createdAt: sanctionsApproval.proposedAt,
      }]) }),
    )

    await page.goto('/approvals')

    const rows = page.locator('[data-testid^="domain-approval-"]')
    await expect(rows).toHaveCount(4)
    await expect(rows.nth(0)).toContainText(sanctionsApproval.action)
    await page.getByLabel(/^(Order|Pořadí)$/).selectOption('newest')
    await expect(rows.nth(0)).toContainText(billingApproval.action)
    await expect(rows.nth(0).getByTestId('approval-resource')).toContainText(billingApproval.resourceId)
    await expect(rows.nth(0).getByTestId('approval-maker')).toContainText(billingApproval.maker)
    await expect(rows.nth(0).getByTestId('approval-maker-kind')).toContainText(/Human|Člověk/)
    await expect(rows.nth(0).locator('time')).toHaveAttribute('datetime', billingApproval.proposedAt)

    await page.getByLabel(/^(Domain|Doména)$/).selectOption('sanctions')
    await expect(rows).toHaveCount(1)
    await expect(rows.first()).toContainText(sanctionsApproval.action)
    await expect(rows.first().getByTestId('approval-maker-kind')).toContainText('AI agent')
    await page.getByLabel(/Search queue|Hledat ve frontě/).fill('maker.sanctions')
    await expect(rows).toHaveCount(1)

    const handoff = page.getByRole('link', { name: new RegExp(`Open governed review for approval ${sanctionsApproval.id}|Otevřít řízenou kontrolu žádosti ${sanctionsApproval.id}`) })
    await expect(handoff).toHaveAttribute('href', '/sanctions?approvalId=sanctions-approval%20%2F%2042#sanctions-approval-id')
    await Promise.all([
      page.waitForURL(
        /\/sanctions\?approvalId=sanctions-approval%20%2F%2042#sanctions-approval-id$/,
        { waitUntil: 'domcontentloaded', timeout: 15_000 },
      ),
      handoff.click(),
    ])
    await expect(page.getByLabel(/Approval id|ID žádosti/)).toHaveValue(sanctionsApproval.id)
  })

  test('never reports an empty domain queue when the federated read itself failed', async ({ page }) => {
    await page.route('**/api/agent/proposals*', route =>
      route.fulfill({ contentType: 'application/json', body: '[]' }),
    )
    await page.route('**/api/approvals/pending', route =>
      route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'aggregator unavailable' }) }),
    )
    await page.route('**/api/governance/agent-identities', route => route.fulfill({
      contentType: 'application/json', body: JSON.stringify({ available: true, agents: [] }),
    }))

    await page.goto('/approvals')

    await expect(page.getByText(/Domain approval inbox could not be loaded|Doménovou schvalovací frontu se nepodařilo načíst/)).toBeVisible()
    await expect(page.getByText(/No domain approvals pending|Žádná doménová schvalování nečekají/)).toHaveCount(0)
  })

  test('shows treasury and backfill audit context without masking a truncated backfill source', async ({ page }) => {
    await page.route('**/api/agent/proposals*', route =>
      route.fulfill({ contentType: 'application/json', body: '[]' }),
    )
    await page.route('**/api/approvals/pending', route => route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        items: [
          { id: 'deal-7', domain: 'treasury', action: 'treasury.MM_PLACEMENT', resourceId: 'deal-7', maker: 'dealer.two', proposedAt: '2026-09-20T10:00:00Z' },
          { id: 'request-7', domain: 'ledger-backfill', action: 'lending.ledgerBackfill.decide', resourceId: 'request-7', maker: 'finance.one', proposedAt: '2026-09-20T11:00:00Z' },
        ],
        sources: approvalSources({ treasury: 'ok', 'ledger-backfill': 'unavailable' }),
      }),
    }))
    await page.route('**/api/governance/agent-identities', route => route.fulfill({
      contentType: 'application/json', body: JSON.stringify({ available: true, agents: [] }),
    }))

    await page.goto('/approvals')

    await expect(page.getByText(/This queue is incomplete|Fronta není úplná/)).toContainText('ledger-backfill')
    const treasury = page.getByTestId('domain-approval-treasury:deal-7')
    await expect(treasury.getByTestId('approval-maker')).toContainText('dealer.two')
    await expect(treasury.locator('time')).toHaveAttribute('datetime', '2026-09-20T10:00:00Z')
    await expect(treasury.getByRole('link')).toHaveAttribute('href', '/treasury/deals/deal-7')
    const backfill = page.getByTestId('domain-approval-ledger-backfill:request-7')
    await expect(backfill.getByTestId('approval-maker')).toContainText('finance.one')
    await expect(backfill.getByRole('link')).toHaveAttribute('href', '/balance-sheet/ledger-backfill')
    await expect(page.getByText(/No domain approvals pending|Žádná doménová schvalování nečekají/)).toHaveCount(0)
  })

  test('hands specialist four-eyes proposals to existing workbenches without inventing audience time', async ({ page }) => {
    await page.route('**/api/agent/proposals*', route => route.fulfill({ contentType: 'application/json', body: '[]' }))
    await page.route('**/api/approvals/pending', route => route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        items: [
          { id: 'pack-7', domain: 'compliance-pack', action: 'lending.compliancePack.activate', resourceId: 'pack-7', maker: 'risk.officer', proposedAt: '2026-09-20T08:00:00Z' },
          { id: 'campaign-7', domain: 'campaign', action: 'campaign.activate', resourceId: 'campaign-7', maker: 'marketer.one', proposedAt: '2026-09-20T09:00:00Z' },
          { id: 'newcomers@3', domain: 'audience', action: 'campaign.audience.approve', resourceId: 'newcomers@3', maker: 'marketer.three', proposedAt: null },
          { id: 'case-7', domain: 'identity-case', action: 'identity.case.secondApproval', resourceId: 'case-7', maker: 'checker.one', proposedAt: '2026-09-20T10:00:00Z' },
        ],
        sources: approvalSources({ 'compliance-pack': 'ok', campaign: 'ok', audience: 'ok', 'identity-case': 'ok' }),
      }),
    }))
    await page.route('**/api/governance/agent-identities', route => route.fulfill({
      contentType: 'application/json', body: JSON.stringify({ available: true, agents: [] }),
    }))

    await page.goto('/approvals')

    for (const [key, maker, href] of [
      ['compliance-pack:pack-7', 'risk.officer', '/lending/compliance-packs'],
      ['campaign:campaign-7', 'marketer.one', '/campaigns/campaign-7'],
      ['audience:newcomers@3', 'marketer.three', '/segments'],
      ['identity-case:case-7', 'checker.one', '/identity-cases'],
    ]) {
      const row = page.getByTestId(`domain-approval-${key}`)
      await expect(row.getByTestId('approval-maker')).toContainText(maker)
      await expect(row.getByRole('link')).toHaveAttribute('href', href)
    }
    await expect(page.getByTestId('domain-approval-audience:newcomers@3').locator('time')).toHaveCount(0)
  })
})
