-- SPDX-License-Identifier: Apache-2.0
-- ADR-0333 D6: immutable published customer copy with a different publishing actor.
-- Rollback: stop creating revisions, retain the rows for message evidence, and let the
-- notification runtime use its built-in reviewed copy. Drop only after retention review.
CREATE TABLE managed_notification_templates (
    id UUID PRIMARY KEY,
    template TEXT NOT NULL,
    language TEXT NOT NULL CHECK (language IN ('CS', 'EN')),
    channel TEXT NOT NULL CHECK (channel IN ('EMAIL', 'PUSH', 'INBOX')),
    revision BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    state TEXT NOT NULL CHECK (state IN ('DRAFT', 'PUBLISHED')),
    subject VARCHAR(120) NOT NULL,
    body TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    published_by TEXT,
    published_at TIMESTAMPTZ,
    CHECK (published_by IS NULL OR created_by <> published_by),
    CHECK ((state = 'DRAFT' AND published_by IS NULL AND published_at IS NULL) OR
           (state = 'PUBLISHED' AND published_by IS NOT NULL AND published_at IS NOT NULL))
);
CREATE FUNCTION guard_managed_notification_revision() RETURNS trigger AS $$
BEGIN
    IF OLD.state <> 'DRAFT' OR NEW.state <> 'PUBLISHED'
       OR NEW.id <> OLD.id OR NEW.template <> OLD.template
       OR NEW.language <> OLD.language OR NEW.channel <> OLD.channel
       OR NEW.revision <> OLD.revision OR NEW.subject <> OLD.subject
       OR NEW.body <> OLD.body OR NEW.created_by <> OLD.created_by
       OR NEW.created_at <> OLD.created_at THEN
        RAISE EXCEPTION 'managed notification revision is immutable';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER guard_managed_notification_revision_update
BEFORE UPDATE ON managed_notification_templates
FOR EACH ROW EXECUTE FUNCTION guard_managed_notification_revision();
CREATE INDEX idx_managed_template_latest ON managed_notification_templates
    (template, language, channel, published_at DESC, revision DESC) WHERE state = 'PUBLISHED';

-- NULL means the reviewed built-in renderer supplied the copy.
ALTER TABLE notifications ADD COLUMN template_revision BIGINT;
ALTER TABLE notifications ADD COLUMN visible_at TIMESTAMPTZ;
