#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
"""Generate per-namespace NetworkPolicies from the declared GitOps edges (ADR-0081).

The allow-lists are DERIVED, never hand-edited (house rule, ADR-0029/0074/0081):
every cross-namespace call a service makes is already declared in its Deployment
env (`http://<svc>.<ns>.svc:<port>`), every public path in an Ingress backend,
every Kafka client in its bootstrap URL. This script walks
openbank-infra/gitops/components/, extracts those edges and emits one
`network-policies.yaml` per service namespace:

  - pod-scoped ingress allow-lists (Postgres/Redis pods stay unselected — the
    blast radius of the existing accounts/balances drafts, generalised),
  - same-namespace traffic always allowed,
  - observability allowed on the management port (Prometheus PodMonitor) AND on
    every other port a Pod/ServiceMonitor actually scrapes (e.g. the redis_exporter
    sidecar on 9121, keycloak management on 9000) — the scrape edge is DERIVED from
    the monitor specs, not a hardcoded 8085, so a new metrics endpoint with a
    monitor is reachable by Prometheus the moment its monitor is declared,
  - admin-ui allowed on every service HTTP port (the BFF discovers services
    dynamically via the k8s API, ADR-0051/0056 — its edges are not in env),
  - ingress-nginx allowed where an Ingress backend declares it,
  - the Strimzi broker gets a dedicated policy from the derived client set.

Enforcement is LIVE: the VPC CNI network-policy agent runs in standard mode
(aws/modules/eks: enableNetworkPolicy; NETWORK_POLICY_ENFORCING_MODE=standard,
ADR-0060). These allow-lists actively gate cross-namespace traffic — an edge a
service needs that is NOT captured here (nor in a hand-maintained policy like
temporal-network-policies.yaml) is DROPPED, and a synchronous client (e.g. a
Temporal worker started in onStart) will fail to boot. Re-run after adding a
service or a cross-service call:

    python3 openbank-infra/scripts/gen-network-policies.py
"""

import glob
import os
import re
import sys
from collections import defaultdict

import yaml


class IndentedDumper(yaml.SafeDumper):
    """Indent block sequences under their parent key (repo yamllint style)."""

    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMPONENTS = os.path.join(ROOT, "gitops", "components")

URL_RE = re.compile(r"https?://([a-z0-9-]+)\.([a-z0-9-]+)\.svc(?::(\d+))?")
KAFKA_RE = re.compile(r"([a-z0-9-]+-kafka-bootstrap)\.([a-z0-9-]+)\.svc:(\d+)")

MGMT_PORT = 8085
OBSERVABILITY_NS = "observability"
SECURITY_SCANNER_NS = "security-scanner"
ADMIN_UI_NS = "admin-ui"
INGRESS_NS = "ingress-nginx"
MESSAGING_NS = "messaging"

HEADER = """\
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
#
# DO NOT EDIT — generated by openbank-infra/scripts/gen-network-policies.py
# (ADR-0081: NetworkPolicy baseline derived from the declared GitOps edges).
#
# Pod-scoped ingress allow-lists: each rule admits only the namespaces whose
# Deployments declare a call to this service (env URLs), plus the static
# platform edges (same-namespace, Prometheus scrape on {mgmt}, security-scanner
# posture probe on {mgmt}, admin-ui BFF discovery, ingress-nginx where an Ingress
# backend exists). CNPG Postgres
# pods are NOT selected (operator-managed, no Deployment) — intra-namespace
# data traffic is unaffected; Deployment-managed stores (e.g. redis) get a
# same-namespace-only policy, which is their entire caller set.
#
# ENFORCED: the VPC CNI network-policy agent runs in standard mode (ADR-0060),
# so this allow-list actively gates ingress — an undeclared caller is DROPPED.
# Rollback = delete the NetworkPolicy.
""".format(mgmt=MGMT_PORT)


def load_docs():
    docs = []
    for path in sorted(glob.glob(f"{COMPONENTS}/**/*.yaml", recursive=True)):
        if path.endswith("network-policies.yaml"):
            continue
        try:
            with open(path, encoding="utf-8") as fh:
                for doc in yaml.safe_load_all(fh):
                    if isinstance(doc, dict) and doc.get("kind"):
                        docs.append((path, doc))
        except yaml.YAMLError:
            print(f"  warn: skipping unparseable {path}", file=sys.stderr)
    return docs


def main():
    docs = load_docs()

    # workload key: (ns, app.kubernetes.io/name) -> {"ports": {name: num}}
    workloads = {}
    # ns -> components/<dir> that declares its workloads (dir name != ns for
    # e.g. keycloak->iam, kafka->messaging, sanctions-service->sanctions)
    ns_dir = {}
    # service key: (ns, svc-name) -> {"selector": {...}, "ports": [(port, targetPort)]}
    services = {}
    # edges: (callee_ns, callee_svc) -> set of caller namespaces; port via svc
    edges = defaultdict(set)
    edge_ports = defaultdict(set)  # (callee_ns, callee_svc) -> ports
    ingress_backends = defaultdict(set)  # (ns, svc-name) -> ports
    kafka_clients = set()
    # Prometheus scrape edges declared by Pod/ServiceMonitors:
    #   (target_ns, app.kubernetes.io/name) -> set of port NAMES Prometheus scrapes.
    # Resolved to container ports after the workload table is built, then admitted
    # from the observability namespace alongside the management port.
    monitors = []  # (target_namespaces, app-name, [port-names])

    for path, doc in docs:
        kind = doc.get("kind")
        meta = doc.get("metadata", {}) or {}
        ns = meta.get("namespace")

        if kind in ("Deployment", "StatefulSet", "Rollout") and ns:
            tpl = doc.get("spec", {}).get("template", {}) or {}
            labels = (tpl.get("metadata", {}) or {}).get("labels", {}) or {}
            name = labels.get("app.kubernetes.io/name") or meta.get("name")
            ports = {}
            blob_parts = []
            for c in (tpl.get("spec", {}) or {}).get("containers", []) or []:
                for p in c.get("ports", []) or []:
                    if p.get("containerPort"):
                        ports[p.get("name") or str(p["containerPort"])] = p["containerPort"]
                for e in c.get("env", []) or []:
                    v = e.get("value")
                    if isinstance(v, str):
                        blob_parts.append(v)
            workloads[(ns, name)] = {"ports": ports}
            ns_dir.setdefault(ns, os.path.dirname(path))
            blob = "\n".join(blob_parts)
            for svc, callee_ns, port in URL_RE.findall(blob):
                if callee_ns == ns:
                    continue  # same-namespace is allowed wholesale
                edges[(callee_ns, svc)].add(ns)
                if port:
                    edge_ports[(callee_ns, svc)].add(int(port))
            for _, kns, kport in KAFKA_RE.findall(blob):
                if kns == MESSAGING_NS:
                    kafka_clients.add(ns)

        elif kind == "Service" and ns:
            spec = doc.get("spec", {}) or {}
            services[(ns, meta.get("name"))] = {
                "selector": spec.get("selector", {}) or {},
                "ports": [
                    (p.get("port"), p.get("targetPort", p.get("port")))
                    for p in spec.get("ports", []) or []
                ],
            }

        elif kind in ("PodMonitor", "ServiceMonitor"):
            spec = doc.get("spec", {}) or {}
            app = ((spec.get("selector", {}) or {})
                   .get("matchLabels", {}) or {}).get("app.kubernetes.io/name")
            if not app:
                continue  # only label-selected monitors are derivable here
            target_ns = (spec.get("namespaceSelector", {}) or {}).get("matchNames") or ([ns] if ns else [])
            eps = spec.get("podMetricsEndpoints") or spec.get("endpoints") or []
            port_names = [e.get("port") for e in eps if e.get("port")]
            if target_ns and port_names:
                monitors.append((target_ns, app, port_names))

        elif kind == "Ingress" and ns:
            for rule in (doc.get("spec", {}) or {}).get("rules", []) or []:
                for p in ((rule.get("http", {}) or {}).get("paths", []) or []):
                    be = (p.get("backend", {}) or {}).get("service", {}) or {}
                    if be.get("name"):
                        port = (be.get("port", {}) or {}).get("number")
                        ingress_backends[(ns, be["name"])].add(port)

    def resolve_pod_port(ns, svc_name, svc_port):
        """Service port -> containerPort on the selected workload."""
        svc = services.get((ns, svc_name))
        if not svc:
            return svc_port
        for port, target in svc["ports"]:
            if svc_port in (None, port):
                if isinstance(target, int):
                    return target
                wl_name = svc["selector"].get("app.kubernetes.io/name", svc_name)
                wl = workloads.get((ns, wl_name))
                if wl and target in wl["ports"]:
                    return wl["ports"][target]
        return svc_port

    def ns_peer(name):
        return {
            "namespaceSelector": {
                "matchLabels": {"kubernetes.io/metadata.name": name}
            }
        }

    # ── resolve monitor port NAMES to container ports per workload ───────────
    # (target_ns, app-name) -> {container ports Prometheus scrapes}. A PodMonitor
    # names a container port directly; a ServiceMonitor names a Service port, which
    # we map through the Service to its targetPort. Either way the result is the
    # pod port the scrape lands on, which is what the NetworkPolicy must admit.
    scrape_ports = defaultdict(set)
    for target_ns, app, port_names in monitors:
        for tns in target_ns:
            wl = workloads.get((tns, app))
            for pn in port_names:
                cp = None
                if wl and pn in wl["ports"]:
                    cp = wl["ports"][pn]                  # PodMonitor: container port name
                else:
                    # ServiceMonitor: the endpoint names a SERVICE port. We don't track
                    # service port names here, so resolve only when the Service exposes a
                    # single (unambiguous) port — emit nothing rather than guess wrong for
                    # a multi-port service.
                    svc = services.get((tns, app))
                    if svc and len(svc["ports"]) == 1:
                        cp = resolve_pod_port(tns, app, svc["ports"][0][0])
                if cp:
                    scrape_ports[(tns, app)].add(cp)

    # ── emit one file per namespace that has workloads ───────────────────────
    by_ns = defaultdict(list)

    # CI infrastructure is reached by ARC runner pods whose namespace lives
    # outside GitOps (tofu-managed) — a derived allow-list cannot see them and
    # would cut CI off the moment enforcement is enabled. Out of scope here.
    skip_ns = {"registry-cache", "gradle-build-cache", "external-dns"}

    for (ns, wl_name), wl in sorted(workloads.items()):
        if ns in skip_ns:
            continue
        # The fleet PodMonitor scrapes the port NAMED "management" — 8085 by
        # convention, but some workloads expose it on a different number (e.g.
        # clearing-simulator on 8087). Resolve it by name so the management port is
        # admitted to observability (not callers) regardless of its number, and is
        # not mistaken for a service HTTP port below.
        mgmt_port = wl["ports"].get("management")
        if mgmt_port is None and MGMT_PORT in wl["ports"].values():
            mgmt_port = MGMT_PORT
        http_ports = sorted(
            p for n, p in wl["ports"].items() if p != mgmt_port
        )
        callers = sorted(edges.get((ns, wl_name), set()) - {ns})
        ing_ports = {
            resolve_pod_port(ns, wl_name, p)
            for p in ingress_backends.get((ns, wl_name), set())
        }

        rules = [{"from": [{"podSelector": {}}]}]  # same-namespace
        if http_ports:
            peers = [ns_peer(c) for c in callers if c != ADMIN_UI_NS]
            peers.append(ns_peer(ADMIN_UI_NS))  # BFF dynamic discovery
            rules.append({
                "from": peers,
                "ports": [{"protocol": "TCP", "port": p} for p in http_ports],
            })
        # Prometheus scrape: the Quarkus management port (the fleet PodMonitor's
        # `port: management`, resolved by name above) plus any extra port a dedicated
        # Pod/ServiceMonitor targets (redis_exporter 9121, keycloak management 9000,
        # …). Without these the scrape is silently DROPPED by this very allow-list,
        # the target goes "context deadline exceeded", and TargetDown/PaymentServiceDown
        # fire as permanent false positives.
        obs_ports = set(scrape_ports.get((ns, wl_name), set()))
        if mgmt_port is not None:
            obs_ports.add(mgmt_port)
        if obs_ports:
            rules.append({
                "from": [ns_peer(OBSERVABILITY_NS)],
                "ports": [{"protocol": "TCP", "port": p} for p in sorted(obs_ports)],
            })
        # security-scanner posture probe (#1811): openbank-security-scanner performs
        # read-only GET hygiene checks against the Quarkus management port (/q/health,
        # /q/health/ready, CWE-312 sensitive-data check). Grant it the management port
        # ONLY — never the API/http port — so it verifies liveness and health-endpoint
        # hygiene fleet-wide without widening the API attack surface of money-path
        # services. Scoped to workloads that actually expose a management port; the
        # scanner's targets are in its own config (not env), so this static edge is the
        # derivation point (the scanner namespace is not otherwise a declared caller).
        if mgmt_port is not None:
            rules.append({
                "from": [ns_peer(SECURITY_SCANNER_NS)],
                "ports": [{"protocol": "TCP", "port": mgmt_port}],
            })
        if ing_ports:
            rules.append({
                "from": [ns_peer(INGRESS_NS)],
                "ports": [{"protocol": "TCP", "port": p} for p in sorted(ing_ports)],
            })

        by_ns[ns].append({
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": {
                "name": f"{wl_name}-ingress-allow-list",
                "namespace": ns,
                "labels": {
                    "app.kubernetes.io/part-of": ns,
                    "openbank.io/derived": "gen-network-policies",
                },
            },
            "spec": {
                "podSelector": {
                    "matchLabels": {"app.kubernetes.io/name": wl_name}
                },
                "policyTypes": ["Ingress"],
                "ingress": rules,
            },
        })

    # ── Strimzi broker: derived client set on the client listener ───────────
    if kafka_clients:
        by_ns[MESSAGING_NS].append({
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": {
                "name": "kafka-broker-ingress-allow-list",
                "namespace": MESSAGING_NS,
                "labels": {
                    "app.kubernetes.io/part-of": MESSAGING_NS,
                    "openbank.io/derived": "gen-network-policies",
                },
            },
            "spec": {
                "podSelector": {
                    "matchLabels": {"strimzi.io/cluster": "openbank-cluster"}
                },
                "policyTypes": ["Ingress"],
                "ingress": [
                    {"from": [{"podSelector": {}}]},  # operator/entity/kafka-ui
                    {
                        "from": [ns_peer(c) for c in sorted(kafka_clients)],
                        "ports": [{"protocol": "TCP", "port": 9092}],
                    },
                ],
            },
        })

    for ns, policies in sorted(by_ns.items()):
        out_dir = ns_dir.get(ns, os.path.join(COMPONENTS, ns))
        out = os.path.join(out_dir, "network-policies.yaml")
        if not os.path.isdir(out_dir):
            print(f"  warn: no components dir for ns {ns} — skipping", file=sys.stderr)
            continue
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(HEADER)
            for pol in policies:
                fh.write("---\n")
                yaml.dump(pol, fh, Dumper=IndentedDumper,
                          sort_keys=False, default_flow_style=False)
        print(f"wrote {os.path.relpath(out, ROOT)} ({len(policies)} policies)")


if __name__ == "__main__":
    main()
