// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

package com.openbank.lending.infrastructure.adapter

import com.openbank.lending.application.port.out.BorrowerCreditPort
import com.openbank.lending.application.port.out.LedgerPostingPort
import com.openbank.lending.application.port.out.LoanEventEmitter
import com.openbank.lending.application.port.out.OriginationWorkflowPort
import io.micrometer.core.instrument.MeterRegistry
import io.micrometer.core.instrument.Tag
import io.quarkus.arc.ClientProxy
import io.quarkus.runtime.Startup
import jakarta.enterprise.context.ApplicationScoped
import org.eclipse.microprofile.config.inject.ConfigProperty
import org.jboss.logging.Logger
import java.util.concurrent.atomic.AtomicInteger

/**
 * One outbound port's declared backend, and the implementation ArC actually bound for it.
 *
 * [realBound] is read from the *effect* — the class behind the client proxy — never from a second
 * copy of the configuration, which would agree with the first and prove nothing.
 */
data class AdapterBinding(
    val property: String,
    val envVar: String,
    val runtimeValue: String,
    val realValue: String,
    val boundImplementation: String,
) {
    /** The offline `@Default` bindings in this package are the `NoOp*` / `Logging*` classes. */
    val realBound: Boolean =
        !boundImplementation.startsWith("NoOp") && !boundImplementation.startsWith("Logging")

    /** What the runtime configuration asks for, which a build-time gate may not have delivered. */
    val wantsReal: Boolean = runtimeValue == realValue

    /** The dangerous direction: configuration promises a real backend and a silent stand-in is bound. */
    val silentlyInert: Boolean = wantsReal && !realBound

    fun describe(): String =
        "$property='$runtimeValue' at runtime (container env $envVar) selects the real backend, but " +
            "the image was built with $boundImplementation bound"
}

/**
 * Refuses to boot when a port's **runtime** backend selection disagrees with the implementation
 * actually baked into the image at **build** time (#6057).
 *
 * ## The defect this exists to make impossible
 *
 * The four outbound ports below are selected with `@IfBuildProperty`, which Quarkus resolves
 * during augmentation and freezes into the image: ArC removes the losing bean's class outright.
 * The deployment, however, activated them with container **env vars** — `LENDING_LEDGER_BACKEND`,
 * `LENDING_BORROWER_CREDIT_BACKEND` — which are read at runtime and cannot change a decision the
 * image no longer contains. Both sides looked correct in isolation, and the combination was inert.
 *
 * Measured on the deployed image before this class existed, by grepping ArC's generated bytecode
 * inside the running pod: `RestLedgerPostingAdapter` 0 occurrences, `NoOpLedgerPostingPort` 4;
 * `BorrowerCreditClient` 0, `NoOpBorrowerCreditPort` 4 — while that same pod's environment held
 * `LENDING_LEDGER_BACKEND=rest`. The `lending.outbox.backend` pair was the control that proved the
 * probe could tell the two apart (`JpaLoanEventEmitter` 4, `LoggingLoanEventEmitter` 0), and it
 * only worked because its `application.yaml` default already *was* the production value.
 *
 * The same probe, re-run independently for #6085, found the third property in the same state:
 * `TemporalOriginationWorkflowAdapter` **0** occurrences, `NoOpOriginationWorkflowPort` **4**,
 * with `OPENBANK_TEMPORAL_ENABLED=true` in that pod's environment. No origination durable timer —
 * document SLA, offer expiry, consumer-credit reflection period — had ever been armed.
 *
 * ## Why a boot-time check, and why `@Startup`
 *
 * `@ApplicationScoped` is lazy: a guard in an `init {}` block runs on first *use* of the bean,
 * which for a config-sanity check can be long after the deploy reports green — or never.
 * `@Startup` forces construction during boot, so a mismatch is a failed Rollout instead of money
 * postings quietly going nowhere. Fixing only the defaults would not be enough: it would make
 * today's image right by coincidence and leave the next person free to repeat the
 * env-var-that-does-nothing mistake with no signal at all.
 *
 * Only the *silently inert* direction refuses the boot. The reverse — a real adapter bound while
 * the runtime value says otherwise — is logged at `warn`: it is surprising, but it is the loud
 * kind of surprise, and it is the ordinary shape of a test that installs a higher-priority
 * `@Alternative` stub over the no-op.
 */
@Startup
@ApplicationScoped
// LongParameterList (detekt fires AT the threshold of 9, not above it): every parameter is load-
// bearing and none can move to field injection — the verification runs in `init {}`, which is
// exactly the point, and `@Inject lateinit var` fields are not populated until after it. Each port
// is here to be UNWRAPPED, and each property to be compared against the class that unwrapping
// reveals; dropping either half of a pair would remove a check rather than tidy a signature.
@Suppress("LongParameterList")
class LendingAdapterBindingVerifier(
    ledger: LedgerPostingPort,
    borrowerCredit: BorrowerCreditPort,
    events: LoanEventEmitter,
    originationWorkflow: OriginationWorkflowPort,
    meters: MeterRegistry,
    @ConfigProperty(name = "lending.ledger.backend") ledgerBackend: String,
    @ConfigProperty(name = "lending.borrower-credit.backend") borrowerCreditBackend: String,
    @ConfigProperty(name = "lending.outbox.backend") outboxBackend: String,
    @ConfigProperty(name = "openbank.temporal.enabled") temporalEnabled: String,
) {
    /** Strongly held so the Micrometer gauges below are not collected out from under the registry. */
    private val gaugeValues = mutableListOf<AtomicInteger>()

    init {
        val bindings = listOf(
            AdapterBinding(
                "lending.ledger.backend",
                "LENDING_LEDGER_BACKEND",
                ledgerBackend,
                REST,
                implementationOf(ledger),
            ),
            AdapterBinding(
                "lending.borrower-credit.backend",
                "LENDING_BORROWER_CREDIT_BACKEND",
                borrowerCreditBackend,
                REST,
                implementationOf(borrowerCredit),
            ),
            AdapterBinding(
                "lending.outbox.backend",
                "LENDING_OUTBOX_BACKEND",
                outboxBackend,
                JPA,
                implementationOf(events),
            ),
            // #6085, the same mechanism on a third property this class did not originally cover.
            // Its "real" value is the boolean `true` rather than a backend name, which is why
            // AdapterBinding compares strings: what matters is whether the runtime selection and
            // the bound class agree, not what the selector is spelled like.
            AdapterBinding(
                "openbank.temporal.enabled",
                "OPENBANK_TEMPORAL_ENABLED",
                temporalEnabled,
                ENABLED,
                implementationOf(originationWorkflow),
            ),
        )

        bindings.forEach { publish(meters, it) }
        verify(bindings)
    }

    /**
     * Named for what this service can establish — which implementation is bound — and deliberately
     * not for what a posting achieves downstream, which it cannot observe.
     */
    private fun publish(meters: MeterRegistry, binding: AdapterBinding) {
        val value = AtomicInteger(if (binding.realBound) 1 else 0)
        gaugeValues += value
        meters.gauge(
            "openbank_lending_adapter_real_backend_bound",
            listOf(
                Tag.of("property", binding.property),
                Tag.of("implementation", binding.boundImplementation),
            ),
            value,
        )
    }

    private fun verify(bindings: List<AdapterBinding>) {
        bindings.filter { !it.realBound && !it.wantsReal }.forEach {
            LOG.warnf(
                "%s='%s': the offline %s is bound. It REFUSES every call rather than reporting " +
                    "success, so this build cannot reach the real backend.",
                it.property,
                it.runtimeValue,
                it.boundImplementation,
            )
        }
        bindings.filter { it.realBound && !it.wantsReal }.forEach {
            LOG.warnf(
                "%s='%s' does not select the real backend, yet %s is bound — calls WILL reach the " +
                    "real system.",
                it.property,
                it.runtimeValue,
                it.boundImplementation,
            )
        }

        val inert = bindings.filter { it.silentlyInert }
        if (inert.isNotEmpty()) {
            throw IllegalStateException(
                "Outbound adapter binding does not match the runtime configuration. These are " +
                    "BUILD-time (@IfBuildProperty) selections frozen into the image during " +
                    "augmentation; a container env var cannot change them. Rebuild the image with " +
                    "the intended value. " + inert.joinToString("; ") { it.describe() },
            )
        }
    }

    private companion object {
        val LOG: Logger = Logger.getLogger(LendingAdapterBindingVerifier::class.java)
        const val REST = "rest"
        const val JPA = "jpa"
        const val ENABLED = "true"

        fun implementationOf(port: Any): String = ClientProxy.unwrap(port)::class.java.simpleName
    }
}
