// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) OpenBank contributors. Licensed under the GNU Affero General Public License v3.0 only.
// A commercial licence is available from the maintainers as an alternative to the AGPL-3.0.
// See LICENSES/AGPL-3.0-only.txt or https://www.gnu.org/licenses/agpl-3.0.html for details.

package com.openbank.docstruth.infrastructure.persistence

import com.openbank.docstruth.domain.model.DocsTruthCheckType
import com.openbank.docstruth.domain.model.FindingSeverity
import com.openbank.docstruth.domain.model.FindingStatus
import io.quarkus.hibernate.reactive.panache.kotlin.PanacheCompanionBase
import io.quarkus.hibernate.reactive.panache.kotlin.PanacheEntityBase
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.math.BigDecimal
import java.time.Instant
import java.util.UUID

/**
 * Persisted docs-truth finding (ADR-0166). Reactive Panache entity (the fleet standard). The id is
 * assigned in the domain (Ids.newId()), not generated by the DB.
 */
@Entity
@Table(name = "findings")
class FindingEntity : PanacheEntityBase {

    companion object : PanacheCompanionBase<FindingEntity, UUID>

    @Id
    @Column(columnDefinition = "uuid")
    lateinit var id: UUID

    @Column(name = "check_type", nullable = false)
    @Enumerated(EnumType.STRING)
    lateinit var checkType: DocsTruthCheckType

    @Column(name = "severity", nullable = false)
    @Enumerated(EnumType.STRING)
    lateinit var severity: FindingSeverity

    @Column(name = "detected_at", nullable = false)
    lateinit var detectedAt: Instant

    @Column(name = "title", columnDefinition = "TEXT", nullable = false)
    lateinit var title: String

    @Column(name = "component", nullable = false)
    lateinit var component: String

    @Column(name = "adr_path", nullable = false)
    lateinit var adrPath: String

    @Column(name = "raw_metric_value", nullable = false)
    lateinit var rawMetricValue: BigDecimal

    @Column(name = "threshold", nullable = false)
    lateinit var threshold: BigDecimal

    @Column(name = "root_cause", columnDefinition = "TEXT")
    var rootCause: String? = null

    @Column(name = "proposal_url")
    var proposalUrl: String? = null

    @Column(name = "proposed_fix_diff", columnDefinition = "TEXT")
    var proposedFixDiff: String? = null

    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    lateinit var status: FindingStatus

    @Column(name = "diagnosed_at")
    var diagnosedAt: Instant? = null

    @Column(name = "proposed_at")
    var proposedAt: Instant? = null
}
