// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

package com.openbank.libs.web

import jakarta.annotation.security.PermitAll
import jakarta.enterprise.context.ApplicationScoped
import jakarta.ws.rs.GET
import jakarta.ws.rs.Path
import jakarta.ws.rs.Produces
import jakarta.ws.rs.core.MediaType
import jakarta.ws.rs.core.Response
import org.eclipse.microprofile.config.inject.ConfigProperty
import java.nio.file.Files
import java.nio.file.Paths
import java.util.Optional

/**
 * Self-publishes the service's own CycloneDX SBOM at `/q/openbank/sbom`.
 *
 * Conceptually a "management endpoint" — same pattern as `/q/openbank/docs`
 * (DocsResource), `/q/health`, `/q/metrics`: served under the well-known `/q/...`
 * prefix, no app-level auth (mgmt path is network-gated), version-locked with the
 * running image.
 *
 * The `bom.json` is generated by the Gradle CycloneDX plugin (`cyclonedxBom`,
 * schema 1.5, `runtimeClasspath`) and **baked into the image** at deploy-build
 * time — copied to `OPENBANK_SBOM_PATH` (default `/app/sbom/bom.json`) by
 * build-push-service.sh and the per-service Dockerfile. Because the SBOM travels
 * inside the image, what a running service reports here is exactly what was built.
 *
 * Scope (deliberate):
 *   - This is an OPERATIONAL view (what's running), NOT supply-chain integrity.
 *     A signed, attested CycloneDX as a first-class release artifact (cosign /
 *     SLSA, ADR-0029 D2) is a separate, still-open concern.
 *   - Build-time CycloneDX covers JVM/Gradle dependencies, NOT the container OS
 *     layer (base image, sidecars) — ADR-0030 "no runtime SBOM drift" still holds.
 *
 * Endpoint:
 *   GET /q/openbank/sbom  → 200 CycloneDX JSON, or 404 {"status":"not_generated"}
 *                           when the image was built without a baked SBOM.
 *
 * Security:
 *   - The file path comes from trusted config (not request input) → no traversal.
 *   - `@PermitAll` because this endpoint is meant for the network-gated mgmt path.
 */
@Path("/q/openbank/sbom")
@ApplicationScoped
class SbomResource(
    // Optional<String> on purpose: a plain @ConfigProperty with no value would fail
    // @QuarkusTest boot with SRCFG00040. Defaulted, but kept Optional for safety.
    @ConfigProperty(name = "openbank.sbom.path", defaultValue = "/app/sbom/bom.json")
    private val sbomPath: Optional<String>,
) {

    @GET
    @PermitAll
    @Produces(MediaType.APPLICATION_JSON)
    fun sbom(): Response {
        val path = sbomPath.orElse(DEFAULT_PATH).trim()
        val file = Paths.get(path)
        if (path.isEmpty() || !Files.isRegularFile(file)) {
            return Response.status(Response.Status.NOT_FOUND)
                .type(MediaType.APPLICATION_JSON)
                .entity(mapOf("status" to "not_generated", "schema" to SCHEMA_VERSION))
                .build()
        }
        val bytes = Files.readAllBytes(file)
        return Response.ok(bytes, MediaType.APPLICATION_JSON)
            // inline (not attachment) so admin-ui can fetch + summarise; filename
            // lets a human "Save as" a sensibly-named CycloneDX document.
            .header("Content-Disposition", "inline; filename=\"bom.json\"")
            .header("Cache-Control", "public, max-age=60")
            .header("X-Sbom-Schema", SCHEMA_VERSION)
            .build()
    }

    private companion object {
        const val DEFAULT_PATH = "/app/sbom/bom.json"

        // Contract marker for the admin-ui consumer. The body itself is raw
        // CycloneDX (its own `bomFormat`/`specVersion` fields); this header just
        // declares which serving contract the endpoint speaks.
        const val SCHEMA_VERSION = "openbank.sbom.v1"
    }
}
