#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# SCA REST extension — SCA challenge lifecycle allow reasons (ADR-0034 Phase 5, issue #266)
SCA_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# Sca-service REST extension (ADR-0034 Phase 5, issue #266).
# Extends openbank.rest with SCA-domain allow reasons.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.
#
# Actions gated (ScaResource):
#   scaChallenge.initiate — initiate a challenge (POST /challenges)
#   scaChallenge.read     — get challenge by id
#   scaChallenge.verify   — OTP fallback verification (no in-repo M2M caller today)
#   scaChallenge.decide   — record device-signed approval/denial
#   scaChallenge.consume  — spend an approved challenge (ADR-0021 settlement gate)
#   device.enroll         — enrol a device credential (#partyId)
#   device.list           — list a party's device credentials (#partyId)
#
# Base rest.rego already grants: operator-read-any / compliance-read-any for
# *.read + *.list, party-self-service for device.list when the JWT sub equals
# the {partyId} path parameter, and edge-service-notification for SERVICE
# principals on the whole device.* family (device.enroll / device.list).

package openbank.rest

import rego.v1

# Operators and admins may perform ANY SCA challenge lifecycle operation — the ops
# console path (resolve a stuck challenge, service-desk credential reset per the
# ADR-0021 enroll-on-behalf note). device.* writes for operators ride on this too.
allowed_reasons contains "operator-sca-write" if {
	input.principal.type == "HUMAN"
	some role in {"ROLE_OPERATOR", "ROLE_ADMIN"}
	role in input.principal.roles
	some family in {"scaChallenge.", "device."}
	startswith(input.action, family)
}

# M2M callers in the SCA ceremony (both verified in-repo).
#
# NOTE (found post-merge, issue tracked separately): AuthorizeInterceptor never
# emits principal.type == "SERVICE" — M2M callers authenticate via Keycloak
# client_credentials JWTs, which the interceptor classifies as HUMAN. Gate on
# the verified client identity instead:
#   - customer-edge uses its own Keycloak client, identity
#     `service-account-openbank-edge` — initiate a challenge for the
#     authenticated customer, poll it (read), record the device decision, and
#     consume the approved challenge as the payment settlement gate (ADR-0021 —
#     scaGate runs before every money-path forward).
#   - consent-service shares the `openbank-services` client (like nearly every
#     other backend service), identity `service-account-openbank-services` —
#     reads a challenge to activate/reject a PENDING_SCA consent
#     (scaChallenge.read only). This identity is NOT unique to consent-service:
#     any other backend service using the shared client would also match this
#     rule for scaChallenge.read — documented limitation, not fixable without a
#     per-service client or audience claim.
# Deliberately narrow: scaChallenge.verify (the OTP fallback) has NO in-repo M2M
# caller and stays human-channel-only — a blanket allow would open every
# @Authorize endpoint to any M2M client (edge-service-notification's stance).
# device.enroll for the edge is already granted by edge-service-notification in
# base rest.rego — not duplicated here.
allowed_reasons contains "service-sca-edge-m2m" if {
	input.principal.type == "HUMAN"
	input.principal.id == "service-account-openbank-edge"
	input.action in {
		"scaChallenge.initiate",
		"scaChallenge.read",
		"scaChallenge.decide",
		"scaChallenge.consume",
	}
}

allowed_reasons contains "service-sca-shared-client-m2m" if {
	input.principal.type == "HUMAN"
	input.principal.id == "service-account-openbank-services"
	input.action == "scaChallenge.read"
}
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$SCA_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/sca/sca-opa-bundle.yaml

{
  echo "# GENERATED by gen-sca-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + sca_rest_ext.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: sca-opa-bundle"
  echo "  namespace: sca"
  echo "  labels:"
  echo "    app.kubernetes.io/name: sca-service"
  echo "    app.kubernetes.io/part-of: sca"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  sca_rest_ext.rego: |"
  echo "$SCA_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-customer-edge-opa-bundle.sh).
ROLLOUT=$REPO/openbank-infra/gitops/components/sca/sca-service.yaml
if [ -f "$ROLLOUT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$ROLLOUT"
  rm -f "${ROLLOUT}.bak"
  echo "patched $ROLLOUT annotation → $CHECKSUM"
fi
