#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# ADR registry integrity gate (ADR-0001 / ADR-0029 "governance as code").
#
# WHY THIS EXISTS (the defects it would have caught, all real, all 2026-06):
#
#   1. DUPLICATE NUMBERS. Three ADRs shared `0119` (ai-devops-agent / relicense /
#      oss-readiness), created by parallel agent sessions that each grabbed "the
#      next number" by hand against a stale local tree while origin/main had already
#      moved on (0120-0122 were taken). Nothing in CI checked uniqueness — so the
#      collision merged. (Fixed in PR #2414.)
#
#   2. OFF-BY-ONE TITLES. Hand-copied ADRs numbered five H1 headings one behind their
#      filename: `# 112.` inside `0113-*.md`, etc. (0113/0115/0116/0117/0118). The
#      filename is the source of truth; the heading silently disagreed.
#
#   3. STALE INDEX. `docs/adr/README.md` is generated by `docs/adr/gen-index.sh`.
#      A hand-edit or a forgotten re-run leaves the index disagreeing with the
#      ADRs it indexes — derived data that rots (CLAUDE.md rule #7).
#
# This gate makes all three impossible to merge. It is pure bash over the files in
# docs/adr/ — no Gradle, no Docker — so it runs in seconds on a docs-only PR. It is the
# BACKSTOP; the PREVENTION is `docs/adr/new.sh`, which allocates a collision-free number
# (local ∪ origin/main ∪ open PRs) and derives the H1 from it, so defects 1 & 2 are
# avoided at authoring time rather than caught at merge.
#
#   4. DANGLING REFERENCES. `ADR-0132` was cited in 3 code/config comments and 43
#      CHANGELOG entries before the file ever existed; `ADR-0128` was cited in two
#      gitops comments as a plain typo for `ADR-0037`. Neither was structurally
#      impossible (unlike defects 1/2/3 above), so nothing caught them until a
#      manual repo-wide audit did (2026-07-05, fixed in the same sweep that added
#      this check). Check 5 below makes the "reference points to a number with no
#      file" half of that defect class permanent going forward.
#
# NOT covered (be honest about the gap): a reference that points to a WRONG-but-
# EXISTING ADR number (e.g. 0121 citing `ADR-0119` when it meant the renamed
# oss-readiness ADR, now 0124). That target exists, so no generic check flags it;
# it needs a human/AI reviewer reading for intent. This gate is structural, not
# semantic. The same is true of dangling issue/PR references (e.g. `#1612`,
# `#638`) found in the same audit — those need a GitHub API call to verify, which
# this offline, no-network gate deliberately does not make.
#
# Exit: 0 = clean, 1 = at least one violation (always enforcing — the fleet is
# clean as of PR #2414, so there is no sweep to grandfather).
# -----------------------------------------------------------------------------
set -euo pipefail

ADR_DIR="${1:-docs/adr}"
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

if [[ ! -d "$ADR_DIR" ]]; then
  echo "::error::check-adr-registry: ADR directory '$ADR_DIR' not found." >&2
  exit 1
fi

fail=0
err() { echo "::error title=ADR registry::$*" >&2; fail=1; }

shopt -s nullglob
adrs=("$ADR_DIR"/[0-9]*.md)
if [[ ${#adrs[@]} -eq 0 ]]; then
  echo "::error::check-adr-registry: no numbered ADRs found in '$ADR_DIR'." >&2
  exit 1
fi

# --- 1. Unique numbers -------------------------------------------------------
# Collect the NNNN prefix of every ADR; any number appearing >1 is a collision.
dupes=$(
  for f in "${adrs[@]}"; do
    base=$(basename "$f")
    echo "${base%%-*}"
  done | sort | uniq -d
)
if [[ -n "$dupes" ]]; then
  while IFS= read -r num; do
    files=$(ls "$ADR_DIR/$num"-*.md 2>/dev/null | xargs -n1 basename | paste -sd', ' -)
    err "duplicate ADR number $num shared by: $files — renumber all but one to the next free number."
  done <<< "$dupes"
fi

# --- 2. H1 heading number must match the filename ----------------------------
# Only check when the H1 carries a number in a recognised position:
#   "# ADR-0113 — Title"  or  "# 113. Title"  (also "# 0113 — ...").
# A bare title ("# OSS-readiness ...") or an incidental number ("# PostgreSQL 18
# — ...") has no anchored ADR number, so it is skipped (no false positive).
for f in "${adrs[@]}"; do
  base=$(basename "$f")
  fnum=$((10#${base%%-*}))
  h1=$(grep -m1 '^# ' "$f" || true)
  hnum=""
  if [[ "$h1" =~ ^\#[[:space:]]+ADR-0*([0-9]+) ]]; then
    hnum="${BASH_REMATCH[1]}"
  elif [[ "$h1" =~ ^\#[[:space:]]+0*([0-9]+)\. ]]; then
    hnum="${BASH_REMATCH[1]}"
  fi
  if [[ -n "$hnum" && "$((10#$hnum))" -ne "$fnum" ]]; then
    err "$base: H1 says number $hnum but filename is $(printf '%04d' "$fnum") — the filename is the source of truth. Fix the heading."
  fi
done

# --- 3. Generated index must be up to date -----------------------------------
# Regenerate in place and fail if it changed git-tracked content. The generator
# is deterministic, so a clean tree => no diff.
if [[ -x "$ADR_DIR/gen-index.sh" || -f "$ADR_DIR/gen-index.sh" ]]; then
  bash "$ADR_DIR/gen-index.sh" >/dev/null
  for derived in README.md DIGEST.md index.json; do
    if ! git diff --quiet -- "$ADR_DIR/$derived" 2>/dev/null; then
      err "docs/adr/$derived is stale — run 'bash $ADR_DIR/gen-index.sh' and commit the result."
      echo "----- $derived drift (committed vs regenerated) -----" >&2
      git --no-pager diff -- "$ADR_DIR/$derived" >&2 || true
      git checkout -- "$ADR_DIR/$derived" 2>/dev/null || true
    fi
  done
else
  echo "::warning::check-adr-registry: $ADR_DIR/gen-index.sh missing — skipping index freshness check." >&2
fi

# --- 4. Front-matter schema (docs/adr/SCHEMA.md) ------------------------------
# The header used to be prose, in four coexisting conventions, so every consumer
# needed its own fallback regex and the index truncated statuses to 40 chars to
# cope. Now it is one machine-readable block, parsed by the one shared parser, and
# validated here. Everything below is a structural check on that block.
# shellcheck source=../../docs/adr/lib-frontmatter.sh
. "$ADR_DIR/lib-frontmatter.sh"

KNOWN_REPOS="$ADR_DIR/known-repos.txt"
TAGS_FILE="$ADR_DIR/tags.txt"
SCHEMA_KEYS="date decision-status delivery-status authors supersedes superseded-by delivery-repos tags summary"
DECISION_ENUM="proposed accepted superseded deprecated rejected"
DELIVERY_ENUM="planned partial shipped n-a"
SUMMARY_MAX=240

in_set() { case " $2 " in *" $1 "*) return 0 ;; *) return 1 ;; esac; }

allowed_tags=""
if [[ -f "$TAGS_FILE" ]]; then
  allowed_tags=$(grep -vE '^\s*(#|$)' "$TAGS_FILE" | tr '\n' ' ')
else
  echo "::warning::check-adr-registry: $TAGS_FILE missing — skipping tag allowlist check." >&2
fi
allowed_repos=""
if [[ -f "$KNOWN_REPOS" ]]; then
  allowed_repos=$(grep -vE '^\s*(#|$)' "$KNOWN_REPOS" | tr '\n' ' ')
else
  echo "::warning::check-adr-registry: $KNOWN_REPOS missing — skipping Delivery-Repos allowlist check." >&2
fi

# Collected for check 4h (bidirectional supersession) after the per-file pass.
declared_supby=""   # "NNNN>TTTT" pairs: NNNN declares it is superseded by TTTT
declared_sup=""     # "NNNN>TTTT" pairs: NNNN declares it supersedes TTTT

for f in "${adrs[@]}"; do
  base=$(basename "$f")
  num=${base%%-*}

  # Capture fm_extract's OWN status. `if ! fm=$(...); then case "$?"` cannot: inside
  # the branch `$?` is the status of the negated condition, i.e. always 0, so every
  # parse failure fell through to the generic `*` arm and the 3-vs-4 distinction the
  # library goes to the trouble of returning was thrown away.
  fm=""
  fm_rc=0
  fm=$(fm_extract "$f" 2>/dev/null) || fm_rc=$?
  if (( fm_rc != 0 )); then
    case "$fm_rc" in
      3) err "$base: no YAML front-matter block — the file must start with '---'. See docs/adr/SCHEMA.md." ;;
      4) err "$base: front-matter block is never closed by a '---' line. See docs/adr/SCHEMA.md." ;;
      *) err "$base: front-matter could not be READ (fm_extract exited $fm_rc) — this is a tool failure, not a schema violation." ;;
    esac
    continue
  fi

  # 4a. malformed lines (nesting, block scalars, stray text) --------------------
  while IFS=$'\t' read -r k v; do
    [[ "$k" == "!malformed" ]] && err "$base: front-matter line is not a flat 'key: value': $v"
  done <<< "$fm"

  # 4b. every required key present; no unknown keys ----------------------------
  # An unknown key is almost always a typo'd required one, which would otherwise
  # read as "field simply absent" and be silently defaulted by every consumer.
  # A read failure and an absent key are DIFFERENT verdicts and must print
  # differently: "missing required key 'authors'" names a file and a field and reads
  # as a genuine finding, so emitting it for a tool failure gets a correct ADR
  # "fixed" or gets the whole gate ignored. See lib-frontmatter.sh's
  # NEVER PIPE INTO AN EARLY-EXIT CONSUMER note for how that shipped once already.
  for k in $SCHEMA_KEYS; do
    fm_has "$fm" "$k" && continue
    key_rc=$?
    if (( key_rc > 1 )); then
      err "$base: front-matter READ FAILED while checking key '$k' (fm_has exited $key_rc) — the key was NOT determined to be missing."
    else
      err "$base: front-matter is missing required key '$k'."
    fi
  done
  while IFS=$'\t' read -r k v; do
    [[ -z "$k" || "$k" == "!malformed" ]] && continue
    in_set "$k" "$SCHEMA_KEYS" || err "$base: unknown front-matter key '$k' (typo? see docs/adr/SCHEMA.md)."
  done <<< "$fm"

  decision=$(fm_field "$fm" decision-status)
  delivery=$(fm_field "$fm" delivery-status)
  date=$(fm_field "$fm" date)
  summary_raw=$(fm_field "$fm" summary)

  # 4c. enums and date format ---------------------------------------------------
  in_set "$decision" "$DECISION_ENUM" || err "$base: decision-status '$decision' is not one of: $DECISION_ENUM"
  in_set "$delivery" "$DELIVERY_ENUM" || err "$base: delivery-status '$delivery' is not one of: $DELIVERY_ENUM"
  [[ "$date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] || err "$base: date '$date' is not YYYY-MM-DD."

  # 4d. summary -- the field DIGEST.md is built from, so it is worth policing ---
  if [[ "$summary_raw" != \"*\" ]]; then
    err "$base: summary must be a double-quoted single-line string (see docs/adr/SCHEMA.md)."
  else
    summary=$(fm_unquote "$summary_raw")
    if [[ ${#summary} -gt $SUMMARY_MAX ]]; then
      err "$base: summary is ${#summary} chars, max $SUMMARY_MAX."
    fi
    if [[ ${#summary} -lt 20 ]]; then
      err "$base: summary is ${#summary} chars — too short to be a real decision statement."
    fi
  fi

  # 4e. authors non-empty ------------------------------------------------------
  [[ -n "$(fm_list "$(fm_field "$fm" authors)")" ]] || err "$base: authors is empty."

  # 4f. closed vocabularies ----------------------------------------------------
  tag_count=0
  while IFS= read -r t; do
    [[ -z "$t" ]] && continue
    tag_count=$((tag_count + 1))
    if [[ -n "$allowed_tags" ]] && ! in_set "$t" "$allowed_tags"; then
      err "$base: tag '$t' is not in $TAGS_FILE — add it there in this PR, or pick an existing tag."
    fi
  done <<< "$(fm_list "$(fm_field "$fm" tags)")"
  if [[ $tag_count -lt 1 || $tag_count -gt 4 ]]; then
    err "$base: has $tag_count tags — the schema allows 1 to 4."
  fi
  while IFS= read -r r; do
    [[ -z "$r" ]] && continue
    if [[ -n "$allowed_repos" ]] && ! in_set "$r" "$allowed_repos"; then
      err "$base: delivery-repos names '$r', which is not in $KNOWN_REPOS — add it there first (or fix the typo)."
    fi
  done <<< "$(fm_list "$(fm_field "$fm" delivery-repos)")"

  # 4g. supersession is internally consistent ----------------------------------
  supby=$(fm_list "$(fm_field "$fm" superseded-by)")
  sup=$(fm_list "$(fm_field "$fm" supersedes)")
  if [[ -n "$supby" && "$decision" != "superseded" ]]; then
    err "$base: superseded-by is set but decision-status is '$decision' — it must be 'superseded'."
  fi
  if [[ -z "$supby" && "$decision" == "superseded" ]]; then
    err "$base: decision-status is 'superseded' but superseded-by is empty — name the ADR that replaced it."
  fi
  while IFS= read -r t; do
    [[ -z "$t" ]] && continue
    [[ "$t" == "$num" ]] && err "$base: superseded-by lists itself."
    ls "$ADR_DIR/$t"-*.md >/dev/null 2>&1 || err "$base: superseded-by names ADR-$t, which has no file."
    declared_supby="$declared_supby $num>$t"
  done <<< "$supby"
  while IFS= read -r t; do
    [[ -z "$t" ]] && continue
    [[ "$t" == "$num" ]] && err "$base: supersedes lists itself."
    ls "$ADR_DIR/$t"-*.md >/dev/null 2>&1 || err "$base: supersedes names ADR-$t, which has no file."
    declared_sup="$declared_sup $num>$t"
  done <<< "$sup"

  # 4j. an unfilled scaffold must not merge -------------------------------------
  # The gate checked that a section EXISTS, not that anyone wrote it. So a
  # `docs/adr/new.sh` scaffold with its tag corrected but its `summary:` left as the
  # TODO placeholder passed cleanly — and `summary` is the one field the whole
  # DIGEST.md tier rests on, so the placeholder would have been published as this
  # ADR's entry in the decision history. Same for the TEMPLATE.md body prompts.
  # These markers exist only in the scaffolding, so they cannot false-positive.
  while IFS= read -r marker; do
    [[ -z "$marker" ]] && continue
    if grep -qF -- "$marker" "$f"; then
      err "$base: still contains the unfilled scaffold placeholder \"$marker\" — write the ADR before merging it."
    fi
  done <<'MARKERS'
TODO-pick-from-tags.txt
summary: "TODO
authors: [<name>]
<Short noun phrase>
<req refs>
What forces are at play (technical, business, regulatory)?
State the decision clearly in active voice
- **Option A** — short description
MARKERS

  # 4i. required body sections -------------------------------------------------
  # Hard-required, EXCEPT on superseded ADRs: those are immutable historical
  # records (ADR-0001) and some are a pointer to their successor and nothing else
  # — retro-fitting sections into them would be rewriting history, not fixing it.
  if [[ "$decision" != "superseded" ]]; then
    grep -q '^## Context' "$f"                        || err "$base: missing a '## Context' section."
    grep -qiE '^## (The )?Decision' "$f"              || err "$base: missing a '## Decision' section."
    grep -q '^## Consequences' "$f"                   || err "$base: missing a '## Consequences' section."
    # GRADUATED to blocking (ADR-0144 gate-graduation). These were advisory while 32
    # and 42 pre-schema ADRs respectively lacked them; that backlog is now closed, so
    # the rule enforces instead of nagging — an advisory rule nobody can ever act on
    # is just noise, and a rule with no remaining violations is free to enforce.
    #
    # On writing them: reconstruct, do not invent. An ADR whose alternatives were
    # never recorded should say so explicitly rather than manufacture a plausible
    # rejected option, and a compliance row must not carry an article or requirement
    # number that does not appear in the ADR's own text. A confident fabrication in
    # this directory is read by auditors as a claim about the platform.
    grep -q '^## Alternatives' "$f" || err "$base: missing a '## Alternatives considered' section (see TEMPLATE.md; if none was recorded, say so explicitly)."
    grep -q '^## Compliance'   "$f" || err "$base: missing a '## Compliance impact' section (see TEMPLATE.md; 'not applicable — <reason>' is a valid and common answer)."
  fi
done

# 4h. supersession must be BIDIRECTIONAL -------------------------------------
# The defect this prevents: ADR-A says "superseded by B" and B says nothing, so a
# reader who opens B has no way to learn it replaced A. Seven such forward links
# existed with no enforced back-link before this check.
for pair in $declared_supby; do
  a=${pair%%>*}; b=${pair##*>}
  case " $declared_sup " in
    *" $b>$a "*) ;;
    *) err "ADR-$a declares superseded-by ADR-$b, but ADR-$b does not declare supersedes: [$a] — supersession must be recorded on both sides." ;;
  esac
done
for pair in $declared_sup; do
  a=${pair%%>*}; b=${pair##*>}
  case " $declared_supby " in
    *" $b>$a "*) ;;
    *) err "ADR-$a declares supersedes ADR-$b, but ADR-$b does not declare superseded-by: [$a] — supersession must be recorded on both sides." ;;
  esac
done


# --- 5. Dangling ADR-NNNN references repo-wide -------------------------------
# Every "ADR-NNNN" mention outside docs/adr/ (code comments, gitops YAML, other
# governance docs) must resolve to an actual docs/adr/NNNN-*.md file. Catches the
# ADR-0132/ADR-0128 defect class (see WHY THIS EXISTS #4) mechanically instead of
# relying on the next manual audit to find it. Deliberately repo-wide, not just
# docs/adr/, since that's exactly where both real-world instances were found.
#
# Set membership via `comm`, NOT a nested loop. The obvious shape — for each reference,
# walk the list of ADR numbers — is O(references x ADRs), and this repo has 20 636
# references against 226 ADRs: ~4.7M bash iterations, measured at 71 s of CPU and the
# single largest cost in the whole gate job. `git grep` itself takes 1.2 s; all of the
# rest was this loop.
#
# NOT an associative array (`declare -A`), which is the reflex fix and is WRONG here:
# macOS ships bash 3.2, where `declare -A` fails with "invalid option" and the assignment
# silently degrades to a sparse INDEXED array. That happens to give the right answer for
# these particular keys, so it would have looked fixed and measured fast while resting on
# an error message — and this script runs on the mixed macOS/Linux pool. `comm` is POSIX.
#
# Plain string comparison is sound because both sides are exactly four digits by
# construction: the reference regex is `ADR-[0-9]{4}` and every filename prefix in
# docs/adr/ is 4-digit (asserted below, so a 5-digit ADR-10000 does not silently make
# every reference look dangling).
_adr_tmp=$(mktemp -d)
trap 'rm -rf "$_adr_tmp"' EXIT

for f in "${adrs[@]}"; do
  basename "$f"
done | sed -E 's/^([0-9]+)-.*/\1/' | sort -u > "$_adr_tmp/existing"

if grep -qvE '^[0-9]{4}$' "$_adr_tmp/existing"; then
  err "docs/adr/ contains an ADR whose number is not 4 digits — check 5 compares reference numbers to filename numbers as fixed-width strings and would mis-report. Renumber it, or widen both sides together."
fi

# Exclude docs/adr/* (self-references are already covered by checks 1-4 above) and this
# script itself (its own comments cite ADR-0128/ADR-0132 as worked examples of the defect
# class this check exists to catch — not real dangling references). Emitted as num:file so
# the number is sortable in field 1.
git grep -InoE 'ADR-[0-9]{4}' -- ':!docs/adr/*' ':!.github/scripts/check-adr-registry.sh' 2>/dev/null \
  | sed -E 's/^([^:]+):[0-9]+:ADR-([0-9]{4})$/\2:\1/' | sort -u > "$_adr_tmp/refs"

# Dangling = referenced numbers minus existing numbers. Report every citing file for
# each, so the error names where to go, exactly as the per-reference loop did.
cut -d: -f1 "$_adr_tmp/refs" | sort -u | comm -23 - "$_adr_tmp/existing" > "$_adr_tmp/dangling"
while IFS= read -r num; do
  [[ -z "$num" ]] && continue
  while IFS=: read -r _ file; do
    err "$file: references ADR-$num, which has no docs/adr/$num-*.md file — fix the reference or write the ADR."
  done < <(grep "^${num}:" "$_adr_tmp/refs")
done < "$_adr_tmp/dangling"


if [[ "$fail" -ne 0 ]]; then
  echo "::error::check-adr-registry: ADR registry has integrity violations (see above)." >&2
  exit 1
fi
echo "check-adr-registry: OK — ${#adrs[@]} ADRs: unique numbers, headings match filenames, front-matter valid, supersession bidirectional, derived artefacts fresh."
