#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# ADR registry integrity gate (ADR-0001 / ADR-0029 "governance as code").
#
# WHY THIS EXISTS (the defects it would have caught, all real, all 2026-06):
#
#   1. DUPLICATE NUMBERS. Three ADRs shared `0119` (ai-devops-agent / relicense /
#      oss-readiness), created by parallel agent sessions that each grabbed "the
#      next number" by hand against a stale local tree while origin/main had already
#      moved on (0120-0122 were taken). Nothing in CI checked uniqueness — so the
#      collision merged. (Fixed in PR #2414.)
#
#   2. OFF-BY-ONE TITLES. Hand-copied ADRs numbered five H1 headings one behind their
#      filename: `# 112.` inside `0113-*.md`, etc. (0113/0115/0116/0117/0118). The
#      filename is the source of truth; the heading silently disagreed.
#
#   3. STALE INDEX. `docs/adr/README.md` is generated by `docs/adr/gen-index.sh`.
#      A hand-edit or a forgotten re-run leaves the index disagreeing with the
#      ADRs it indexes — derived data that rots (CLAUDE.md rule #7).
#
# This gate makes all three impossible to merge. It is pure bash over the files in
# docs/adr/ — no Gradle, no Docker — so it runs in seconds on a docs-only PR. It is the
# BACKSTOP; the PREVENTION is `docs/adr/new.sh`, which allocates a collision-free number
# (local ∪ origin/main ∪ open PRs) and derives the H1 from it, so defects 1 & 2 are
# avoided at authoring time rather than caught at merge.
#
#   4. DANGLING REFERENCES. `ADR-0132` was cited in 3 code/config comments and 43
#      CHANGELOG entries before the file ever existed; `ADR-0128` was cited in two
#      gitops comments as a plain typo for `ADR-0037`. Neither was structurally
#      impossible (unlike defects 1/2/3 above), so nothing caught them until a
#      manual repo-wide audit did (2026-07-05, fixed in the same sweep that added
#      this check). Check 5 below makes the "reference points to a number with no
#      file" half of that defect class permanent going forward.
#
# NOT covered (be honest about the gap): a reference that points to a WRONG-but-
# EXISTING ADR number (e.g. 0121 citing `ADR-0119` when it meant the renamed
# oss-readiness ADR, now 0124). That target exists, so no generic check flags it;
# it needs a human/AI reviewer reading for intent. This gate is structural, not
# semantic. The same is true of dangling issue/PR references (e.g. `#1612`,
# `#638`) found in the same audit — those need a GitHub API call to verify, which
# this offline, no-network gate deliberately does not make.
#
# Exit: 0 = clean, 1 = at least one violation (always enforcing — the fleet is
# clean as of PR #2414, so there is no sweep to grandfather).
# -----------------------------------------------------------------------------
set -euo pipefail

ADR_DIR="${1:-docs/adr}"
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

if [[ ! -d "$ADR_DIR" ]]; then
  echo "::error::check-adr-registry: ADR directory '$ADR_DIR' not found." >&2
  exit 1
fi

fail=0
err() { echo "::error title=ADR registry::$*" >&2; fail=1; }

shopt -s nullglob
adrs=("$ADR_DIR"/[0-9]*.md)
if [[ ${#adrs[@]} -eq 0 ]]; then
  echo "::error::check-adr-registry: no numbered ADRs found in '$ADR_DIR'." >&2
  exit 1
fi

# --- 1. Unique numbers -------------------------------------------------------
# Collect the NNNN prefix of every ADR; any number appearing >1 is a collision.
dupes=$(
  for f in "${adrs[@]}"; do
    base=$(basename "$f")
    echo "${base%%-*}"
  done | sort | uniq -d
)
if [[ -n "$dupes" ]]; then
  while IFS= read -r num; do
    files=$(ls "$ADR_DIR/$num"-*.md 2>/dev/null | xargs -n1 basename | paste -sd', ' -)
    err "duplicate ADR number $num shared by: $files — renumber all but one to the next free number."
  done <<< "$dupes"
fi

# --- 2. H1 heading number must match the filename ----------------------------
# Only check when the H1 carries a number in a recognised position:
#   "# ADR-0113 — Title"  or  "# 113. Title"  (also "# 0113 — ...").
# A bare title ("# OSS-readiness ...") or an incidental number ("# PostgreSQL 18
# — ...") has no anchored ADR number, so it is skipped (no false positive).
for f in "${adrs[@]}"; do
  base=$(basename "$f")
  fnum=$((10#${base%%-*}))
  h1=$(grep -m1 '^# ' "$f" || true)
  hnum=""
  if [[ "$h1" =~ ^\#[[:space:]]+ADR-0*([0-9]+) ]]; then
    hnum="${BASH_REMATCH[1]}"
  elif [[ "$h1" =~ ^\#[[:space:]]+0*([0-9]+)\. ]]; then
    hnum="${BASH_REMATCH[1]}"
  fi
  if [[ -n "$hnum" && "$((10#$hnum))" -ne "$fnum" ]]; then
    err "$base: H1 says number $hnum but filename is $(printf '%04d' "$fnum") — the filename is the source of truth. Fix the heading."
  fi
done

# --- 3. Generated index must be up to date -----------------------------------
# Regenerate in place and fail if it changed git-tracked content. The generator
# is deterministic, so a clean tree => no diff.
if [[ -x "$ADR_DIR/gen-index.sh" || -f "$ADR_DIR/gen-index.sh" ]]; then
  bash "$ADR_DIR/gen-index.sh" >/dev/null
  if ! git diff --quiet -- "$ADR_DIR/README.md" 2>/dev/null; then
    err "docs/adr/README.md is stale — run 'bash $ADR_DIR/gen-index.sh' and commit the result."
    echo "----- index drift (committed vs regenerated) -----" >&2
    git --no-pager diff -- "$ADR_DIR/README.md" >&2 || true
    git checkout -- "$ADR_DIR/README.md" 2>/dev/null || true
  fi
else
  echo "::warning::check-adr-registry: $ADR_DIR/gen-index.sh missing — skipping index freshness check." >&2
fi

# --- 4. Delivery-Repos values must be in the known-repos allowlist (ADR-0147) ---
# Catches a typo'd repo name at authoring time; does NOT verify the target repo's
# actual state (out of scope — see known-repos.txt).
KNOWN_REPOS="$ADR_DIR/known-repos.txt"
if [[ -f "$KNOWN_REPOS" ]]; then
  for f in "${adrs[@]}"; do
    base=$(basename "$f")
    line=$(grep -m1 -E '^Delivery-Repos:' "$f" || true)
    [[ -z "$line" ]] && continue
    repos_raw="${line#Delivery-Repos:}"
    IFS=',' read -ra repo_list <<< "$repos_raw"
    for repo in "${repo_list[@]}"; do
      repo="$(echo "$repo" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
      [[ -z "$repo" ]] && continue
      if ! grep -qxF "$repo" "$KNOWN_REPOS"; then
        err "$base: Delivery-Repos names '$repo', which is not in $KNOWN_REPOS — add it there first (or fix the typo)."
      fi
    done
  done
else
  echo "::warning::check-adr-registry: $KNOWN_REPOS missing — skipping Delivery-Repos allowlist check." >&2
fi

# --- 5. Dangling ADR-NNNN references repo-wide -------------------------------
# Every "ADR-NNNN" mention outside docs/adr/ (code comments, gitops YAML, other
# governance docs) must resolve to an actual docs/adr/NNNN-*.md file. Catches the
# ADR-0132/ADR-0128 defect class (see WHY THIS EXISTS #4) mechanically instead of
# relying on the next manual audit to find it. Deliberately repo-wide, not just
# docs/adr/, since that's exactly where both real-world instances were found.
existing_numbers=$(
  for f in "${adrs[@]}"; do
    basename "$f" | sed -E 's/^([0-9]+)-.*/\1/'
  done
)
while IFS=: read -r file num; do
  [[ -z "$num" ]] && continue
  n10=$((10#$num))
  found=0
  while IFS= read -r existing; do
    [[ "$((10#$existing))" -eq "$n10" ]] && { found=1; break; }
  done <<< "$existing_numbers"
  if [[ "$found" -eq 0 ]]; then
    err "$file: references ADR-$num, which has no docs/adr/$num-*.md file — fix the reference or write the ADR."
  fi
done < <(
  # Exclude docs/adr/* (self-references already covered by checks 1-4 above) and
  # this script itself (its own comments cite ADR-0128/ADR-0132 as worked examples
  # of the defect class this check exists to catch — not real dangling references).
  git grep -InoE 'ADR-[0-9]{4}' -- ':!docs/adr/*' ':!.github/scripts/check-adr-registry.sh' 2>/dev/null \
    | sed -E 's/^([^:]+):[0-9]+:ADR-([0-9]{4})$/\1:\2/'
)

if [[ "$fail" -ne 0 ]]; then
  echo "::error::check-adr-registry: ADR registry has integrity violations (see above)." >&2
  exit 1
fi
echo "check-adr-registry: OK — ${#adrs[@]} ADRs, unique numbers, headings match filenames, index fresh."
