#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
"""Every outbound REST call from a money-path service to an in-repo provider has a committed pact.

WHY THIS EXISTS (issue #8345, acceptance criterion 4)
-----------------------------------------------------
`check-pact-provider-replay.py` guarantees every COMMITTED pact is replayed before merge, and
`derive-pact-drift-scope.sh` guarantees every committed pact is regenerated by a discovered test.
Neither can see a money-path call that has NO pact at all: the (consumer, provider) pair simply
never appears in `pacts/`. Measured 2026-09-30: 58 outbound `@RegisterRestClient`s across the
money-path services, 26 of them with no contract — including every rail's sanctions, fraud and
AML call. That gap was found by hand and would have been found by hand again.

THE DENOMINATOR IS DERIVED, NEVER LISTED
----------------------------------------
For every service in `rules.yaml: money_path_services`, every `@RegisterRestClient(configKey =
"<key>")` interface under `src/main` names a provider. The key resolves to a module directory:
`openbank-<key>` when that directory exists, otherwise through KEY_ALIASES (the few keys whose
name is not the module name), otherwise EXTERNAL (a provider outside this repo, which Pact cannot
verify). A key that resolves nowhere is itself a finding: a renamed module or a new client cannot
quietly leave the checked set.

A pair is covered when `pacts/<consumer>-<provider>.json` exists and names that provider. The
pairs uncovered today are carried in `money-path-pact-coverage-baseline.txt` (shrink-only, one
`# reason` per entry): a NEW uncovered pair fails the gate, and a baselined pair that gains a pact
fails too, so the list can only shrink and an exception cannot outlive its reason.

Usage: check-money-path-pact-coverage.py [--root .] [--print-baseline] [--self-test]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gatelib  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
BASELINE = Path(__file__).resolve().with_name("money-path-pact-coverage-baseline.txt")

# configKeys whose name is not `openbank-<key>`. Kept small on purpose: a new alias needs a line
# here, which is the reviewable moment.
KEY_ALIASES = {
    "balance-api": "openbank-balance-service",
    "ledger-api": "openbank-ledger-service",
    "sepa-payment-service": "openbank-sepa-payment",
    "product-catalog-api": "openbank-product-catalog",
    "tpp-registry": "openbank-tpp-registry-service",
    "card-issuance-api": "openbank-card-issuance-service",
    "fraud-api": "openbank-fraud-service",
    "transaction-api": "openbank-transaction-service",
    "context-lending-access": "openbank-context-service",
    "lending-graph-party-proof": "openbank-party-service",
    "lending-graph-document-proof": "openbank-document-service",
}

# Providers outside this repository. A pact against them would verify nothing here.
# Card-scheme sandboxes (Visa, Mastercard) are vendor APIs reached by card-processing (ADR-0283).
EXTERNAL_KEYS = {"cnb-feed", "mastercard-api", "visa-api"}

CONFIG_KEY = re.compile(r'@RegisterRestClient\s*\([^)]*configKey\s*=\s*"([a-z0-9-]+)"')


def money_path_services(root: Path) -> list[str]:
    rules = gatelib.load_yaml(root / "openbank-libs/governance/rules.yaml")
    return list(rules.get("money_path_services") or [])


def resolve(key: str, modules: set[str]) -> str | None:
    """Provider module for a configKey, or None when it is external or unresolvable."""
    if key in KEY_ALIASES:
        return KEY_ALIASES[key]
    candidate = f"openbank-{key}"
    return candidate if candidate in modules else None


def audit(root: Path) -> tuple[list[tuple[str, str, str]], list[str], int]:
    """Returns (uncovered pairs as (consumer, provider, client file), errors, subjects)."""
    modules = {p.name for p in root.iterdir() if p.is_dir() and (p / "build.gradle.kts").exists()}
    pact_dir = root / "pacts"
    committed: set[tuple[str, str]] = set()
    for pact in sorted(pact_dir.glob("*.json")) if pact_dir.is_dir() else []:
        try:
            doc = json.loads(gatelib.read_text(pact))
        except (OSError, ValueError):
            continue
        consumer = ((doc.get("consumer") or {}).get("name") or "").strip()
        provider = ((doc.get("provider") or {}).get("name") or "").strip()
        if consumer and provider:
            committed.add((consumer, provider))

    uncovered: list[tuple[str, str, str]] = []
    errors: list[str] = []
    subjects = 0
    for consumer in money_path_services(root):
        for kt in gatelib.rglob(root / consumer / "src" / "main", "*.kt"):
            text = gatelib.read_text(kt, errors="replace")
            for key in CONFIG_KEY.findall(text):
                if key in EXTERNAL_KEYS:
                    continue
                provider = resolve(key, modules)
                rel = kt.relative_to(root).as_posix()
                if provider is None:
                    errors.append(
                        f"{rel}: configKey \"{key}\" resolves to no module directory — add the module, "
                        f"an entry in KEY_ALIASES, or EXTERNAL_KEYS if it lives outside this repo",
                    )
                    continue
                if provider == consumer:
                    continue
                subjects += 1
                if (consumer, provider) not in committed:
                    uncovered.append((consumer, provider, rel))
    return uncovered, errors, subjects


def load_baseline(path: Path = BASELINE) -> dict[str, str]:
    entries: dict[str, str] = {}
    if not path.exists():
        return entries
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, reason = line.partition("#")
        entries[key.strip()] = reason.strip()
    return entries


def pair_key(consumer: str, provider: str) -> str:
    return f"{consumer} -> {provider}"


def report(uncovered, errors, subjects, baseline: dict[str, str]) -> int:
    gatelib.subjects(subjects, "money-path outbound REST clients targeting an in-repo provider")
    observed = {pair_key(c, p) for c, p, _ in uncovered}
    new = [(c, p, f) for c, p, f in uncovered if pair_key(c, p) not in baseline]
    stale = [k for k in baseline if k not in observed]
    rc = 0
    for e in errors:
        print(f"::error::{e}", file=sys.stderr)
        rc = 1
    if new:
        print("\nMoney-path calls with NO consumer pact:\n", file=sys.stderr)
        for c, p, f in new:
            print(f"::error::{pair_key(c, p)}  [{f}]", file=sys.stderr)
        print(
            f"\n{len(new)} new uncovered pair(s). Add a consumer pact (and confirm the provider's "
            f"@PactFolder replay runs), or record a reasoned exception in "
            f"money-path-pact-coverage-baseline.txt.",
            file=sys.stderr,
        )
        rc = 1
    if stale:
        print("\nStale baseline entries (the pair now has a pact — remove them):", file=sys.stderr)
        for s in stale:
            print(f"::error::{s}", file=sys.stderr)
        rc = 1
    if rc == 0:
        print(
            f"OK: {subjects - len(uncovered)}/{subjects} money-path outbound calls carry a consumer pact; "
            f"{len(baseline)} baselined exception(s), none stale.",
        )
    return rc


def self_test() -> int:
    """Prove the gate can fail: a known-uncovered pair, a stale entry, an unresolvable key, a covered control."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "openbank-libs/governance").mkdir(parents=True)
        (root / "openbank-libs/governance/rules.yaml").write_text(
            "money_path_services:\n  - openbank-alpha-service\n  - openbank-beta-service\n",
        )
        for m in ("openbank-alpha-service", "openbank-beta-service", "openbank-gamma-service", "openbank-balance-service"):
            (root / m / "src/main/kotlin").mkdir(parents=True)
            (root / m / "build.gradle.kts").write_text("")
        (root / "openbank-alpha-service/src/main/kotlin/A.kt").write_text(
            '@RegisterRestClient(configKey = "gamma-service")\ninterface G\n'
            '@RegisterRestClient(configKey = "balance-api")\ninterface B\n'
            '@RegisterRestClient(configKey = "cnb-feed")\ninterface C\n',
        )
        (root / "openbank-beta-service/src/main/kotlin/B.kt").write_text(
            '@RegisterRestClient(configKey = "nowhere-service")\ninterface N\n',
        )
        (root / "pacts").mkdir()
        (root / "pacts/openbank-alpha-service-openbank-gamma-service.json").write_text(
            json.dumps({"consumer": {"name": "openbank-alpha-service"}, "provider": {"name": "openbank-gamma-service"}}),
        )
        uncovered, errors, subjects = audit(root)
        pairs = {pair_key(c, p) for c, p, _ in uncovered}
        checks = {
            "covered control (alpha->gamma) is not reported": pair_key("openbank-alpha-service", "openbank-gamma-service") not in pairs,
            "aliased uncovered pair (alpha->balance via balance-api) IS reported": pair_key("openbank-alpha-service", "openbank-balance-service") in pairs,
            "external key (cnb-feed) is skipped, not reported": all("cnb" not in p for p in pairs),
            "unresolvable key is an error": any("nowhere-service" in e for e in errors),
            "subjects count the two resolvable in-repo pairs": subjects == 2,
        }
        # Baseline semantics: the aliased pair baselined => clean; a baselined pair that is covered => stale.
        baseline = {pair_key("openbank-alpha-service", "openbank-balance-service"): "reason"}
        rc_clean = report(uncovered, [], subjects, baseline)
        checks["baselined uncovered pair passes"] = rc_clean == 0
        stale_baseline = {pair_key("openbank-alpha-service", "openbank-gamma-service"): "reason",
                          pair_key("openbank-alpha-service", "openbank-balance-service"): "reason"}
        checks["a baselined pair that gained a pact is stale => fails"] = report(uncovered, [], subjects, stale_baseline) == 1
        checks["an unbaselined uncovered pair fails"] = report(uncovered, [], subjects, {}) == 1
    failed = [k for k, ok in checks.items() if not ok]
    for k, ok in checks.items():
        print(f"{'ok  ' if ok else 'FAIL'} {k}")
    return 1 if failed else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=str(REPO))
    ap.add_argument("--print-baseline", action="store_true", help="emit today's uncovered pairs in baseline format")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    uncovered, errors, subjects = audit(Path(args.root))
    if args.print_baseline:
        # Errors still go to stderr: a baseline printed over an unresolvable key would hide it.
        for e in errors:
            print(f"::error::{e}", file=sys.stderr)
        for c, p, f in sorted(uncovered):
            print(f"{pair_key(c, p)}  # {f} — no consumer pact yet (#8345)")
        return 1 if errors else 0
    return report(uncovered, errors, subjects, load_baseline())


if __name__ == "__main__":
    sys.exit(main())
