#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
"""Generate the case-coordinator-only OPA data projection (ADR-0271).

The output intersects two authoritative sources without copying their unrelated fields:
agent ids + case_capabilities from agents.yaml, and agent_case_capability_matrix from
rules.yaml. A differential OPA evaluation proves the projection makes the same decisions
as source-shaped data before anything is written.

Usage: gen-case-collaboration-opa-data.py [--check] [--self-test]
"""

from __future__ import annotations

import argparse
import copy
import json
import pathlib
import shutil
import subprocess
import sys
import tempfile
from typing import NoReturn

import yaml

REPO = pathlib.Path(__file__).resolve().parents[2]
AGENTS = REPO / "openbank-libs/governance/agents.yaml"
RULES = REPO / "openbank-libs/governance/rules.yaml"
POLICY = REPO / "openbank-infra/opa/policies/case_collaboration.rego"
OUT = REPO / "openbank-libs/governance/case-collaboration-opa-data.yaml"

ALLOWED_CAPABILITIES = {"case.join", "case.contribute"}
ALLOWED_CLASSES = {"INCIDENT_RESPONSE"}
ALLOWED_MODES = {"SHADOW"}
GRANT_FIELDS = (
    "agent_id",
    "capabilities",
    "case_class",
    "delivery_mode",
    "enabled",
    "rollout_id",
    "max_signals_per_case",
)

HEADER = """# GENERATED by .github/scripts/gen-case-collaboration-opa-data.py — do not hand-edit.
#
# Case-coordinator-only OPA input projection (ADR-0271). The bundle mounts this file at
# /bundle/case_collaboration/data.yaml, where OPA loads it as data.case_collaboration.*.
# No matrix entry means no live collaboration grant.
"""


def fail(message: str) -> NoReturn:
    raise ValueError(message)


def project(agent_doc: dict, rules_doc: dict) -> dict:
    raw_agents = agent_doc.get("agents")
    if not isinstance(raw_agents, list):
        fail("agents.yaml: agents must be a list")

    agents = []
    for raw in raw_agents:
        if not isinstance(raw, dict):
            fail("agents.yaml: every agent must be a mapping")
        capabilities = raw.get("case_capabilities", [])
        if not isinstance(capabilities, list) or not all(isinstance(value, str) for value in capabilities):
            fail(f"agents.yaml: {raw.get('id', '<unknown>')}.case_capabilities must be a string list")
        if capabilities:
            agent_id = raw.get("id")
            if not isinstance(agent_id, str) or not agent_id:
                fail("agents.yaml: a case-capability holder needs a non-empty id")
            agents.append({"id": agent_id, "case_capabilities": sorted(set(capabilities))})

    raw_grants = rules_doc.get("agent_case_capability_matrix")
    if not isinstance(raw_grants, list):
        fail("rules.yaml: agent_case_capability_matrix must be a list (empty means deny all)")

    grants = []
    for index, raw in enumerate(raw_grants):
        if not isinstance(raw, dict):
            fail(f"rules.yaml: grant {index} must be a mapping")
        missing = [field for field in GRANT_FIELDS if field not in raw]
        if missing:
            fail(f"rules.yaml: grant {index} missing {', '.join(missing)}")
        capabilities = raw["capabilities"]
        if not isinstance(capabilities, list) or not capabilities or not all(isinstance(value, str) for value in capabilities):
            fail(f"rules.yaml: grant {index} capabilities must be a non-empty string list")
        unknown = set(capabilities) - ALLOWED_CAPABILITIES
        if unknown:
            fail(f"rules.yaml: grant {index} has non-pilot capabilities: {sorted(unknown)}")
        if raw["case_class"] not in ALLOWED_CLASSES:
            fail(f"rules.yaml: grant {index} case_class is outside the shadow pilot")
        if raw["delivery_mode"] not in ALLOWED_MODES:
            fail(f"rules.yaml: grant {index} delivery_mode must be SHADOW")
        if not isinstance(raw["enabled"], bool):
            fail(f"rules.yaml: grant {index} enabled must be boolean")
        if not isinstance(raw["rollout_id"], str) or not raw["rollout_id"]:
            fail(f"rules.yaml: grant {index} rollout_id must be non-empty")
        quota = raw["max_signals_per_case"]
        if not isinstance(quota, int) or isinstance(quota, bool) or quota < 1 or quota > 8:
            fail(f"rules.yaml: grant {index} max_signals_per_case must be between 1 and 8")
        grants.append({field: copy.deepcopy(raw[field]) for field in GRANT_FIELDS})

    agents.sort(key=lambda item: item["id"])
    grants.sort(key=lambda item: (item["agent_id"], item["case_class"], item["delivery_mode"], item["rollout_id"]))
    return {"agents": agents, "grants": grants}


def source_view(agent_doc: dict, rules_doc: dict) -> dict:
    return {
        "agents": copy.deepcopy(agent_doc["agents"]),
        "grants": copy.deepcopy(rules_doc["agent_case_capability_matrix"]),
    }


def decisions(view: dict, policy_inputs: list[dict]) -> list[dict]:
    opa = shutil.which("opa")
    if not opa:
        fail("opa is required for the differential decision proof")
    with tempfile.TemporaryDirectory(prefix="case-opa-proof-") as tmp:
        root = pathlib.Path(tmp)
        data_file = root / "data.json"
        input_file = root / "input.json"
        data_file.write_text(
            json.dumps({"case_collaboration": view, "case_collaboration_proof_inputs": policy_inputs}),
            encoding="utf-8",
        )
        input_file.write_text("{}", encoding="utf-8")
        result = subprocess.run(
            [
                opa,
                "eval",
                "--format",
                "json",
                "-d",
                str(POLICY),
                "-d",
                str(data_file),
                "-i",
                str(input_file),
                "[d | some policy_input in data.case_collaboration_proof_inputs; d := data.openbank.case_collaboration.decision with input as policy_input]",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
    parsed = json.loads(result.stdout)
    expressions = parsed.get("result", [{}])[0].get("expressions", [])
    if len(expressions) != 1 or not isinstance(expressions[0].get("value"), list):
        fail("OPA returned no case decision list for the differential proof")
    return sorted(expressions[0]["value"], key=lambda value: json.dumps(value, sort_keys=True))


def prove_equivalent(agent_doc: dict, rules_doc: dict, projected: dict) -> int:
    full = source_view(agent_doc, rules_doc)
    agent_ids = sorted({item.get("id", "") for item in agent_doc["agents"]} | {"unknown-agent"})
    capabilities = sorted(
        {cap for item in agent_doc["agents"] for cap in item.get("case_capabilities", [])}
        | {cap for grant in rules_doc["agent_case_capability_matrix"] for cap in grant.get("capabilities", [])}
        | ALLOWED_CAPABILITIES
        | {"case.synthesize"}
    )
    case_classes = sorted(
        {grant.get("case_class", "") for grant in rules_doc["agent_case_capability_matrix"]}
        | ALLOWED_CLASSES
        | {"AML_REVIEW"}
    )
    modes = sorted(
        {grant.get("delivery_mode", "") for grant in rules_doc["agent_case_capability_matrix"]}
        | ALLOWED_MODES
        | {"HITL"}
    )
    policy_inputs = []
    for agent_id in agent_ids:
        for capability in capabilities:
            for case_class in case_classes:
                for mode in modes:
                    policy_input = {
                        "agent": agent_id,
                        "capability": capability,
                        "case_class": case_class,
                        "delivery_mode": mode,
                    }
                    policy_inputs.append(policy_input)
    before = decisions(full, policy_inputs)
    after = decisions(projected, policy_inputs)
    if before != after:
        fail("differential proof diverged between source-shaped data and projection")
    return len(policy_inputs)


def render(value: dict) -> str:
    return HEADER + "\n" + yaml.safe_dump(value, sort_keys=False, allow_unicode=True)


def load_documents() -> tuple[dict, dict]:
    return (
        yaml.safe_load(AGENTS.read_text(encoding="utf-8")),
        yaml.safe_load(RULES.read_text(encoding="utf-8")),
    )


def self_test() -> None:
    agent_doc = {
        "agents": [{
            "id": "rca-investigator",
            "description": "must not enter projection",
            "case_capabilities": ["case.contribute", "case.join"],
            "tools": {"allow": ["read.logs"]},
        }],
    }
    rules_doc = {
        "agent_case_capability_matrix": [{
            "agent_id": "rca-investigator",
            "capabilities": ["case.join", "case.contribute"],
            "case_class": "INCIDENT_RESPONSE",
            "delivery_mode": "SHADOW",
            "enabled": True,
            "rollout_id": "self-test",
            "max_signals_per_case": 8,
            "ignored": "must not enter projection",
        }],
    }
    projected = project(agent_doc, rules_doc)
    if "description" in projected["agents"][0] or "ignored" in projected["grants"][0]:
        fail("self-test: projection retained an unrelated field")
    count = prove_equivalent(agent_doc, rules_doc, projected)
    broken = copy.deepcopy(rules_doc)
    broken["agent_case_capability_matrix"][0]["delivery_mode"] = "HITL"
    try:
        project(agent_doc, broken)
    except ValueError:
        print(f"self-test: OK — projection narrowed fields, rejected HITL, and proved {count} decisions")
        return
    fail("self-test: HITL grant was accepted")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return

    agent_doc, rules_doc = load_documents()
    projected = project(agent_doc, rules_doc)
    count = prove_equivalent(agent_doc, rules_doc, projected)
    rendered = render(projected)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            sys.exit(f"::error file={OUT.relative_to(REPO)}::case collaboration OPA data is stale; run {pathlib.Path(__file__).name}")
        print(f"case collaboration OPA data: OK — {count} source/projection decisions identical")
        return
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(rendered)} bytes; {count} decisions identical)")


if __name__ == "__main__":
    main()
