#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
#
# Renders docs/cards/capability-matrix.md from openbank-libs/governance/card-capabilities.yaml.
#
# WHY THIS EXISTS
#   ADR-0283's promise is that a bank can choose its card network per product and see what that
#   choice costs. A hand-written comparison table is that promise's weakest form: it is right on the
#   day it is written and silently wrong afterwards, and nothing in CI can tell the difference.
#   Generating it makes the registry the only thing anyone edits (rule 6), and the drift check makes
#   an edit to the artifact a build failure rather than a divergence nobody notices.
#
#   The same registry feeds the Card Center screen in ADR-0283 phase 3, so the two cannot disagree.
#
# WHAT IT DELIBERATELY DOES NOT DO
#   It does not claim an integration exists. `bindings` is rendered verbatim, and a capability whose
#   only binding is the simulator says exactly that. A matrix that reads like an integration status
#   page is worse than no matrix, because the reader cannot tell a plan from a fact.
#
# Usage: python3 .github/scripts/gen-card-capability-matrix.py [--check]
#   --check exits 1 if the rendered output differs from what is committed (drift), printing nothing
#   else — the shape every derived-file checker here uses.

import argparse
import pathlib
import sys

try:
    import yaml
except ImportError as missing:  # pragma: no cover - the fleet always has PyYAML
    print("PyYAML is required", file=sys.stderr)
    raise SystemExit(2) from missing

ROOT = pathlib.Path(__file__).resolve().parents[2]
REGISTRY = ROOT / "openbank-libs" / "governance" / "card-capabilities.yaml"
OUT = ROOT / "docs" / "cards" / "capability-matrix.md"

AVAILABILITY_LABEL = {
    "sandbox": "sandbox",
    "contract": "contract required",
    "none": "not offered",
}


def render(registry: dict) -> str:
    networks = registry["networks"]
    order = list(networks)
    lines = [
        "<!--",
        "SPDX-License-Identifier: Apache-2.0",
        "Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.",
        "",
        "GENERATED by .github/scripts/gen-card-capability-matrix.py — do not hand-edit.",
        "Source: openbank-libs/governance/card-capabilities.yaml (ADR-0283 phase 2).",
        "-->",
        "# Card scheme capability matrix",
        "",
        "What each card network offers, which port this platform models it behind, and what this",
        "repository actually implements today. Generated from the capability registry; edit the",
        "registry, never this file.",
        "",
        "**`bindings` is the honest column.** It records what is implemented here, not what is",
        "possible. A capability whose only binding is `simulator` has no vendor integration, and",
        "saying so is the point — a matrix that reads like an integration status page cannot be",
        "told apart from a plan.",
        "",
        "**`availability` is about the SANDBOX**, not a production contract: `sandbox` means an",
        "adapter can be exercised for free from the developer portal, `contract required` means no",
        "call succeeds before a commercial agreement is signed.",
        "",
    ]

    header = ["Capability", "Port"] + [networks[n]["label"] for n in order] + ["Bindings here"]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "---|" * len(header))
    for cap in registry["capabilities"]:
        port = cap.get("port")
        port_cell = f"`{port.rsplit('.', 1)[-1]}`" if port else "_none yet_"
        cells = [cap["label"], port_cell]
        for name in order:
            entry = (cap.get("networks") or {}).get(name)
            if not entry:
                cells.append("_not registered_")
                continue
            availability = AVAILABILITY_LABEL.get(entry.get("availability", ""), entry.get("availability", "?"))
            cells.append(f"{entry['product']} ({availability})")
        bindings = cap.get("bindings") or []
        cells.append(", ".join(bindings) if bindings else "_none_")
        lines.append("| " + " | ".join(cells) + " |")

    lines.append("")
    lines.append("## Why each capability is here")
    lines.append("")
    for cap in registry["capabilities"]:
        why = " ".join((cap.get("why") or "").split())
        lines.append(f"- **{cap['label']}** — {why}")
    lines.append("")
    lines.append("## Authenticating to each network's sandbox")
    lines.append("")
    for name in order:
        n = networks[name]
        lines.append(f"- **{n['label']}** ({n['developer_portal']}): {n['sandbox_auth']}.")
    lines.append("")
    lines.append(
        "Credentials live in OpenBao and are read only by the adapter module that needs them; no "
        "service outside an adapter sees a network credential."
    )
    lines.append("")
    return "\n".join(lines)


def self_test() -> int:
    """
    Drives --check's comparison against a rendering that must NOT match, and asserts it says so.

    A drift checker whose red path has never executed is a green nobody can rely on — this repo has
    been burnt three separate times by exactly that (#2165, #2154, #2177). The comparison is the
    whole gate, so it is what gets falsified here: render the real registry, mutate one visible
    cell, and require the comparison to report a difference. Both directions are asserted, so a
    checker that always reports drift fails this too.
    """
    registry = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    rendered = render(registry)

    if rendered != render(registry):
        print("self-test FAILED: rendering is not deterministic", file=sys.stderr)
        return 1

    mutated = dict(registry)
    mutated["capabilities"] = [dict(c) for c in registry["capabilities"]]
    mutated["capabilities"][0]["bindings"] = ["visa-sandbox-that-does-not-exist"]
    if render(mutated) == rendered:
        print(
            "self-test FAILED: a changed `bindings` produced an identical matrix — the generator "
            "is not reading the column the whole registry exists to publish",
            file=sys.stderr,
        )
        return 1

    print("self-test ok: the matrix changes when the registry does, and is stable when it does not")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed file has drifted")
    ap.add_argument("--self-test", action="store_true", help="prove --check can go red")
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    registry = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    rendered = render(registry)

    if args.check:
        if not OUT.is_file():
            print(f"::error::{OUT.relative_to(ROOT)} does not exist — run the generator", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != rendered:
            print(
                f"::error::{OUT.relative_to(ROOT)} has drifted from card-capabilities.yaml — "
                "regenerate it (bash .github/scripts/regen-derived.sh) and commit the result",
                file=sys.stderr,
            )
            return 1
        print(f"card capability matrix: OK ({len(registry['capabilities'])} capabilities)")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(registry['capabilities'])} capabilities)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
