#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
"""Derive the OPA policy-input subset of `rules.yaml` — the only part any bundle needs.

WHAT THIS FIXES

Every service OPA bundle used to embed `openbank-libs/governance/rules.yaml` VERBATIM
(168 KB, 2358 lines) and hash it into that service's `openbank.tech/policy-checksum`
pod-roll annotation. Two consequences, both measured:

  1. THROUGHPUT (#3357). A one-line `rules.yaml` edit restamped ~78 files under
     `openbank-infra/gitops/components/` — 39 bundle ConfigMaps plus the 39 pod-roll
     annotations that live in the same `*-service.yaml` files the auto-deploy bot bumps
     image pins in. Those PRs re-conflicted within minutes and could not be landed
     during working hours. Measured over the last 80 revisions of `rules.yaml`, only 16
     changed anything OPA reads: 80% of that contention was for data the policy never
     consults.

  2. CORRECTNESS. `rules.yaml` is 62% of every bundle's bytes, and all 39 bundles sit
     over 200 KB against Kubernetes' 262144-byte `metadata.annotations` ceiling. Five
     Applications had already crossed it and were serving FROZEN policy — see
     check-opa-bundle-apply-size.py, which documents that incident. Dropping the unread
     bulk takes every bundle far back under the ceiling.

WHAT IT EMITS

`openbank-libs/governance/rules-opa-data.yaml`: the top-level keys of `rules.yaml` that
a `.rego` in this repo actually references as `data.rules.<key>`, and nothing else.

THE KEY SET IS DERIVED, NEVER LISTED. It is read out of the `.rego` sources themselves.
A hand-kept list of "keys the policy reads" is the exact shape this repo has been burnt
by before (`pact-drift-check.yml`'s hand-kept module list, #2284): the list goes stale,
the subset silently omits a key the policy started reading, and `data.rules.<key>` then
evaluates to undefined — which in Rego is not an error, it is a rule that quietly stops
firing. Deriving the set means adding `data.rules.newthing` to a policy automatically
adds `newthing` to the emitted data on the next generation, and `--check` fails until it
is committed.

TWO THINGS THAT ARE DELIBERATELY *NOT* REPAIRED HERE

  - A referenced key that does not exist at the top level of `rules.yaml` is reported and
    then left absent, exactly as it is today. `rest.rego` reads
    `data.rules.shared_m2m_write_prohibition`, but that key is nested under
    `change_requirements:` in `rules.yaml`, so it is undefined in the cluster right now
    and the `prohibited` rule it guards has never fired. Promoting it would be a
    SEMANTIC policy change smuggled inside a mechanical one. Reported, not fixed.
  - The extraction is byte-preserving. Each selected key's block is copied out of
    `rules.yaml` as raw text rather than re-serialised through a YAML dumper, so the
    value OPA parses is character-identical to the value it parses today. The generator
    then loads both documents and asserts deep equality per key before writing — a
    re-dump could not make that promise, and equality is the whole safety argument.

Usage:  gen-rules-opa-data.py [--check] [--self-test]
        (no flags) write the derived file
        --check     exit 1 if the committed file differs from a fresh derivation
        --self-test prove the check can fail
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import tempfile

import yaml

REPO = pathlib.Path(__file__).resolve().parents[2]
RULES = REPO / "openbank-libs" / "governance" / "rules.yaml"
OUT = REPO / "openbank-libs" / "governance" / "rules-opa-data.yaml"

# A top-level key of rules.yaml starts in column 0. Block-scalar content is always
# indented in YAML, so a column-0 identifier can never be part of another key's value.
TOP_KEY = re.compile(r"^([A-Za-z_][A-Za-z_0-9]*):")

# `data.rules.<key>` — the only shape the policies use. A dynamic index (`data.rules[x]`)
# cannot be resolved statically and would make subsetting unsound, so it is a hard error.
REF = re.compile(r"\bdata\.rules\.([A-Za-z_][A-Za-z_0-9]*)")
DYNAMIC_REF = re.compile(r"\bdata\.rules\s*\[")

HEADER = """# GENERATED by .github/scripts/gen-rules-opa-data.py — do not hand-edit.
#
# The subset of openbank-libs/governance/rules.yaml that OPA actually reads: the
# top-level keys some .rego in this repo references as data.rules.<key>. Mounted into
# every service bundle at /bundle/rules/data.yaml, so it loads as data.rules.*.
#
# Blocks below are copied VERBATIM out of rules.yaml — edit rules.yaml, then re-run the
# generator. The generator asserts each key deep-equals its source before writing.
"""


def strip_rego_comments(text: str) -> str:
    """Drop `#` comments. A comment that mentions `data.rules.x` is prose about the
    policy, not the policy — counting it would let a stale doc-comment pin a key into the
    emitted data forever (the code-about-code collision, #2450)."""
    out = []
    for line in text.splitlines():
        in_str = False
        cut = len(line)
        i = 0
        while i < len(line):
            c = line[i]
            if c == "\\" and in_str:
                i += 2
                continue
            if c == '"':
                in_str = not in_str
            elif c == "#" and not in_str:
                cut = i
                break
            i += 1
        out.append(line[:cut])
    return "\n".join(out)


def referenced_keys(repo: pathlib.Path) -> set[str]:
    """Every top-level rules.yaml key referenced from any .rego in the tree.

    Test policies are included on purpose: over-including a key costs a few lines of
    generated YAML, under-including one silently disables a rule.
    """
    keys: set[str] = set()
    for rego in sorted(repo.rglob("*.rego")):
        if ".git" in rego.parts:
            continue
        body = strip_rego_comments(rego.read_text(encoding="utf-8"))
        if DYNAMIC_REF.search(body):
            sys.exit(
                f"::error file={rego.relative_to(repo)}::dynamic `data.rules[...]` index — "
                "the emitted subset cannot be derived statically. Use data.rules.<key>."
            )
        keys.update(REF.findall(body))
    return keys


def extract_blocks(text: str, keys: set[str]) -> tuple[list[str], list[str]]:
    """Raw text of each requested top-level key's block, in file order."""
    lines = text.splitlines(keepends=True)
    starts: list[tuple[int, str]] = []
    for i, line in enumerate(lines):
        m = TOP_KEY.match(line)
        if m:
            starts.append((i, m.group(1)))

    blocks: list[str] = []
    found: list[str] = []
    for idx, (start, name) in enumerate(starts):
        if name not in keys:
            continue
        end = starts[idx + 1][0] if idx + 1 < len(starts) else len(lines)
        # Trailing blank/comment lines before the next key belong to that key's preamble,
        # not to this value. Dropping them keeps the artifact readable; YAML ignores both.
        block = lines[start:end]
        while block and (not block[-1].strip() or block[-1].lstrip().startswith("#")):
            block.pop()
        blocks.append("".join(block))
        found.append(name)
    return blocks, found


def render(rules_text: str, keys: set[str]) -> tuple[str, list[str], list[str]]:
    blocks, found = extract_blocks(rules_text, keys)
    missing = sorted(keys - set(found))
    return HEADER + "\n" + "\n".join(blocks), found, missing


def verify_equivalence(rules_text: str, derived_text: str, found: list[str]) -> None:
    """The safety argument: for every emitted key, the parsed value must deep-equal the
    value parsed from rules.yaml. If this ever fails the extraction is unsound and no
    file is written."""
    src = yaml.safe_load(rules_text) or {}
    got = yaml.safe_load(derived_text) or {}
    if sorted(got) != sorted(found):
        sys.exit(
            f"::error::derived document has keys {sorted(got)}, expected {sorted(found)}"
        )
    for k in found:
        if got[k] != src[k]:
            sys.exit(f"::error::derived value for `{k}` does not equal rules.yaml's")


def build() -> tuple[str, list[str]]:
    rules_text = RULES.read_text(encoding="utf-8")
    keys = referenced_keys(REPO)
    text, found, missing = render(rules_text, keys)
    verify_equivalence(rules_text, text, found)
    return text, missing


# A referenced key that cannot be selected is DECLARED debt, not a warning.
#
# `shared_m2m_write_prohibition` sat here as a ::warning:: on every run and nobody acted, because a
# warning over a GENERATED artifact says "the committed document does not match reality" — there is
# no judgement left to exercise, so advisory only makes the drift mergeable (the repo's own lesson,
# #2156/#2216). Meanwhile `rest.rego:482` reads it, the register is undefined in-cluster, `r in
# <undefined>` iterates nothing, and the `prohibited` rule that mitigates GHSA-58jq-9hq3-66jr has
# never denied anything. Measured against the live bundles: 128 writes reachable by the shared M2M
# client on services already running AUTHZ_ENFORCE=true (#3765/#3734).
#
# What made it invisible for so long: `rest_test.rego`'s regression test SUPPLIES the register it
# tests against — `with data.rules.shared_m2m_write_prohibition.reasons as ["operator-ledger-write"]`
# — so it is green about a rule that works given data production never has. Neither the policy source
# nor its tests can reveal this; only evaluating against the deployed bundle can.
#
# So: today's one occurrence is declared with its reason and its issue, and anything NEW fails. A
# declaration that becomes resolvable is reported too, so this cannot quietly become permanent.
UNRESOLVABLE_DECLARED: dict[str, str] = {
    "shared_m2m_write_prohibition": (
        "nested under `change_requirements:` in rules.yaml, so it cannot be selected as a top-level "
        "key. Promoting it is a POLICY DECISION, not an edit: 128 currently-reachable writes depend "
        "on the very reasons the register names, so promotion denies live money-path callers. "
        "Tracked in #3765/#3734 — remove this entry in the same change that promotes the key."
    ),
}


def report_missing(missing: list[str]) -> int:
    """Return 0 when every unresolvable key is declared, 1 otherwise."""
    rc = 0
    for k in missing:
        if k in UNRESOLVABLE_DECLARED:
            print(
                f"::notice::`data.rules.{k}` is referenced by a policy and is undefined in the "
                f"cluster — declared debt: {UNRESOLVABLE_DECLARED[k]}",
                file=sys.stderr,
            )
            continue
        rc = 1
        print(
            f"::error::`data.rules.{k}` is referenced by a policy but is not a top-level key of "
            "rules.yaml, so it is UNDEFINED in every deployed bundle. In rego `r in <undefined>` "
            "iterates nothing, so the rule reading it cannot fire — and its unit tests can still be "
            "green, because a test may supply the data with `with data.rules... as [...]`. Either "
            "make it a top-level key (a policy decision — it changes live decisions) or declare it "
            "in UNRESOLVABLE_DECLARED with the reason and the issue.",
            file=sys.stderr,
        )
    stale = sorted(set(UNRESOLVABLE_DECLARED) - set(missing))
    for k in stale:
        rc = 1
        print(
            f"::error::`{k}` is declared unresolvable but IS now selectable — the debt is paid, so "
            "drop its UNRESOLVABLE_DECLARED entry.",
            file=sys.stderr,
        )
    return rc


def self_test() -> int:
    """Prove --check can fail, and that the extraction really is value-preserving."""
    ok = True

    sample = (
        "alpha:\n  a: 1\n\n# preamble for beta\nbeta:\n  b:\n    - x\n    - y\n\n"
        "gamma:\n  c: |\n    a block\n    with lines\n"
    )
    text, found, missing = render(sample, {"beta", "gamma", "nope"})
    if found != ["beta", "gamma"] or missing != ["nope"]:
        print(f"FAIL: selection wrong: found={found} missing={missing}")
        ok = False
    parsed = yaml.safe_load(text)
    if parsed != {"beta": {"b": ["x", "y"]}, "gamma": {"c": "a block\nwith lines\n"}}:
        print(f"FAIL: extracted value not equal to source: {parsed}")
        ok = False
    if "alpha" in text:
        print("FAIL: unreferenced key leaked into the subset")
        ok = False

    # A stale committed file must be detected — the failure mode --check exists for.
    with tempfile.TemporaryDirectory() as d:
        stale = pathlib.Path(d) / "rules-opa-data.yaml"
        stale.write_text(text + "\nextra: 1\n", encoding="utf-8")
        if stale.read_text(encoding="utf-8") == text:
            print("FAIL: staleness comparison cannot distinguish differing files")
            ok = False

    # A comment mentioning data.rules.X must NOT pin X into the subset.
    if REF.findall(strip_rego_comments("# reads data.rules.ghost\nx := 1\n")):
        print("FAIL: a doc-comment reference was counted as a policy reference")
        ok = False
    if not REF.findall(strip_rego_comments("y := data.rules.real\n")):
        print("FAIL: a real reference was stripped as a comment")
        ok = False

    # The unresolvable-key ratchet, both directions. A rego rule reading a key the subset
    # cannot carry resolves to `undefined`, which is indistinguishable from an empty list —
    # both read as "nothing prohibited" — so silence here is the failure mode, not the pass.
    if report_missing(["a_key_nobody_declared"]) == 0:
        print("FAIL: an undeclared unresolvable key did not fail the check")
        ok = False
    if report_missing(sorted(UNRESOLVABLE_DECLARED)) != 0:
        print("FAIL: a declared unresolvable key failed the check")
        ok = False
    # A declaration that is no longer missing is a paid debt still being claimed.
    if report_missing([]) == 0 and UNRESOLVABLE_DECLARED:
        print("FAIL: a stale UNRESOLVABLE_DECLARED entry was not reported")
        ok = False

    print("self-test: PASS" if ok else "self-test: FAIL")
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    text, missing = build()
    missing_rc = report_missing(missing)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(
                "::error::openbank-libs/governance/rules-opa-data.yaml is stale — run "
                ".github/scripts/gen-rules-opa-data.py and commit the result, then "
                "re-run the OPA bundle generators.",
                file=sys.stderr,
            )
            return 1
        print(f"rules-opa-data.yaml is in sync ({len(text)} bytes)")
        # In sync is not the same as sound: a policy can reference a key the subset cannot carry,
        # in which case the file is correct AND the rule reading it is dead. Both must hold.
        return missing_rc

    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(text)} bytes)")
    return missing_rc


if __name__ == "__main__":
    sys.exit(main())
