#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
#
# regen-derived.sh — the ONE entrypoint that regenerates every derived artefact in this repo,
# in dependency order, for the sources a branch actually changed.
#
# WHY THIS EXISTS
#   The derived artefacts here are generated by six programs living in four directories, and a
#   single source has up to three independent tails. `agents.yaml` is the worked example: it feeds
#   `docs/compliance/eu-ai-act.md`, `openbank-admin-ui/ai-governance-snapshot.json`, AND — via
#   `agents-opa-data.yaml` — every OPA bundle ConfigMap plus its pod-roll `policy-checksum`
#   annotation. Nothing names that fan-out in one place, so it is carried in a contributor's head,
#   and #3771 regenerated none of the three and red-gated `main`.
#
#   The ordering is not cosmetic either. The derived DATA files must be written before the bundles
#   that embed them, or the bundles are stamped against the previous revision and the drift gate
#   fails on content nobody wrote.
#
# THE ORDERING TRAP THIS SCRIPT REFUSES TO WALK INTO
#   Two of the derived-file CHECKS restore their subject to HEAD on a failing run:
#   check-adr-registry.sh and check-eu-ai-act.sh (its line 25, a `git checkout --` of the doc). So
#   `regenerate -> check -> commit` silently commits the RESTORED content, and the next regen then
#   disagrees with what was committed — the gate fails on content you never authored (#3983, #4002).
#
#   The only correct order is REGENERATE -> STAGE+COMMIT -> CHECK. This script therefore does the
#   regeneration and stops: it never runs a checker, and it prints the next two commands. Being
#   unable to run the checks is the feature, and the self-test asserts it.
#
# WHAT IT DOES NOT DO
#   It does not decide whether a regeneration was NEEDED. gen-rules-opa-data.py projects only the
#   top-level keys some .rego actually reads, so editing a key outside that read set produces a
#   byte-identical output and no bundle moves. Running this script on a branch that needed nothing
#   is a no-op costing seconds; guessing that you needed nothing is how main goes red.
#
# Usage:
#   bash .github/scripts/regen-derived.sh              # sources changed vs origin/main
#   bash .github/scripts/regen-derived.sh --all        # everything, unconditionally
#   bash .github/scripts/regen-derived.sh --selftest   # prove the generator inventory is complete

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

MODE="changed"
case "${1:-}" in
  --all) MODE="all" ;;
  --selftest) MODE="selftest" ;;
  "") ;;
  *) echo "unknown argument: $1" >&2; exit 2 ;;
esac

# --- the inventory -----------------------------------------------------------------------------
# Every generator in the repo, and the source path fragments that make it stale. `bundles` is a
# pseudo-entry expanded to the per-component scripts at run time, so a new component needs no edit.
#
# The SELF-TEST asserts this inventory names every gen-* program that exists, which is what stops a
# new generator being added and silently never invoked — the failure mode a hand-kept list has.
GENERATORS=(
  "rules-opa-data|python3 .github/scripts/gen-rules-opa-data.py|openbank-libs/governance/rules.yaml"
  "agents-opa-data|python3 .github/scripts/gen-agents-opa-data.py|openbank-libs/governance/agents.yaml"
  "case-collaboration-opa-data|python3 .github/scripts/gen-case-collaboration-opa-data.py|openbank-libs/governance/agents.yaml openbank-libs/governance/rules.yaml .rego"
  "eu-ai-act|python3 .github/scripts/gen-eu-ai-act.py|openbank-libs/governance/agents.yaml"
  "ai-governance-snapshot|python3 .github/scripts/gen-ai-governance-snapshot.py|openbank-libs/governance/agents.yaml prompts/registry.yaml"
  "adr-index|bash docs/adr/gen-index.sh|docs/adr/"
  "bundles|__BUNDLES__|openbank-libs/governance/rules.yaml openbank-libs/governance/agents.yaml .rego"
)

changed_files() {
  local base
  base="$(git merge-base HEAD origin/main 2>/dev/null || echo "")"
  if [[ -z "$base" ]]; then
    echo "WARN: no merge-base with origin/main — falling back to --all" >&2
    return 1
  fi
  {
    git diff --name-only "$base"...HEAD
    git diff --name-only
    git ls-files --others --exclude-standard
  } | sort -u
}

matches_any() {
  local files="$1"
  local patterns="$2"
  local pattern
  for pattern in $patterns; do
    if grep -qF -- "$pattern" <<<"$files"; then return 0; fi
  done
  return 1
}

run_bundles() {
  local script
  local count=0
  while IFS= read -r script; do
    bash "$script"
    count=$((count + 1))
  done < <(find openbank-infra/gitops/components -name 'gen-*opa-bundle*.sh' | sort)
  echo "    (${count} bundle scripts)"
}

# --- self-test ---------------------------------------------------------------------------------
# The falsifiable property: the inventory above is COMPLETE, in both directions. A generator that
# exists in the tree and is not named here would never run — and this script's entire value is the
# claim that no such generator exists. Derived from the filesystem, never asserted.
selftest() {
  local failures=0
  local entry

  local -a on_disk=()
  while IFS= read -r f; do
    [[ -n "$f" ]] && on_disk+=("$f")
  done < <(
    {
      ls .github/scripts/gen-*.py 2>/dev/null || true
      ls docs/adr/gen-index.sh 2>/dev/null || true
    } | sort
  )

  if [[ ${#on_disk[@]} -eq 0 ]]; then
    echo "  [FAIL] found no generators on disk — the self-test lost its own corpus"
    failures=$((failures + 1))
  fi

  local f named
  for f in "${on_disk[@]}"; do
    named=0
    for entry in "${GENERATORS[@]}"; do
      if grep -qF -- "$f" <<<"${entry#*|}"; then named=1; break; fi
    done
    if [[ $named -eq 0 ]]; then
      echo "  [FAIL] generator not named in GENERATORS, so it would never run: $f"
      failures=$((failures + 1))
    else
      echo "  [ok] inventoried: $f"
    fi
  done

  # The reverse direction: an entry naming a program that no longer exists is a stale claim, and
  # would fail at run time on the first branch that happened to touch its source.
  for entry in "${GENERATORS[@]}"; do
    local cmd prog
    cmd="${entry#*|}"
    cmd="${cmd%%|*}"
    [[ "$cmd" == "__BUNDLES__" ]] && continue
    prog="$(awk '{print $2}' <<<"$cmd")"
    if [[ ! -f "$prog" ]]; then
      echo "  [FAIL] stale inventory entry, program does not exist: $prog"
      failures=$((failures + 1))
    fi
  done

  # The bundle expansion must find a corpus. Zero scripts makes the bundle step a silent no-op —
  # the "examines nothing, therefore passes everything" shape (#4339).
  local bundles
  bundles="$(find openbank-infra/gitops/components -name 'gen-*opa-bundle*.sh' | wc -l | tr -d ' ')"
  if [[ "$bundles" -lt 20 ]]; then
    echo "  [FAIL] bundle expansion found only $bundles scripts — the corpus was lost"
    failures=$((failures + 1))
  else
    echo "  [ok] bundle expansion found $bundles scripts"
  fi

  # This script must not be able to run a checker: the whole ordering guarantee rests on it.
  if grep -vE '^\s*#' "${BASH_SOURCE[0]}" | grep -qE 'check-[a-z0-9-]+\.(sh|py)'; then
    echo "  [FAIL] this script invokes a checker — regenerate->check->commit commits restored content"
    failures=$((failures + 1))
  else
    echo "  [ok] invokes no checker (regenerate -> commit -> check is structural, not advisory)"
  fi

  # Printed unconditionally, including on the failure path: a self-test that found its corpus and
  # then failed on it must not also read as having lost the corpus (run-gates.py min_subjects).
  echo "SUBJECTS=$(( ${#on_disk[@]} + bundles ))  # generators inventoried + bundle scripts found"

  if [[ $failures -gt 0 ]]; then
    echo "SELF-TEST FAILED: $failures problem(s)."
    return 1
  fi
  echo "SELF-TEST OK: inventory complete both ways, corpus present, no checker invoked."
  return 0
}

if [[ "$MODE" == "selftest" ]]; then
  selftest
  exit $?
fi

FILES=""
if [[ "$MODE" == "changed" ]]; then
  if ! FILES="$(changed_files)"; then MODE="all"; fi
fi

echo "regen-derived: mode=$MODE"
RAN=0
for entry in "${GENERATORS[@]}"; do
  name="${entry%%|*}"
  rest="${entry#*|}"
  cmd="${rest%%|*}"
  globs="${rest#*|}"

  if [[ "$MODE" == "changed" ]] && ! matches_any "$FILES" "$globs"; then
    echo "  skip  $name (no source changed)"
    continue
  fi

  echo "  run   $name"
  if [[ "$cmd" == "__BUNDLES__" ]]; then
    run_bundles
  else
    eval "$cmd"
  fi
  RAN=$((RAN + 1))
done

echo
echo "regen-derived: $RAN generator group(s) ran."
git --no-pager status --porcelain | sed 's/^/    /'
cat <<'NEXT_STEPS'

NEXT — in this order, and only this order:
    git add <the files listed above>    # explicit list, never -A
    git commit -s -S
    python3 .github/scripts/run-gates.py --all

Running the gates BEFORE the commit is the trap: two of the derived-file checks
restore their subject to HEAD on a failing run, so the commit then captures the
restored content and the next regeneration disagrees with it (#3983, #4002).
NEXT_STEPS
