#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents-opa-data.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Pid REST extension — identity + EUDI + party actions for operators/admins
# Pid-service REST extension (ADR-0034, ADR-0094, ADR-0072).
#
# Extension extracted to a standalone .rego (mirroring vop_rest_ext.rego, #4239, and the #1322
# pattern) so `opa test` can load and cover it — see pid_rest_ext_test.rego in this same
# directory. It was a heredoc until #4228, which is why its rules had no test at all:
# opa-policy.yml discovers suites by the *_rest_ext.rego / *_rest_ext_test.rego file PAIR, and a
# heredoc has no file to pair with.
PID_REST_EXT=$REPO/openbank-infra/gitops/components/pid/pid_rest_ext.rego

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$PID_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/pid/pid-opa-bundle.yaml

{
  echo "# GENERATED by gen-pid-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + pid_rest_ext.rego + agents.rego + agents-opa-data.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: pid-opa-bundle"
  echo "  namespace: pid"
  echo "  labels:"
  echo "    app.kubernetes.io/name: pid-service"
  echo "    app.kubernetes.io/part-of: pid"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  pid_rest_ext.rego: |"
  sed 's/^/    /' "$PID_REST_EXT" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Deployment pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — a stale annotation means pods keep the old policy).
DEPLOY=$REPO/openbank-infra/gitops/components/pid/pid-service.yaml
if [ -f "$DEPLOY" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$DEPLOY"
  rm -f "${DEPLOY}.bak"
  echo "patched $DEPLOY annotation → $CHECKSUM"
fi
