#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
CONSENT_REST_EXT=$REPO/openbank-infra/gitops/components/consent/consent_rest_ext.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Extracted to a standalone consent_rest_ext.rego (matches kyc/psd2/aml's convention) so
# `opa test` can run it directly — ADR-0206 D5 added consent_rest_ext_test.rego, which needs a
# real file to load, not a heredoc trapped inside this script.
CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$CONSENT_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/consent/consent-opa-bundle.yaml

{
  echo "# GENERATED by gen-consent-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + consent_rest_ext.rego + agents.rego + agents.yaml + rules.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: consent-opa-bundle"
  echo "  namespace: consent"
  echo "  labels:"
  echo "    app.kubernetes.io/name: consent-service"
  echo "    app.kubernetes.io/part-of: consent"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  consent_rest_ext.rego: |"
  sed 's/^/    /' "$CONSENT_REST_EXT" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-customer-edge-opa-bundle.sh).
ROLLOUT=$REPO/openbank-infra/gitops/components/consent/consent-service.yaml
if [ -f "$ROLLOUT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$ROLLOUT"
  rm -f "${ROLLOUT}.bak"
  echo "patched $ROLLOUT annotation → $CHECKSUM"
fi
