#!/usr/bin/env bash
# Generates keycloak-theme-openbank.yaml (the ConfigMap ArgoCD applies) from the
# human-editable theme source under ./theme/openbank/login.
#
# ArgoCD's directory source only applies *.yaml, and the vault PNG is binary, so
# the theme cannot ship as loose files — it is packed into one ConfigMap:
#   - text files (theme.properties, css, messages) -> data:
#   - the PNG                                       -> binaryData:
# The Deployment mounts each key back to its real theme path via subPath.
#
# ConfigMap keys cannot contain '/', so keys are flat names; keycloak.yaml maps
# each flat key to its nested theme path. After editing anything under theme/,
# re-run this script and commit the regenerated ConfigMap.
set -euo pipefail
cd "$(dirname "$0")"

SRC=theme/openbank/login
OUT=keycloak-theme-openbank.yaml

{
  echo "# GENERATED by gen-theme-configmap.sh — do not hand-edit. Source: ./theme/openbank/login"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: keycloak-theme-openbank"
  echo "  namespace: iam"
  echo "  labels:"
  echo "    app.kubernetes.io/name: keycloak"
  echo "    app.kubernetes.io/part-of: iam"
  echo "data:"
  for f in theme.properties resources/css/openbank.css messages/messages_en.properties; do
    key=$(basename "$f")
    echo "  $key: |"
    sed 's/^/    /' "$SRC/$f" | sed 's/[[:space:]]*$//'
  done
  echo "binaryData:"
  echo "  openbank-vault.png: $(base64 < "$SRC/resources/img/openbank-vault.png" | tr -d '\n')"
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes)"

# Roll the pod on theme change: stamp the ConfigMap's checksum into the
# Deployment pod-template annotation (subPath mounts don't hot-reload).
SUM=$(shasum -a 256 "$OUT" | cut -c1-16)
sed -i '' -E "s|(openbank.dev/theme-checksum: )\".*\"|\1\"$SUM\"|" keycloak.yaml
echo "stamped theme-checksum=$SUM into keycloak.yaml"
