#!/usr/bin/env bash
# Generates engagement-service-opa-bundle.yaml (the ConfigMap ArgoCD applies) from the
# REST authorization policy source of truth. The engagement-service OPA sidecar serves
# data.openbank.rest.allow — the decision AuthorizeInterceptor (openbank-libs) queries
# for every @Authorize-annotated SurfaceResource endpoint (ADR-0034 D5, ADR-0220 D1).
#
# engagement has NO per-service *_rest_ext.rego: the rule that authorizes it —
# `allowed_reasons contains "edge-service-engagement"`, scoped to the two exact actions
# engagement.surface.read / engagement.surface.recordEvent — lives in the SHARED rest.rego
# (added by #4054). So this generator has the same five inputs as customer-edge's and
# notification's, and gains a sixth only if engagement ever needs its own extension.
#
# rest.rego co-locates with agents.rego (a SINGLE sidecar serves both planes) and reads two
# data documents:
#   data.rules.*   ← rules-opa-data.yaml  (the derived subset of rules.yaml OPA actually reads)
#   data.agents.*  ← agents.yaml          (charter lookup for the AI_AGENT branch)
# so the bundle ships all four sources. The mount layout the Deployment reproduces:
#   rest.rego        -> /bundle/rest.rego        (package openbank.rest)
#   agents.rego      -> /bundle/agents.rego      (package openbank.agents)
#   rules-data.yaml  -> /bundle/rules/data.yaml  (loads as data.rules.*)
#   agents-data.yaml -> /bundle/agents/data.yaml (loads as data.agents.*)
#   manifest.json    -> /bundle/.manifest
# A checksum annotation rolls the Deployment when the policy changes (subPath mounts do
# not hot-reload). After editing any source below, re-run this script + commit.
#
# `awk 1` rather than a bare `sed` on each source: a source file with no trailing newline
# makes `sed` emit its last line unterminated, which welds the next `data:` key onto it and
# silently swallows that key from the ConfigMap. That shipped once (#3748, fixed #3971) and
# left a service's bundle unparseable — awk 1 normalises the terminator. The
# `opa-bundle-parses` gate (#3979) is the backstop.
set -euo pipefail
cd "$(dirname "$0")"

REST=../../../../openbank-libs/governance/policies/rest.rego
AGENTS=../../../opa/policies/agents.rego
RULES=../../../../openbank-libs/governance/rules-opa-data.yaml
AGENTS_DATA=../../../../openbank-libs/governance/agents-opa-data.yaml
MANIFEST=../../../opa/bundle.manifest
OUT=engagement-service-opa-bundle.yaml

# Portable SHA-256: prefer sha256sum (Linux), fall back to shasum -a 256 (macOS).
CHECKSUM=$(cat "$REST" "$AGENTS" "$RULES" "$AGENTS_DATA" "$MANIFEST" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

{
  echo "# GENERATED by gen-engagement-opa-bundle.sh — do not hand-edit."
  echo "# Source: openbank-libs/governance/policies/rest.rego + opa/policies/agents.rego"
  echo "#         + openbank-libs/governance/rules-opa-data.yaml + agents-opa-data.yaml + opa/bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: engagement-service-opa-bundle"
  echo "  namespace: engagement"
  echo "  labels:"
  echo "    app.kubernetes.io/name: engagement-service"
  echo "    app.kubernetes.io/part-of: engagement"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  awk 1 "$REST" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  awk 1 "$AGENTS" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  awk 1 "$RULES" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  awk 1 "$AGENTS_DATA" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  awk 1 "$MANIFEST" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
} > "$OUT"
# No trailing `printf '\n'` here, unlike the sibling generators. Theirs supplies the single
# terminator their last source (bundle.manifest, which has no trailing newline) is missing;
# `awk 1` above already supplies it, so keeping the printf too would emit a BLANK last line
# and yamllint fails it: `2035:1 [empty-lines] too many blank lines (1 > 0)`. Measured on the
# first push of this branch. Drop the printf, not the awk — awk 1 is what makes every block
# terminate, and that is the #3748 defence.

echo "wrote $OUT (checksum $CHECKSUM, $(wc -c < "$OUT") bytes)"

# Sync the Deployment pod-roll annotation so a policy change always triggers a rollout.
ROLLOUT=engagement-service.yaml
if [ -f "$ROLLOUT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$ROLLOUT"
  rm -f "${ROLLOUT}.bak"
  echo "patched $ROLLOUT annotation -> $CHECKSUM"
fi
