#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
COPILOT_TOOL_REGO=$REPO/openbank-infra/opa/policies/copilot_tool.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents-opa-data.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Copilot REST extension — allows copilot.chat for authenticated customers in the customer realm
COPILOT_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# Copilot-service REST extension (ADR-0034, ADR-0089).
# Extends openbank.rest with copilot-specific allow reasons.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.

package openbank.rest

import rego.v1

# Any authenticated customer (HUMAN with a valid JWT sub) may invoke the copilot chat
# endpoint. The copilot.chat action maps to CopilotChatResource.chat / CopilotChatResource.stream.
# Resource-level IDOR is enforced inside the handler (the customerId in the request body
# is checked against the JWT sub by CopilotAuthorizationService). OPA is the HTTP gate.
allowed_reasons contains "copilot-authenticated-customer" if {
	input.principal.type == "HUMAN"
	input.principal.id != ""
	input.action == "copilot.chat"
}
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$COPILOT_REST_EXT")" \
    "$(cat "$COPILOT_TOOL_REGO")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/copilot/copilot-opa-bundle.yaml

{
  echo "# GENERATED by gen-copilot-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + copilot_tool.rego + copilot_rest_ext.rego + agents.rego + agents-opa-data.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: copilot-opa-bundle"
  echo "  namespace: platform"
  echo "  labels:"
  echo "    app.kubernetes.io/name: copilot-service"
  echo "    app.kubernetes.io/part-of: platform"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  copilot_rest_ext.rego: |"
  echo "$COPILOT_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  copilot_tool.rego: |"
  sed 's/^/    /' "$COPILOT_TOOL_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Deployment pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — a stale annotation means pods keep the old policy).
DEPLOY=$REPO/openbank-infra/gitops/components/copilot/copilot-service.yaml
if [ -f "$DEPLOY" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$DEPLOY"
  rm -f "${DEPLOY}.bak"
  echo "patched $DEPLOY annotation → $CHECKSUM"
fi
