# SPDX-License-Identifier: Apache-2.0
# anacredit-service: AnaCredit regulatory reporting (ECB loan-level data, ADR-0037). Namespace: anacredit.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anacredit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:JiRaska/open-bank-oss.git
    targetRevision: main
    path: openbank-infra/gitops/components/anacredit
  destination:
    server: https://kubernetes.default.svc
    namespace: anacredit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=false
