# SPDX-License-Identifier: Apache-2.0
# tpp-registry-service: PSD2 TPP registry (ADR-0034). Namespace: tpp-registry.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tpp-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:JiRaska/open-bank-oss.git
    targetRevision: main
    path: openbank-infra/gitops/components/tpp-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: tpp-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=false
