#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Billing REST extension — billing lifecycle allow reasons (ADR-0034 Phase 5, issue #266)
BILLING_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# Billing-service REST extension (ADR-0034 Phase 5, issue #266).
# Extends openbank.rest with billing-domain allow reasons.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.
#
# Actions gated (BillingResource):
#   billing.read — assess (dry-run) an account's product fees for a cycle
#                  (POST /api/v1/fees/assess; a `.read` verb by design, ADR-0034 D5 —
#                  the endpoint computes and returns, it cannot move money).
#
# Base rest.rego already grants: operator-read-any / compliance-read-any for the
# *.read family — billing.read is fully covered for the ops-console and compliance
# paths with no extension rule strictly required today.
#
# operator-billing-write below future-proofs the phase 2c-ii write verbs
# (e.g. billing.post once fee posting to the ledger lands) for the HUMAN
# operator/admin channel, mirroring the sca/consent/pid extensions.
#
# NO SERVICE (M2M) rule: a repo-wide sweep (gitops component env + *.kt REST
# clients) found NO in-repo M2M caller of billing-service — billing is an
# OUTBOUND actor (it reads account/balance/product-catalog and, in phase 2c-ii,
# posts to the ledger; ADR-0143). Deny-by-default stands for SERVICE principals;
# a future caller must add an action-scoped rule here, never a blanket allow.

package openbank.rest

import rego.v1

# Operators and admins may perform ANY billing lifecycle operation — the ops
# console path (re-run an assessment, and the phase 2c-ii posting verbs once
# they land behind the four-eyes gate).
allowed_reasons contains "operator-billing-write" if {
	input.principal.type == "HUMAN"
	some role in {"ROLE_OPERATOR", "ROLE_ADMIN"}
	role in input.principal.roles
	startswith(input.action, "billing.")
}
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$BILLING_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/billing/billing-opa-bundle.yaml

{
  echo "# GENERATED by gen-billing-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + billing_rest_ext.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: billing-opa-bundle"
  echo "  namespace: billing"
  echo "  labels:"
  echo "    app.kubernetes.io/name: billing-service"
  echo "    app.kubernetes.io/part-of: billing"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  billing_rest_ext.rego: |"
  echo "$BILLING_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Deployment pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-customer-edge-opa-bundle.sh).
DEPLOYMENT=$REPO/openbank-infra/gitops/components/billing/billing-service.yaml
if [ -f "$DEPLOYMENT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$DEPLOYMENT"
  rm -f "${DEPLOYMENT}.bak"
  echo "patched $DEPLOYMENT annotation → $CHECKSUM"
fi
