// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

package com.openbank.fraud.infrastructure.ml

import ai.onnxruntime.OnnxTensor
import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import com.openbank.fraud.application.port.out.MlModelPort
import com.openbank.libs.domain.feature.VELOCITY_TXN_COUNT_H1
import com.openbank.libs.domain.feature.VELOCITY_TXN_COUNT_H24
import jakarta.annotation.PreDestroy
import jakarta.enterprise.context.ApplicationScoped
import org.jboss.logging.Logger
import java.nio.FloatBuffer

/**
 * ADR-0139 phase-1b: the in-process ONNX Runtime adapter behind [MlModelPort], replacing the
 * pure-Kotlin `BaselineFraudModel` throwaway. The bundled model
 * (`src/main/resources/ml/baseline-fraud-v1.onnx`, generated by `scripts/gen_onnx_baseline_model.py`)
 * encodes the *exact same* deterministic logistic over H1/H24 velocity that `BaselineFraudModel`
 * computed directly — coefficients unchanged, only the execution engine changes. It exists to prove
 * loading, inference latency and the shadow-serving contract with a real ONNX Runtime session before
 * a genuinely trained model exists (ADR-0141 phase 2 registry).
 *
 * Session load happens once at construction; a load failure (corrupt/missing resource) is caught and
 * leaves [session] `null`, so every [scoreShadow] call returns `null` immediately — the ADR-0139
 * fail-closed floor applies to model *loading*, not just per-call inference failures. A broken shadow
 * model must never crash service startup or reach the (unaffected) rule verdict.
 */
@ApplicationScoped
class OnnxFraudModel : MlModelPort {

    private val environment: OrtEnvironment = OrtEnvironment.getEnvironment()
    private val session: OrtSession? = loadSession(environment, MODEL_RESOURCE_PATH)

    @Suppress("TooGenericExceptionCaught") // OrtException + tensor lifecycle errors have no common base
    override fun scoreShadow(features: Map<String, Double>): Double? {
        val activeSession = session ?: return null
        val h1 = (features[VELOCITY_TXN_COUNT_H1.name] ?: 0.0).toFloat()
        val h24 = (features[VELOCITY_TXN_COUNT_H24.name] ?: 0.0).toFloat()
        return try {
            OnnxTensor.createTensor(environment, FloatBuffer.wrap(floatArrayOf(h1, h24)), INPUT_SHAPE).use { input ->
                activeSession.run(mapOf(INPUT_NAME to input)).use { result ->
                    @Suppress("UNCHECKED_CAST")
                    (result[0].value as Array<FloatArray>)[0][0].toDouble()
                }
            }
        } catch (ex: Exception) {
            log.debugf(ex, "ONNX inference failed, degrading to rules-only for this request")
            null
        }
    }

    @PreDestroy
    fun close() {
        session?.close()
    }

    companion object {
        private val log = Logger.getLogger(OnnxFraudModel::class.java)
        private const val MODEL_RESOURCE_PATH = "ml/baseline-fraud-v1.onnx"
        private const val INPUT_NAME = "features"
        private val INPUT_SHAPE = longArrayOf(1, 2)

        // internal (not private): OnnxFraudModelTest exercises the load-failure branch directly with
        // a bad resource path, rather than needing a constructor test seam on the CDI bean itself.
        @Suppress("TooGenericExceptionCaught") // OrtException + IO errors have no common base worth splitting
        internal fun loadSession(environment: OrtEnvironment, resourcePath: String): OrtSession? = try {
            val modelBytes = OnnxFraudModel::class.java.classLoader.getResourceAsStream(resourcePath)
                ?.use { it.readBytes() }
                ?: error("model resource not found: $resourcePath")
            environment.createSession(modelBytes, OrtSession.SessionOptions())
        } catch (ex: Exception) {
            log.errorf(ex, "failed to load ONNX baseline fraud model (%s) — shadow scoring disabled", resourcePath)
            null
        }
    }
}
