// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

package com.openbank.fraud.infrastructure.ml

import ai.onnxruntime.OnnxTensor
import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import com.fasterxml.jackson.databind.ObjectMapper
import com.openbank.fraud.application.port.out.MlModelPort
import com.openbank.libs.domain.feature.VELOCITY_TXN_COUNT_H1
import com.openbank.libs.domain.feature.VELOCITY_TXN_COUNT_H24
import jakarta.annotation.PreDestroy
import jakarta.enterprise.context.ApplicationScoped
import org.eclipse.microprofile.config.inject.ConfigProperty
import org.jboss.logging.Logger
import java.nio.FloatBuffer
import java.security.MessageDigest

/**
 * ADR-0139 phase-1b: the in-process ONNX Runtime adapter behind [MlModelPort], replacing the
 * pure-Kotlin `BaselineFraudModel` throwaway. The bundled model
 * (`src/main/resources/ml/baseline-fraud-v1.onnx`, generated by `scripts/gen_onnx_baseline_model.py`)
 * encodes the *exact same* deterministic logistic over H1/H24 velocity that `BaselineFraudModel`
 * computed directly — coefficients unchanged, only the execution engine changes.
 *
 * ADR-0141 (model registry): before the model is loaded, its bytes are verified against a **model
 * card** sidecar (`<model>.card.json`) that pins the content SHA-256 and declares the model's
 * `scope`. This is the serving-side hook the registry ADR calls for: a wrong, corrupt or swapped
 * `.onnx` no longer loads silently. Verification is advisory by default (log + proceed) and becomes
 * fail-closed when `openbank.ml.require-signature=true`, matching the ADR-0144 advisory→enforce
 * graduation pattern — a `*-enforce`-scope trained model would flip it on. The card itself is only
 * digest-pinned today; a real detached signature is the ADR-0141 follow-up.
 *
 * Session load happens once at construction; a load or verification failure leaves [session] `null`,
 * so every [scoreShadow] call returns `null` immediately — the ADR-0139 fail-closed floor applies to
 * model *loading* (and now verification), not just per-call inference failures.
 *
 * "Failure" includes the native library not loading at all, which is an `Error` and not an
 * `Exception` — see [loadEnvironment]. Construction of this bean must never throw: it is injected
 * into the same graph as read-only endpoints that do not use a model, and a bean that fails to
 * construct takes all of them down with it.
 */
@ApplicationScoped
class OnnxFraudModel(
    @ConfigProperty(name = "openbank.ml.require-signature", defaultValue = "false")
    private val requireSignature: Boolean = false,
) : MlModelPort {

    private val environment: OrtEnvironment? = loadEnvironment()
    private val session: OrtSession? =
        environment?.let { loadSession(it, MODEL_RESOURCE_PATH, MODEL_CARD_PATH, requireSignature) }

    @Suppress("TooGenericExceptionCaught") // OrtException + tensor lifecycle errors have no common base
    override fun scoreShadow(features: Map<String, Double>): Double? {
        val env = environment ?: return null
        val activeSession = session ?: return null
        val h1 = (features[VELOCITY_TXN_COUNT_H1.name] ?: 0.0).toFloat()
        val h24 = (features[VELOCITY_TXN_COUNT_H24.name] ?: 0.0).toFloat()
        return try {
            OnnxTensor.createTensor(env, FloatBuffer.wrap(floatArrayOf(h1, h24)), INPUT_SHAPE).use { input ->
                activeSession.run(mapOf(INPUT_NAME to input)).use { result ->
                    @Suppress("UNCHECKED_CAST")
                    (result[0].value as Array<FloatArray>)[0][0].toDouble()
                }
            }
        } catch (ex: Exception) {
            log.debugf(ex, "ONNX inference failed, degrading to rules-only for this request")
            null
        }
    }

    @PreDestroy
    fun close() {
        session?.close()
    }

    companion object {
        private val log = Logger.getLogger(OnnxFraudModel::class.java)

        // internal (not private): OnnxServingSmoke runs the identical load path in-image, and
        // OnnxFraudModelTest exercises the load-failure branch directly.
        internal const val MODEL_RESOURCE_PATH = "ml/baseline-fraud-v1.onnx"
        internal const val MODEL_CARD_PATH = "ml/baseline-fraud-v1.card.json"
        private const val INPUT_NAME = "features"
        private val INPUT_SHAPE = longArrayOf(1, 2)
        private val mapper = ObjectMapper()

        // Truncation length for the sha256 printed in the model-card-verified log line —
        // enough to eyeball-correlate against the full hash without spamming the log.
        private const val LOG_SHA256_PREFIX_LEN = 12

        // Scopes this serving path is allowed to load. A model card declaring anything else (e.g. a
        // credit-decisioning model, ADR-0142) must not be served here even if its bytes verify.
        private val ALLOWED_SCOPES = setOf("fraud-shadow")

        /**
         * Acquire the ONNX Runtime environment, or `null` when the native library will not load.
         *
         * This MUST catch [Throwable], not [Exception]. `OrtEnvironment.getEnvironment()` unpacks
         * and `System.load`s a bundled `.so`, and a platform mismatch surfaces as
         * `ExceptionInInitializerError` wrapping an `UnsatisfiedLinkError` — both `Error`s, so the
         * `catch (ex: Exception)` in [loadSession] below never saw them and the class documented a
         * degradation it could not perform.
         *
         * What that cost: the deploy image was `eclipse-temurin:25-jre-alpine` (musl, no libstdc++),
         * onnxruntime's `libonnxruntime.so` is built against glibc, so `getEnvironment()` threw in
         * a FIELD INITIALIZER — construction of the bean failed, and CDI then failed every
         * injection point of it. `FraudResource.reviewQueue` is a read-only analyst query that
         * never touches the model, and it answered 500 on every call because this bean sits in the
         * same graph. A missing native library disabled a listing endpoint.
         *
         * Measured against the three candidate bases (arm64, onnxruntime 1.22.0):
         *   eclipse-temurin:25-jre-alpine                -> UnsatisfiedLinkError: libstdc++.so.6
         *   eclipse-temurin:25-jre-alpine + apk libstdc++ -> UnsatisfiedLinkError: ld-linux-aarch64.so.1
         *   eclipse-temurin:25-jre (glibc)               -> loads
         * So the runtime image is the fix for *shadow scoring*; this is the fix for *the blast
         * radius*, and it is worth having either way — a corrupt library or an OOM at load time
         * must never be able to take a read endpoint down with it.
         */
        @Suppress("TooGenericExceptionCaught") // an Error is exactly what we must survive here
        internal fun loadEnvironment(): OrtEnvironment? = try {
            OrtEnvironment.getEnvironment()
        } catch (t: Throwable) {
            log.errorf(
                t,
                "ONNX Runtime native library unavailable — shadow scoring disabled, rules-only " +
                    "verdicts stand. This does NOT change any fraud verdict (ADR-0139 phase-1b " +
                    "scores in shadow); it only removes the shadow signal.",
            )
            null
        }

        // internal (not private): OnnxFraudModelTest exercises the load-failure branch directly.
        // requireSignature defaults to false so the existing 2-/3-arg test calls keep the advisory
        // (log + proceed) behaviour without a card assertion.
        //
        // Catches Throwable for the same reason as loadEnvironment: createSession also crosses into
        // native code, so a linkage failure here is an Error, not an Exception.
        @Suppress("TooGenericExceptionCaught") // OrtException + IO errors have no common base worth splitting
        internal fun loadSession(
            environment: OrtEnvironment,
            resourcePath: String,
            cardPath: String? = null,
            requireSignature: Boolean = false,
        ): OrtSession? = try {
            val modelBytes = OnnxFraudModel::class.java.classLoader.getResourceAsStream(resourcePath)
                ?.use { it.readBytes() }
                ?: error("model resource not found: $resourcePath")
            if (cardPath != null && !verifyCard(modelBytes, cardPath, requireSignature)) {
                return null // fail-closed: card mismatch under require-signature
            }
            environment.createSession(modelBytes, OrtSession.SessionOptions())
        } catch (ex: Throwable) {
            log.errorf(ex, "failed to load ONNX baseline fraud model (%s) — shadow scoring disabled", resourcePath)
            null
        }

        /**
         * Verify the model bytes against the ADR-0141 model card: content SHA-256 must match and the
         * declared scope must be allowed here. Returns true if serving may proceed. Under
         * [requireSignature] a missing card or any mismatch returns false (fail closed); otherwise it
         * logs and returns true (advisory).
         */
        @Suppress("TooGenericExceptionCaught", "ReturnCount")
        internal fun verifyCard(modelBytes: ByteArray, cardPath: String, requireSignature: Boolean): Boolean {
            fun fail(reason: String): Boolean {
                if (requireSignature) {
                    log.errorf(
                        "model card verification FAILED (%s) — refusing to load model (require-signature=true)",
                        reason,
                    )
                    return false
                }
                log.warnf(
                    "model card verification advisory failure (%s) — loading anyway (require-signature=false)",
                    reason,
                )
                return true
            }
            val cardBytes = OnnxFraudModel::class.java.classLoader.getResourceAsStream(cardPath)?.use { it.readBytes() }
                ?: return fail("card not found: $cardPath")
            val card = try {
                mapper.readTree(cardBytes)
            } catch (ex: Exception) {
                return fail("card is not valid JSON: ${ex.message}")
            }
            val pinned = card.path("contentSha256").asText("")
            val actual = sha256Hex(modelBytes)
            if (!pinned.equals(actual, ignoreCase = true)) {
                return fail("content sha256 mismatch: card=$pinned actual=$actual")
            }
            val scope = card.path("scope").asText("")
            if (scope !in ALLOWED_SCOPES) {
                return fail("scope '$scope' not allowed here (allowed: $ALLOWED_SCOPES)")
            }
            log.infof(
                "model card verified: %s@%s scope=%s sha256=%s…",
                card.path("modelId").asText("?"),
                card.path("version").asText("?"),
                scope,
                actual.take(LOG_SHA256_PREFIX_LEN),
            )
            return true
        }

        private fun sha256Hex(bytes: ByteArray): String =
            MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }
    }
}
