#!/usr/bin/env bash
# Generates document-service-opa-bundle.yaml (the ConfigMap ArgoCD applies) from the
# REST authorization policy source of truth. The OPA sidecar serves
# data.openbank.rest.allow — the decision AuthorizeInterceptor (openbank-libs) queries
# for every @Authorize-annotated endpoint in document-service (ADR-0034 D5).
#
# rest.rego co-locates with agents.rego (a SINGLE sidecar serves both planes — see the
# header in rest.rego) and reads two data documents:
#   data.rules.*   ← rules.yaml   (money_path_services, four_eyes, feature_flags)
#   data.agents.*  ← agents.yaml  (charter lookup for the AI_AGENT branch)
# so the bundle ships all four sources. The mount layout the Deployment reproduces:
#   rest.rego        -> /bundle/rest.rego        (package openbank.rest)
#   agents.rego      -> /bundle/agents.rego      (package openbank.agents)
#   rules-data.yaml  -> /bundle/rules/data.yaml  (loads as data.rules.*)
#   agents-data.yaml -> /bundle/agents/data.yaml (loads as data.agents.*)
#   manifest.json    -> /bundle/.manifest
#
# Minimal/advisory shape (document-service is NOT in rules.yaml: money_path_services):
# unlike billing (which ships a billing_rest_ext.rego carve-out), this bundle has no
# document-service-specific extension rego — it relies on rest.rego's base allow
# reasons (operator-read-any, compliance-read-any, customer-self-action, etc.) until a
# document-domain-specific rule is actually needed. Mirrors notification-service's
# bundle (gen-notification-opa-bundle.sh), the fleet's other minimal-shape precedent.
#
# A checksum annotation rolls the Deployment when the policy changes (subPath mounts do
# not hot-reload). After editing any source below, re-run this script + commit.
set -euo pipefail
cd "$(dirname "$0")"

REST=../../../../openbank-libs/governance/policies/rest.rego
AGENTS=../../../opa/policies/agents.rego
RULES=../../../../openbank-libs/governance/rules-opa-data.yaml
AGENTS_DATA=../../../../openbank-libs/governance/agents.yaml
MANIFEST=../../../opa/bundle.manifest
OUT=document-service-opa-bundle.yaml

# Portable SHA-256: prefer sha256sum (Linux), fall back to shasum -a 256 (macOS).
CHECKSUM=$(cat "$REST" "$AGENTS" "$RULES" "$AGENTS_DATA" "$MANIFEST" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

{
  echo "# GENERATED by gen-document-service-opa-bundle.sh — do not hand-edit."
  echo "# Source: openbank-libs/governance/policies/rest.rego + opa/policies/agents.rego"
  echo "#         + openbank-libs/governance/rules-opa-data.yaml + agents.yaml + opa/bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: document-service-opa-bundle"
  echo "  namespace: documents"
  echo "  labels:"
  echo "    app.kubernetes.io/name: document-service"
  echo "    app.kubernetes.io/part-of: documents"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_DATA" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM, $(wc -c < "$OUT") bytes)"

# Sync the Deployment pod-roll annotation so a policy change always triggers a rollout.
DEPLOYMENT=document-service-service.yaml
if [ -f "$DEPLOYMENT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$DEPLOYMENT"
  rm -f "${DEPLOYMENT}.bak"
  echo "patched $DEPLOYMENT annotation → $CHECKSUM"
fi
