# Wealth domain (ADR-0037: domain = namespace). App plane. Holds wealth-service plus its
# single-owner CNPG Postgres. wealth-service owns the DeclaredHolding (ADR-0301) — an asset or
# liability the customer declares and the bank does NOT hold — and publishes its lifecycle onto
# openbank.wealth.events. Not money-path: it moves no money and posts nothing to the ledger.
apiVersion: v1
kind: Namespace
metadata:
  name: wealth
  labels:
    openbank.io/plane: app
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
