apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: context-service-oidc
  namespace: context
  annotations:
    openbank.io/rotation-deadline: "2027-09-13"
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vault-kv, kind: ClusterSecretStore }
  target: { name: context-service-oidc, creationPolicy: Owner }
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef: { key: account-service, property: OIDC_CLIENT_SECRET }
