#!/usr/bin/env bash
# Generates case-coordinator-opa-bundle.yaml (the ConfigMap ArgoCD applies) from the policy
# source of truth: agents.rego, the dedicated case-collaboration policy/data projection,
# the agents.yaml charter projection, and the bundle manifest
# (same shape as agent-service's gen-opa-bundle-configmap.sh). The bundle ships as one
# ConfigMap whose keys the case-coordinator-agent Deployment mounts back to the OPA bundle
# layout:
#   agents.rego        -> /bundle/agents.rego
#   agents-data.yaml   -> /bundle/agents/data.yaml   (loads as data.agents.*)
#   case-collaboration.rego -> /bundle/case-collaboration.rego
#   case-collaboration-data.yaml -> /bundle/case_collaboration/data.yaml
#   manifest.json      -> /bundle/.manifest
# A checksum annotation rolls the Deployment when the policy changes (subPath mounts
# do not hot-reload). After editing agents.rego or agents.yaml, re-run + commit.
set -euo pipefail
cd "$(dirname "$0")"

REGO=../../../opa/policies/agents.rego
DATA=../../../../openbank-libs/governance/agents-opa-data.yaml
CASE_REGO=../../../opa/policies/case_collaboration.rego
CASE_DATA=../../../../openbank-libs/governance/case-collaboration-opa-data.yaml
MANIFEST=bundle.manifest
OUT=case-coordinator-opa-bundle.yaml

# Portable SHA-256: prefer sha256sum (Linux), fall back to shasum -a 256 (macOS).
if command -v sha256sum >/dev/null 2>&1; then
  HASH_COMMAND=(sha256sum)
else
  HASH_COMMAND=(shasum -a 256)
fi
CHECKSUM=$(cat "$REGO" "$DATA" "$CASE_REGO" "$CASE_DATA" "$MANIFEST" | \
  "${HASH_COMMAND[@]}" | cut -c1-16)

{
  echo "# GENERATED by gen-case-coordinator-opa-bundle.sh — do not hand-edit."
  echo "# Source: agents.rego + case_collaboration.rego + their generated data projections + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: case-coordinator-opa-bundle"
  echo "  namespace: platform"
  echo "  labels:"
  echo "    app.kubernetes.io/name: case-coordinator-agent"
  echo "    app.kubernetes.io/part-of: platform"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  agents.rego: |"
  sed 's/^/    /' "$REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$DATA" | sed 's/[[:space:]]*$//'
  echo "  case-collaboration.rego: |"
  expand -t 4 "$CASE_REGO" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  case-collaboration-data.yaml: |"
  sed 's/^/    /' "$CASE_DATA" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM, $(wc -c < "$OUT") bytes)"

# Sync the Deployment pod-roll annotation so a policy change always triggers a rollout.
DEPLOYMENT=case-coordinator-service.yaml
if [ -f "$DEPLOYMENT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$DEPLOYMENT"
  rm -f "${DEPLOYMENT}.bak"
  echo "patched $DEPLOYMENT annotation → $CHECKSUM"
fi
