# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
# See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

quarkus:
  http:
    header:
      X-Content-Type-Options:
        value: nosniff
      X-Frame-Options:
        value: DENY
      X-XSS-Protection:
        value: "1; mode=block"
      Referrer-Policy:
        value: strict-origin-when-cross-origin
      Permissions-Policy:
        value: "geolocation=(), microphone=(), camera=()"
      Content-Security-Policy:
        value: "default-src 'self'"
      Strict-Transport-Security:
        value: "max-age=31536000; includeSubDomains"
  management:
    enabled: true
    port: 8085
    host: 0.0.0.0
    root-path: /q

"%test":
  quarkus:
    oidc:
      enabled: false
