// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

package com.openbank.devops.infrastructure.persistence

import com.openbank.devops.domain.model.DetectorId
import com.openbank.devops.domain.model.DoraMetric
import com.openbank.devops.domain.model.FindingSeverity
import com.openbank.devops.domain.model.FindingStatus
import com.openbank.devops.domain.model.RemediationKind
import io.quarkus.hibernate.reactive.panache.kotlin.PanacheCompanionBase
import io.quarkus.hibernate.reactive.panache.kotlin.PanacheEntityBase
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.math.BigDecimal
import java.time.Instant
import java.util.UUID

/**
 * Persisted DevOps finding (ADR-0119). Reactive Panache entity (the fleet standard). The id is
 * assigned in the domain (Ids.newId()), not generated by the DB.
 */
@Entity
@Table(name = "findings")
class FindingEntity : PanacheEntityBase {

    companion object : PanacheCompanionBase<FindingEntity, UUID>

    @Id
    @Column(columnDefinition = "uuid")
    lateinit var id: UUID

    @Column(name = "detector", nullable = false)
    @Enumerated(EnumType.STRING)
    lateinit var detector: DetectorId

    @Column(name = "severity", nullable = false)
    @Enumerated(EnumType.STRING)
    lateinit var severity: FindingSeverity

    @Column(name = "detected_at", nullable = false)
    lateinit var detectedAt: Instant

    @Column(name = "title", columnDefinition = "TEXT", nullable = false)
    lateinit var title: String

    @Column(name = "raw_metric_value", nullable = false)
    lateinit var rawMetricValue: BigDecimal

    @Column(name = "threshold", nullable = false)
    lateinit var threshold: BigDecimal

    @Column(name = "affected_resource", nullable = false)
    lateinit var affectedResource: String

    @Column(name = "dora_metric_impacted")
    @Enumerated(EnumType.STRING)
    var doraMetricImpacted: DoraMetric? = null

    @Column(name = "root_cause", columnDefinition = "TEXT")
    var rootCause: String? = null

    @Column(name = "remediation_kind", nullable = false)
    @Enumerated(EnumType.STRING)
    lateinit var remediationKind: RemediationKind

    @Column(name = "proposal_pr_url")
    var proposalPrUrl: String? = null

    @Column(name = "proposed_remediation", columnDefinition = "TEXT")
    var proposedRemediation: String? = null

    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    lateinit var status: FindingStatus

    @Column(name = "diagnosed_at")
    var diagnosedAt: Instant? = null

    @Column(name = "proposed_at")
    var proposedAt: Instant? = null
}
