#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# AnaCredit REST extension (ADR-0034 Phase 5 bootstrap, issue #938) — no OPA enforcement
# infrastructure existed for this service before this bootstrap.
ANACREDIT_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# AnaCredit-service REST extension (ADR-0034 Phase 5 bootstrap, issue #938).
# Extends openbank.rest with anacredit-domain allow reasons.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.
#
# Actions gated (AnaCreditResource):
#   anacredit.create  — registerExposure (feed a credit exposure in)
#   anacredit.list    — listAllExposures
#   anacredit.read    — renderReturn (#referenceDate)
#
# Base rest.rego already grants operator-read-any (ROLE_OPERATOR/ROLE_ADMIN) and
# compliance-read-any (ROLE_COMPLIANCE) for anacredit.list/.read — no extension needed for
# those. anacredit.create has no generic base-rego grant (it is a non-resource-scoped write),
# so this extension covers only that gap.
#
# No verified M2M caller exists for anacredit-service (audited: no REST client anywhere in the
# fleet calls it, no NetworkPolicy ingress allow-list beyond the shared platform baseline) — the
# exposure feed is fed in by an operator/compliance officer, not another service. Deliberately
# NOT granting a "service-*" M2M rule here, unlike consent/sca's shared-client carve-outs, since
# there is nothing to carve out for.

package openbank.rest

import rego.v1

allowed_reasons contains "operator-anacredit-create" if {
	input.principal.type == "HUMAN"
	some role in {"ROLE_OPERATOR", "ROLE_ADMIN"}
	role in input.principal.roles
	input.action == "anacredit.create"
}
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$ANACREDIT_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/anacredit/anacredit-opa-bundle.yaml

{
  echo "# GENERATED by gen-anacredit-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + anacredit_rest_ext.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: anacredit-opa-bundle"
  echo "  namespace: anacredit"
  echo "  labels:"
  echo "    app.kubernetes.io/name: anacredit-service"
  echo "    app.kubernetes.io/part-of: anacredit"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  anacredit_rest_ext.rego: |"
  echo "$ANACREDIT_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-consent-opa-bundle.sh).
ROLLOUT=$REPO/openbank-infra/gitops/components/anacredit/anacredit-service.yaml
if [ -f "$ROLLOUT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$ROLLOUT"
  rm -f "${ROLLOUT}.bak"
  echo "patched $ROLLOUT annotation → $CHECKSUM"
fi
