// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

package com.openbank.sanctions.contract

import au.com.dius.pact.provider.junit5.HttpTestTarget
import au.com.dius.pact.provider.junit5.PactVerificationContext
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider
import au.com.dius.pact.provider.junitsupport.IgnoreNoPactsToVerify
import au.com.dius.pact.provider.junitsupport.Provider
import au.com.dius.pact.provider.junitsupport.State
import au.com.dius.pact.provider.junitsupport.loader.PactFolder
import com.openbank.sanctions.it.PostgresTestResource
import io.quarkus.test.common.QuarkusTestResource
import io.quarkus.test.junit.QuarkusTest
import io.quarkus.test.security.TestSecurity
import org.eclipse.microprofile.config.inject.ConfigProperty
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.TestTemplate
import org.junit.jupiter.api.extension.ExtendWith

/**
 * Provider-side Pact verification for sanctions-service — its FIRST contract coverage of any kind
 * (issue #2255, dimension C3). An `openapi.yaml` existed and **seven** services hold a
 * `@RegisterRestClient(configKey = "sanctions-service")`, but nothing replayed a consumer contract.
 * It only looked covered: the pre-#2291 scorer matched the bare word "contract" anywhere under
 * `src/test`, including comments.
 *
 * Reads the consumer pacts from the git-pact folder (`@PactFolder`, resolved relative to this
 * module's working directory at `../pacts` = the monorepo-root `pacts/` dir) and replays every
 * interaction whose provider is `openbank-sanctions-service` against the running Quarkus test
 * instance. This always runs — no broker, no gate, no CI secret (ADR-0063 chose git-pact over a Pact
 * Broker for exactly this reason: zero new infra dependency).
 *
 * Verified today: `openbank-fx-service` -> `POST /api/v1/sanctions/screen`, two interactions
 * (CLEAR and HIT) generated by `SanctionsScreenPactConsumerTest` in openbank-fx-service. If that
 * test's contract changes, regenerate the pact JSON (`./gradlew :openbank-fx-service:test --tests
 * "*SanctionsScreenPactConsumerTest*"`) and commit
 * `pacts/openbank-fx-service-openbank-sanctions-service.json` in the same PR, or this test verifies
 * a stale contract.
 *
 * **This must remain the ONLY `@Provider("openbank-sanctions-service")` class in the repo.** Two
 * classes sharing a provider name both pull every pact for that provider and collide (ADR-0029 D3);
 * a further interaction type belongs in the `@BeforeEach` target selection here, or in a new
 * `@State` handler, not in a new class.
 *
 * `@IgnoreNoPactsToVerify(ignoreIoErrors)` makes a missing/unreadable pact file a skip rather than a
 * failure — relevant if the folder is ever emptied ahead of a broker migration.
 *
 * Authentication: `POST /api/v1/sanctions/screen` is
 * `@RolesAllowed("ROLE_OPERATOR", "ROLE_ADMIN", "ROLE_API")`. `@TestSecurity` cannot annotate a
 * `@TestTemplate` method, so it is applied at class level and Pact replays every interaction as that
 * principal. The endpoint additionally carries `@Authorize(action = "sanctions.create")`; with
 * `authz.enforce` at its production default of `true` and no OPA sidecar in a test JVM the
 * interceptor fails **closed** with a 503 (`AuthorizeInterceptor`, ADR-0034), so this service's
 * `%test` profile now pins `authz.enforce: "false"` exactly as aml-service's does. That toggle is a
 * test-profile-only change; it does not weaken the deployed default.
 */
@QuarkusTest
@QuarkusTestResource(PostgresTestResource::class)
@TestSecurity(user = "pact-verifier", roles = ["ROLE_OPERATOR"])
@Provider("openbank-sanctions-service")
@PactFolder("../pacts")
@IgnoreNoPactsToVerify(ignoreIoErrors = "true")
class SanctionsPactProviderVerificationTest {

    @ConfigProperty(name = "quarkus.http.test-port", defaultValue = "8081")
    lateinit var testPort: String

    @BeforeEach
    fun configureTarget(context: PactVerificationContext?) {
        context?.target = HttpTestTarget("localhost", testPort.toInt())
        context?.addStateChangeHandlers(this)
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider::class)
    fun verifyPacts(context: PactVerificationContext?) {
        context?.verifyInteraction()
    }

    /**
     * State: "the sanctions lists are seeded and carry no entry for the screened name".
     *
     * Nothing to do, and nothing *should* be done here. The seed is a Flyway migration
     * (`V6__seed_sanctions_entries.sql`) with `migrate-at-start: true`, so the fresh Testcontainer
     * Postgres already holds every OFAC/EU/UN/HM-Treasury/PEP/CNB entry before the first request —
     * the state this handler names is boot state, not something a handler creates. That is the whole
     * reason both consumer interactions were written against seeded data: writing a row from here is
     * not possible without tripping the documented HR000068 trap (this service's repositories are
     * reactive — `PgPool` / reactive Panache — and a plain JUnit state-change callback carries no
     * Vert.x context).
     *
     * The name the consumer sends shares no trigram token with any seeded `search_text`, so the
     * `word_similarity() >= 0.85` query returns nothing and `SanctionsService.performScreening`
     * answers `CLEAR` with an empty `matches` list and `overallScore = 0.0`.
     *
     * Re-running against a warm container is safe: `screen` is idempotent on `idempotencyKey`, so the
     * second replay returns the identical persisted `SanctionsCheck` rather than re-screening.
     */
    @State("the sanctions lists are seeded and carry no entry for the screened name")
    fun stateNoSeededEntryMatchesTheName() {
        // Intentionally empty — see the KDoc above.
    }

    /**
     * State: "the sanctions lists are seeded with the boot-time OFAC/EU/UN/PEP entries".
     *
     * Also boot state, for the same reason — `V6` seeds `Vladimir Putin` on four lists, so the
     * consumer's HIT interaction is satisfied by the migration alone. Kept as a *separate* named
     * state rather than reusing the one above because the two interactions assert opposite outcomes:
     * a single shared state name would leave a reader unable to tell which precondition each
     * interaction depends on, and would quietly keep passing if the seed lost its sanctioned entries.
     */
    @State("the sanctions lists are seeded with the boot-time OFAC/EU/UN/PEP entries")
    fun stateSeededSanctionsEntriesExist() {
        // Intentionally empty — see the KDoc above.
    }
}
