#!/usr/bin/env bash
# Generates mcp-opa-bundle.yaml (the ConfigMap ArgoCD applies) for openbank-mcp-service
# (ADR-0181 phase 2). The MCP server authorizes tools/call through the SHARED ADR-0034 PDP —
# it queries data.openbank.rest.allow, which bridges an AI_AGENT capability to the
# mcp-anonymous charter in agents.rego. So this bundle embeds the full shared policy set
# (rest.rego + agents.rego + agents.yaml + rules.yaml + manifest), same as a standard service;
# unlike agent-service it needs no service-local REST extension (the MCP capabilities are
# charter-matched directly, not mapped through rest_domains).
#
# A checksum annotation rolls the Deployment when the policy changes (subPath mounts do not
# hot-reload). After editing any embedded source, re-run + commit. Editing the shared sources
# (agents.yaml / rules.yaml / rest.rego / agents.rego) restamps EVERY service's bundle —
# regenerate them all: find openbank-infra/gitops/components -name 'gen-*opa-bundle*.sh' | sort | xargs -n1 bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Portable SHA-256: prefer sha256sum (Linux), fall back to shasum -a 256 (macOS).
CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/mcp/mcp-opa-bundle.yaml

{
  echo "# GENERATED by gen-mcp-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + agents.rego + agents.yaml + rules.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: mcp-opa-bundle"
  echo "  namespace: platform"
  echo "  labels:"
  echo "    app.kubernetes.io/name: mcp-service"
  echo "    app.kubernetes.io/part-of: platform"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Deployment pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload).
DEPLOYMENT=$REPO/openbank-infra/gitops/components/mcp/mcp-service.yaml
if [ -f "$DEPLOYMENT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$DEPLOYMENT"
  rm -f "${DEPLOYMENT}.bak"
  echo "patched $DEPLOYMENT annotation → $CHECKSUM"
fi
