apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pricing-console-auth
  namespace: pricing
  annotations:
    openbank.io/rotation-deadline: "2027-09-21"
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: pricing-console
      metadataPolicy: None
      property: session-secret
    secretKey: session-secret
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: pricing-console
      metadataPolicy: None
      property: oidc-client-secret
    secretKey: oidc-client-secret
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: pricing-console
      metadataPolicy: None
      property: admin-subject
    secretKey: admin-subject
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pricing-console-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pricing-service-oidc
  namespace: pricing
  annotations:
    openbank.io/rotation-deadline: "2027-09-21"
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: pricing-service
      metadataPolicy: None
      property: OIDC_CLIENT_SECRET
    secretKey: OIDC_CLIENT_SECRET
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pricing-service-oidc
