#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents-opa-data.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Second treasury-service deployment (ADR-0337 amendment): the bank treasury's extension (staff
# portfolio rules) plus treasury_pension_co_rest_ext.rego, which prohibits every non-portfolio
# action and every service-account except tax-reporting's portfolio read.
TREASURY_REST_EXT=$REPO/openbank-infra/gitops/components/treasury/treasury_rest_ext.rego
PCO_REST_EXT=$REPO/openbank-infra/gitops/components/treasury-pension-co/treasury_pension_co_rest_ext.rego

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$TREASURY_REST_EXT")" \
    "$(cat "$PCO_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/treasury-pension-co/treasury-pension-co-opa-bundle.yaml

{
  echo "# GENERATED by gen-treasury-pension-co-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + treasury_rest_ext.rego + treasury_pension_co_rest_ext.rego + agents.rego + agents-opa-data.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: treasury-pension-co-opa-bundle"
  echo "  namespace: treasury-pension-co"
  echo "  labels:"
  echo "    app.kubernetes.io/name: treasury-service"
  echo "    app.kubernetes.io/part-of: treasury-pension-co"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  treasury_rest_ext.rego: |"
  sed 's/^/    /' "$TREASURY_REST_EXT" | sed 's/[[:space:]]*$//'
  echo "  treasury_pension_co_rest_ext.rego: |"
  sed 's/^/    /' "$PCO_REST_EXT" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-sca-opa-bundle.sh).
ROLLOUT=$REPO/openbank-infra/gitops/components/treasury-pension-co/treasury-service.yaml
if [ -f "$ROLLOUT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$ROLLOUT"
  rm -f "${ROLLOUT}.bak"
  echo "patched $ROLLOUT annotation → $CHECKSUM"
fi
