# SPDX-License-Identifier: Apache-2.0
# The workload mounts only ca.crt to verify Context's DNS-bound TLS certificate.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fraud-context-trust
  namespace: fraud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: fraud-context-trust
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - fraud-service.fraud.svc
  issuerRef:
    name: openbank-ca
    kind: ClusterIssuer
    group: cert-manager.io
