#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
KYB_REST_EXT=$REPO/openbank-infra/gitops/components/kyb/kyb_rest_ext.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents-opa-data.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Standalone kyb_rest_ext.rego (matches delegation/consent/kyc), so `opa test` can load it
# directly rather than a heredoc trapped inside this script — kyb_rest_ext_test.rego needs
# a real file.
CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$KYB_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/kyb/kyb-opa-bundle.yaml

{
  echo "# GENERATED by gen-kyb-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + kyb_rest_ext.rego + agents.rego + agents-opa-data.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: kyb-opa-bundle"
  echo "  namespace: kyb"
  echo "  labels:"
  echo "    app.kubernetes.io/name: kyb-service"
  echo "    app.kubernetes.io/part-of: kyb"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  kyb_rest_ext.rego: |"
  sed 's/^/    /' "$KYB_REST_EXT" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout (subPath
# mounts do NOT hot-reload). The workload manifest lands with the gitops component (issue #2992);
# until then there is nothing to patch and this is a no-op.
ROLLOUT=$REPO/openbank-infra/gitops/components/kyb/kyb-service.yaml
if [ -f "$ROLLOUT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$ROLLOUT"
  rm -f "${ROLLOUT}.bak"
  echo "patched $ROLLOUT annotation → $CHECKSUM"
fi
