#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
SDD_REST_EXT=$REPO/openbank-infra/gitops/components/sdd/sdd_rest_ext.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Standalone sdd_rest_ext.rego (matches consent/kyc/psd2/aml/delegation), so `opa test` can load it
# directly rather than a heredoc trapped inside this script — sdd_rest_ext_test.rego needs a real
# file.
CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$SDD_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/sdd/sdd-opa-bundle.yaml

{
  echo "# GENERATED by gen-sdd-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + sdd_rest_ext.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: sdd-opa-bundle"
  echo "  namespace: sdd"
  echo "  labels:"
  echo "    app.kubernetes.io/name: sdd-service"
  echo "    app.kubernetes.io/part-of: sdd"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  sdd_rest_ext.rego: |"
  sed 's/^/    /' "$SDD_REST_EXT" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the workload pod-roll annotation so a policy change always triggers a rollout (subPath
# mounts do NOT hot-reload).
WORKLOAD=$REPO/openbank-infra/gitops/components/sdd/sdd-service.yaml
if [ -f "$WORKLOAD" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$WORKLOAD"
  rm -f "${WORKLOAD}.bak"
  echo "patched $WORKLOAD annotation → $CHECKSUM"
fi
