#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# sdd-service REST extension (ADR-0034 Phase 5, issue #3679) — OPA enforcement for the
# SEPA Direct Debit mandate lifecycle service (money-path, #1478).
# The base rest.rego matrix_grants already covers all seven sdd.* actions via the
# role_action_matrix (ROLE_OPERATOR/ROLE_ADMIN: all sdd.*; ROLE_COMPLIANCE: sdd.read).
# No additional extension rule is needed: every action the matrix grants is reachable
# through operator-read-any + matrix_grants in rest.rego alone.
# This file exists to mount the policy bundle into the OPA sidecar — even without a
# service-specific ext.rego, the bundle must be present so the sidecar can serve
# data.openbank.rest.allow for @Authorize-annotated endpoints.

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/sdd/sdd-opa-bundle.yaml

{
  echo "# GENERATED by gen-sdd-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: sdd-opa-bundle"
  echo "  namespace: sdd"
  echo "  labels:"
  echo "    app.kubernetes.io/name: sdd-service"
  echo "    app.kubernetes.io/part-of: sdd"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

ROLLOUT=$REPO/openbank-infra/gitops/components/sdd/sdd-service.yaml
if [ -f "$ROLLOUT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$ROLLOUT"
  rm -f "${ROLLOUT}.bak"
  echo "patched $ROLLOUT annotation → $CHECKSUM"
fi
