// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

package com.openbank.risk.domain

import com.openbank.libs.domain.money.Money
import com.openbank.libs.lending.Amortization
import com.openbank.libs.lending.AmortizationMethod
import com.openbank.risk.domain.model.LedgerInputs
import com.openbank.risk.domain.model.LoanContract
import com.openbank.risk.domain.model.ScheduledInstallment
import com.openbank.risk.domain.model.SubLedgerBalance
import com.openbank.risk.domain.model.TrialBalanceLine
import java.math.BigDecimal
import java.time.LocalDate
import java.util.UUID

object Fixtures {
    val AS_OF: LocalDate = LocalDate.parse("2026-09-30")
    val ALICE: UUID = UUID.fromString("00000000-0000-7000-8000-000000000001")
    val BOB: UUID = UUID.fromString("00000000-0000-7000-8000-000000000002")

    /** Trial-balance line in the ledger convention: net = debit − credit. */
    fun tb(code: String, type: String, currency: String, debit: String, credit: String) = TrialBalanceLine(
        glAccountCode = code,
        glAccountType = type,
        currency = currency,
        totalDebit = BigDecimal(debit),
        totalCredit = BigDecimal(credit),
        net = BigDecimal(debit).subtract(BigDecimal(credit)),
    )

    fun sl(id: UUID, currency: String, debit: String, credit: String) =
        SubLedgerBalance(id, currency, BigDecimal(debit), BigDecimal(credit))

    /**
     * A balanced little bank: nostro 1001 holds 1500 CZK, customers Alice (1000) and Bob (500)
     * hold it on deposit control 2100. The two customer credits sum to the control account.
     */
    fun tiedOut(): LedgerInputs = LedgerInputs(
        asOf = AS_OF,
        trialBalance = listOf(
            tb("1001", "ASSET", "CZK", "1500.00", "0"),
            tb("2100", "LIABILITY", "CZK", "0", "1500.00"),
        ),
        subLedger = listOf(
            sl(ALICE, "CZK", "0", "1000.00"),
            sl(BOB, "CZK", "0", "500.00"),
        ),
    )

    val LOAN_A: UUID = UUID.fromString("00000000-0000-7000-8000-00000000000a")
    val LOAN_B: UUID = UUID.fromString("00000000-0000-7000-8000-00000000000b")

    /**
     * A loan exactly as lending would report it at [AS_OF]: its full schedule is generated by libs
     * `Amortization` — the very function lending books a loan with — and the first [paid]
     * installments are dropped, so the remaining installments and the outstanding are lending's.
     */
    fun lendingLoan(
        id: UUID = LOAN_A,
        principal: String = "12000.00",
        currency: String = "CZK",
        rate: String = "0.06",
        term: Int = 12,
        paid: Int = 6,
        method: AmortizationMethod = AmortizationMethod.ANNUITY,
        firstDue: LocalDate = LocalDate.parse("2026-04-15"),
        glAccountCode: String? = "1200",
        floating: Triple<String, String, Int>? = null,
        nextResetDate: LocalDate? = null,
    ): LoanContract {
        val schedule = Amortization.schedule(
            Money.of(BigDecimal(principal), currency),
            BigDecimal(rate),
            term,
            firstDue,
            12,
            method,
        )
        val remaining = schedule.installments.drop(paid).map {
            ScheduledInstallment(it.number, it.dueDate, it.principal.amount, it.interest.amount)
        }
        return LoanContract(
            loanId = id,
            counterpartyRef = ALICE,
            status = "ACTIVE",
            currency = currency,
            glAccountCode = glAccountCode,
            outstandingPrincipal = remaining.fold(BigDecimal.ZERO.setScale(2)) { acc, i -> acc.add(i.principal) },
            nominalAnnualRate = BigDecimal(rate),
            rateType = if (floating == null) "FIXED" else "FLOATING",
            rateIndex = floating?.first,
            spread = floating?.second?.let(::BigDecimal),
            resetFrequencyMonths = floating?.third,
            nextResetDate = nextResetDate,
            method = method.name,
            periodsPerYear = 12,
            disbursedOn = firstDue.minusMonths(1),
            maturityDate = schedule.installments.last().dueDate,
            ifrs9Stage = "STAGE_1",
            remainingInstallments = remaining,
        )
    }

    /** [tiedOut] plus loans on Loans Receivable 1200 (CZK) whose debit equals [loanTotal], funded from nostro. */
    fun tiedOutWithLoans(loanTotal: BigDecimal): LedgerInputs {
        val base = tiedOut()
        return base.copy(
            trialBalance = base.trialBalance + tb("1200", "ASSET", "CZK", loanTotal.toPlainString(), "0") +
                tb("3000", "EQUITY", "CZK", "0", loanTotal.toPlainString()),
        )
    }
}
