#!/usr/bin/env bash
# Generates agent-opa-bundle.yaml (the ConfigMap ArgoCD applies) from the policy
# source of truth: the OPA Rego + the agents.yaml charter + the bundle manifest.
# ArgoCD's directory source applies only *.yaml, so the bundle ships as one ConfigMap
# whose keys the agent-service Deployment mounts back to the OPA bundle layout
# (mirrors openbank-infra/opa/build-bundle.sh and the local docker-compose opa mount):
#   agents.rego        -> /bundle/agents.rego
#   agents-data.yaml   -> /bundle/agents/data.yaml   (loads as data.agents.*)
#   manifest.json      -> /bundle/.manifest
# A checksum annotation rolls the Deployment when the policy changes (subPath mounts
# do not hot-reload). After editing agents.rego or agents.yaml, re-run + commit.
set -euo pipefail
cd "$(dirname "$0")"

REGO=../../../opa/policies/agents.rego
DATA=../../../../openbank-libs/governance/agents-opa-data.yaml
MANIFEST=../../../opa/bundle.manifest
OUT=agent-opa-bundle.yaml

# Portable SHA-256: prefer sha256sum (Linux), fall back to shasum -a 256 (macOS).
CHECKSUM=$(cat "$REGO" "$DATA" "$MANIFEST" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

{
  echo "# GENERATED by gen-opa-bundle-configmap.sh — do not hand-edit."
  echo "# Source: opa/policies/agents.rego + openbank-libs/governance/agents-opa-data.yaml + opa/bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: agent-opa-bundle"
  echo "  namespace: platform"
  echo "  labels:"
  echo "    app.kubernetes.io/name: agent-service"
  echo "    app.kubernetes.io/part-of: platform"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  agents.rego: |"
  sed 's/^/    /' "$REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$DATA" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM, $(wc -c < "$OUT") bytes)"

# Sync the Deployment pod-roll annotation so a policy change always triggers a rollout.
DEPLOYMENT=agent-service.yaml
if [ -f "$DEPLOYMENT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$DEPLOYMENT"
  rm -f "${DEPLOYMENT}.bak"
  echo "patched $DEPLOYMENT annotation → $CHECKSUM"
fi
