apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onboarding-service-oidc
  namespace: onboarding
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: onboarding-service-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: account-service
        property: OIDC_CLIENT_SECRET
