#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Card-issuance REST extension (ADR-0034 Phase 5 bootstrap, issue #938) — no OPA enforcement
# infrastructure existed for this service before this bootstrap. card-issuance-service deploys
# into the shared `payments` namespace/ArgoCD app (payments-services.yaml), not its own — this
# generator lives alongside that manifest for the same reason the other payments/* bundles do.
CARD_ISSUANCE_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# Card-issuance-service REST extension (ADR-0034 Phase 5 bootstrap, issue #938).
# Extends openbank.rest with card-domain allow reasons.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.
#
# Actions gated (CardResource):
#   card.create    — issueCard
#   card.list      — listAll, listByAccount (#accountId), listByParty (#partyId)
#   card.read      — getCard (#id)
#   card.activate  — activate (#id)
#   card.block     — block (#id) — also ROLE_COMPLIANCE at the Jakarta layer
#   card.suspend   — suspend (#id) — customer-edge calls this on a customer's OWN card
#                    (self-service freeze, /customer/v1/cards/{id}/freeze)
#   card.resume    — resume (#id) — same, customer self-service unfreeze
#
# Base rest.rego already grants operator-read-any (ROLE_OPERATOR/ROLE_ADMIN) for card.list/.read
# — no extension needed for those. The remaining actions have no generic base-rego grant.
#
# Verified caller: customer-edge calls card.list/card.suspend/card.resume on the customer's own
# card via the shared `openbank-services` Keycloak client (service-account-openbank-services,
# whose realmRoles include ROLE_OPERATOR) — see CustomerEdgeResource.kt cardAction(). Per the
# documented fleet-wide limitation (rules.yaml authz_policy.principal_type_service_unreachable),
# AuthorizeInterceptor cannot distinguish this M2M caller from a real human operator holding
# ROLE_OPERATOR, so granting the role necessarily covers both — same stance as consent-service's
# service-consent-m2m rule.

package openbank.rest

import rego.v1

# Operators/admins may create, activate, suspend, or resume a card. Card.block is deliberately
# excluded here — it additionally requires ROLE_COMPLIANCE at the Jakarta layer, gated below.
allowed_reasons contains "operator-card-write" if {
	input.principal.type == "HUMAN"
	some role in {"ROLE_OPERATOR", "ROLE_ADMIN"}
	role in input.principal.roles
	input.action in {"card.create", "card.activate", "card.suspend", "card.resume"}
}

# Blocking a card (fraud/compliance hold) is also grantable to ROLE_COMPLIANCE, matching
# CardResource's @RolesAllowed("ROLE_OPERATOR", "ROLE_ADMIN", "ROLE_COMPLIANCE") on block().
allowed_reasons contains "compliance-card-block" if {
	input.principal.type == "HUMAN"
	"ROLE_COMPLIANCE" in input.principal.roles
	input.action == "card.block"
}
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$CARD_ISSUANCE_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/card-issuance-opa-bundle.yaml

{
  echo "# GENERATED by gen-card-issuance-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + card_issuance_rest_ext.rego + agents.rego + agents.yaml + rules.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: card-issuance-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: card-issuance-service"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  card_issuance_rest_ext.rego: |"
  echo "$CARD_ISSUANCE_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# The checksum annotation for card-issuance-service's pod template lives inline inside the
# combined payments-services.yaml manifest — patched by hand below (a blind sed across the
# whole multi-service file would risk touching another service's identical placeholder).
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
echo "NOTE: update the card-issuance-service pod template annotation in $ROLLOUT to \"$CHECKSUM\" (not auto-patched — shared multi-service file)."
