#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# SEPA-instant REST extension — payment-rail allow reasons (ADR-0034 Phase 5, issue #266)
SEPA_INSTANT_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# Sepa-instant REST extension (ADR-0034 Phase 5, issue #266).
# Extends openbank.rest with SCT Inst (sepa-instant)-domain allow reasons.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.
#
# Actions gated (SctInstResource). NOTE: the real action prefix is `sctInstPayment`,
# not `sepa-instant` — confirmed from source (SctInstResource.kt), the existing
# `sctInstPayment.recall` annotation predates this change. `money_path_scopes` in the
# base rest.rego derives "sepa-instant" from the module name openbank-sepa-instant, so
# it does NOT match this prefix and four_eyes_required never fires for this rail today
# (recall isn't in the four_eyes verb list either). That mismatch is a fleet-wide
# concern tracked separately (issue #395 / PR #396) — out of scope here; this extension
# only adds the missing allow reasons under the prefix actually used in code.
#   sctInstPayment.create — submit a new SCT Inst payment (POST /)
#   sctInstPayment.read   — get payment by id (#paymentId)
#   sctInstPayment.list   — list all / list-by-debtor-account
#   sctInstPayment.recall — recall a settled payment (#paymentId) — already covered by
#                           the base operator-on-own-tenant rule; no extension needed.
#
# Base rest.rego already grants: operator-read-any / compliance-read-any for *.read +
# *.list, and operator-on-own-tenant (resource-scoped) for *.recall. Only *.create has
# no base coverage — that's the one gap this extension fills.

package openbank.rest

import rego.v1

# Operators, admins and the payments desk (ROLE_PAYMENTS, declared in the resource's own
# @RolesAllowed) may submit a new SCT Inst payment. The admin-ui payments console
# initiates with the signed-in operator's OWN bearer token (BFF pattern, ADR-0080 P1).
# This money-path rail's four-eyes / canary controls are independent platform
# safeguards; approval logic lives in the handlers, never in this policy.
allowed_reasons contains "operator-sepa-instant-write" if {
	input.principal.type == "HUMAN"
	some role in {"ROLE_OPERATOR", "ROLE_ADMIN", "ROLE_PAYMENTS"}
	role in input.principal.roles
	input.action == "sctInstPayment.create"
}

# No SERVICE (M2M) allow reason: at the time of writing, there is NO in-repo caller of
# any SctInstResource endpoint (grep across gitops/components and every service's
# src for SEPA_INSTANT_URL / sctInst / sepa-instant.payments.svc client code found none
# — @RolesAllowed already admits ROLE_SERVICE on listAll/listByDebtor at the RBAC layer,
# but that predates any real caller). Deliberately NOT granting a blanket SERVICE allow
# here without verified caller evidence (ADR-0034 Phase 5 safety rule) — if/when a real
# M2M caller (e.g. customer-edge for initiate, or clearing-service/clearing-simulator for
# an inbound return-equivalent flow) is wired up, add a narrowly-scoped SERVICE rule
# mirroring gen-sepa-payment-opa-bundle.sh's service-sepa-payment-m2m pattern — scoped to
# exactly the verified actions, never every sctInstPayment.* action.
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$SEPA_INSTANT_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/sepa-instant-opa-bundle.yaml

{
  echo "# GENERATED by gen-sepa-instant-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + sepa_instant_rest_ext.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: sepa-instant-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: sepa-instant"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  sepa_instant_rest_ext.rego: |"
  echo "$SEPA_INSTANT_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-sca-opa-bundle.sh). The
# payments component hosts SEVERAL workloads in one file, so the substitution is
# scoped to the sepa-instant Rollout document only — a blanket sed would stomp the
# checksum of any sibling workload's own bundle (e.g. sepa-payment's, if/when it lands).
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
if [ -f "$ROLLOUT" ]; then
  CHECKSUM="$CHECKSUM" ROLLOUT="$ROLLOUT" python3 - << 'PY'
import os, re, sys

path = os.environ["ROLLOUT"]
checksum = os.environ["CHECKSUM"]
text = open(path).read()

docs = text.split("\n---\n")
patched = 0
for i, doc in enumerate(docs):
    if re.search(r"^kind: Rollout$", doc, re.M) and re.search(r"^  name: sepa-instant$", doc, re.M):
        if 'openbank.tech/policy-checksum: "' in doc:
            new, n = re.subn(
                r'(openbank\.tech/policy-checksum: ")[^"]*(")',
                rf"\g<1>{checksum}\g<2>",
                doc,
            )
        else:
            new, n = re.subn(
                r'(  labels:\n(?:.*\n)*?    app\.kubernetes\.io/part-of: payments\n)',
                lambda m: m.group(1) + (
                    "  annotations:\n"
                    "    # Rolls the pods when the OPA bundle changes — subPath mounts do NOT hot-reload.\n"
                    "    # Kept in sync by gen-sepa-instant-opa-bundle.sh (do not hand-edit).\n"
                    f'    openbank.tech/policy-checksum: "{checksum}"\n'
                ),
                doc,
                count=1,
            )
        if n == 0:
            sys.exit("sepa-instant Rollout found but could not stamp policy-checksum annotation")
        docs[i] = new
        patched += n

if patched == 0:
    sys.exit("sepa-instant Rollout not found in payments-services.yaml")
open(path, "w").write("\n---\n".join(docs))
PY
  echo "patched $ROLLOUT (sepa-instant Rollout) annotation → $CHECKSUM"
fi
