#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# SEPA-payment REST extension — payment-rail allow reasons (ADR-0034 Phase 5, issue #266)
SEPA_PAYMENT_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# Sepa-payment REST extension (ADR-0034 Phase 5, issue #266).
# Extends openbank.rest with SEPA-payment-domain allow reasons.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.
#
# Actions gated (SepaPaymentResource):
#   sepaPayment.create           — create a SEPA credit transfer (POST /)
#   sepaPayment.read             — get payment by id (#paymentId)
#   sepaPayment.list             — list payments
#   sepaPayment.transitionStatus — ops status transition (#paymentId, PATCH /{id}/status)
#   sepaPayment.handleReturn     — inbound pacs.004 return from clearing (POST /returns)
#
# Base rest.rego already grants: operator-read-any / compliance-read-any for
# *.read + *.list. Everything else on this rail needs an explicit reason below.

package openbank.rest

import rego.v1

# Operators, admins and the payments desk (ROLE_PAYMENTS, declared in the resource's own
# @RolesAllowed) may perform ANY sepaPayment lifecycle operation. The admin-ui payments
# console initiates and lists SEPA transfers with the signed-in operator's OWN bearer
# token (BFF /api/sepa-payments — ADR-0080 P1), and resolves stuck payments via the
# status transition — so the human operator path stays first-class. Initiation and
# transition on this money-path rail remain subject to the platform's four-eyes and
# canary controls; approval logic itself lives in the handlers, never in this policy.
allowed_reasons contains "operator-sepa-payment-write" if {
	input.principal.type == "HUMAN"
	some role in {"ROLE_OPERATOR", "ROLE_ADMIN", "ROLE_PAYMENTS"}
	role in input.principal.roles
	startswith(input.action, "sepaPayment.")
}

# M2M callers on the SEPA rail (all verified in-repo):
#   - customer-edge (UpstreamClient, client_credentials SERVICE token): initiates a SEPA
#     credit transfer for the authenticated customer AFTER the edge's own ownership
#     (IDOR) guard + SCA gate (scaGate runs before every money-path forward, ADR-0021),
#     and polls the payment status (read) for the settlement-honest success screen
#     (ADR-0108).
#   - clearing-simulator (SepaPaymentClient, oidc-client SERVICE token): submits the
#     inbound pacs.004 payment return (sepaPayment.handleReturn) — mirrors the
#     endpoint's own @RolesAllowed(ROLE_SERVICE).
# Deliberately narrow: sepaPayment.transitionStatus has NO in-repo M2M caller (its
# @RolesAllowed does not even admit ROLE_SERVICE) and stays human-only; sepaPayment.list
# has no M2M caller either (admin-ui lists with the operator's own token). A blanket
# SERVICE allow would open every @Authorize endpoint on a payment rail to any M2M client.
#
# NOTE (found post-merge, issue tracked separately): AuthorizeInterceptor never
# emits principal.type == "SERVICE" — M2M callers authenticate via Keycloak
# client_credentials JWTs, which the interceptor classifies as HUMAN. Split into
# two rules since the two callers use different Keycloak clients:
#   - customer-edge has its own dedicated client, identity
#     `service-account-openbank-edge`.
#   - clearing-simulator shares the `openbank-services` client (like nearly every
#     other backend service), identity `service-account-openbank-services` —
#     not unique to clearing-simulator, documented inline.
allowed_reasons contains "service-sepa-payment-edge-m2m" if {
	input.principal.type == "HUMAN"
	input.principal.id == "service-account-openbank-edge"
	input.action in {
		"sepaPayment.create",
		"sepaPayment.read",
	}
}

allowed_reasons contains "service-sepa-payment-shared-client-m2m" if {
	input.principal.type == "HUMAN"
	input.principal.id == "service-account-openbank-services"
	input.action == "sepaPayment.handleReturn"
}
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$SEPA_PAYMENT_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/sepa-payment-opa-bundle.yaml

{
  echo "# GENERATED by gen-sepa-payment-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + sepa_payment_rest_ext.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: sepa-payment-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: sepa-payment"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  sepa_payment_rest_ext.rego: |"
  echo "$SEPA_PAYMENT_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-sca-opa-bundle.sh). The
# payments component hosts SEVERAL workloads in one file, so the substitution is
# scoped to the sepa-payment Rollout document only — a blanket sed would stomp the
# checksum of any sibling workload that later gets its own bundle.
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
if [ -f "$ROLLOUT" ]; then
  CHECKSUM="$CHECKSUM" ROLLOUT="$ROLLOUT" python3 - << 'PY'
import os, re, sys

path = os.environ["ROLLOUT"]
checksum = os.environ["CHECKSUM"]
text = open(path).read()

docs = text.split("\n---\n")
patched = 0
for i, doc in enumerate(docs):
    if re.search(r"^kind: Rollout$", doc, re.M) and re.search(r"^  name: sepa-payment$", doc, re.M):
        new, n = re.subn(
            r'(openbank\.tech/policy-checksum: ")[^"]*(")',
            rf"\g<1>{checksum}\g<2>",
            doc,
        )
        if n == 0:
            sys.exit("sepa-payment Rollout found but no policy-checksum annotation to stamp")
        docs[i] = new
        patched += n

if patched == 0:
    sys.exit("sepa-payment Rollout not found in payments-services.yaml")
open(path, "w").write("\n---\n".join(docs))
PY
  echo "patched $ROLLOUT (sepa-payment Rollout) annotation → $CHECKSUM"
fi
