#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents-opa-data.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# SEPA-instant REST extension — payment-rail allow reasons (ADR-0034 Phase 5, issue #266)
# Extracted from an inline heredoc into its own file (#10486 batch 7) so a
# sepa_instant_rest_ext_test.rego beside it runs in CI's per-service rest_ext suite.
SEPA_INSTANT_REST_EXT=$(cat "$REPO/openbank-infra/gitops/components/payments/sepa_instant_rest_ext.rego")

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$SEPA_INSTANT_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/sepa-instant-opa-bundle.yaml

{
  echo "# GENERATED by gen-sepa-instant-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + sepa_instant_rest_ext.rego + agents.rego + agents-opa-data.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: sepa-instant-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: sepa-instant"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  sepa_instant_rest_ext.rego: |"
  echo "$SEPA_INSTANT_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-sca-opa-bundle.sh). The
# payments component hosts SEVERAL workloads in one file, so the substitution is
# scoped to the sepa-instant Rollout document only — a blanket sed would stomp the
# checksum of any sibling workload's own bundle (e.g. sepa-payment's, if/when it lands).
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
if [ -f "$ROLLOUT" ]; then
  CHECKSUM="$CHECKSUM" ROLLOUT="$ROLLOUT" python3 - << 'PY'
import os, re, sys

path = os.environ["ROLLOUT"]
checksum = os.environ["CHECKSUM"]
text = open(path).read()

docs = text.split("\n---\n")
patched = 0
for i, doc in enumerate(docs):
    if re.search(r"^kind: Rollout$", doc, re.M) and re.search(r"^  name: sepa-instant$", doc, re.M):
        if 'openbank.tech/policy-checksum: "' in doc:
            new, n = re.subn(
                r'(openbank\.tech/policy-checksum: ")[^"]*(")',
                rf"\g<1>{checksum}\g<2>",
                doc,
            )
        else:
            new, n = re.subn(
                r'(  labels:\n(?:.*\n)*?    app\.kubernetes\.io/part-of: payments\n)',
                lambda m: m.group(1) + (
                    "  annotations:\n"
                    "    # Rolls the pods when the OPA bundle changes — subPath mounts do NOT hot-reload.\n"
                    "    # Kept in sync by gen-sepa-instant-opa-bundle.sh (do not hand-edit).\n"
                    f'    openbank.tech/policy-checksum: "{checksum}"\n'
                ),
                doc,
                count=1,
            )
        if n == 0:
            sys.exit("sepa-instant Rollout found but could not stamp policy-checksum annotation")
        docs[i] = new
        patched += n

if patched == 0:
    sys.exit("sepa-instant Rollout not found in payments-services.yaml")
open(path, "w").write("\n---\n".join(docs))
PY
  echo "patched $ROLLOUT (sepa-instant Rollout) annotation → $CHECKSUM"
fi
