#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents-opa-data.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# VoP REST extension (ADR-0171, ADR-0034 Phase 5).
#
# Extension extracted to a standalone .rego (mirroring standing_order_rest_ext.rego, issue #1322)
# so `opa test` can load and cover it — see vop_rest_ext_test.rego in this same directory. It was
# a heredoc until #4228, which is why the rule below had no test: opa-policy.yml discovers suites
# by the *_rest_ext_test.rego / *_rest_ext.rego file PAIR, and a heredoc has no file to pair with.
VOP_REST_EXT=$REPO/openbank-infra/gitops/components/payments/vop_rest_ext.rego

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$VOP_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/vop-opa-bundle.yaml

{
  echo "# GENERATED by gen-vop-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + vop_rest_ext.rego + agents.rego + agents-opa-data.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: vop-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: vop-service"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  vop_rest_ext.rego: |"
  sed 's/^/    /' "$VOP_REST_EXT" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-sepa-instant-opa-bundle.sh).
#
# Document-scoped, and it EXITS NON-ZERO if the vop-service Rollout is missing:
# payments-services.yaml holds every payments rail, so a bare sed would stamp this checksum onto
# all of them, and a silent no-op would leave pods serving a stale policy with no signal.
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
if [ -f "$ROLLOUT" ]; then
  CHECKSUM="$CHECKSUM" ROLLOUT="$ROLLOUT" python3 - << 'PY'
import os, re, sys

path = os.environ["ROLLOUT"]
checksum = os.environ["CHECKSUM"]
text = open(path).read()

docs = text.split("\n---\n")
patched = 0
for i, doc in enumerate(docs):
    if re.search(r"^kind: Rollout$", doc, re.M) and re.search(r"^  name: vop-service$", doc, re.M):
        if 'openbank.tech/policy-checksum: "' in doc:
            new, n = re.subn(
                r'(openbank\.tech/policy-checksum: ")[^"]*(")',
                rf"\g<1>{checksum}\g<2>",
                doc,
            )
        else:
            new, n = re.subn(
                r'(  labels:\n(?:.*\n)*?    app\.kubernetes\.io/part-of: payments\n)',
                lambda m: m.group(1) + (
                    "  annotations:\n"
                    "    # Rolls the pods when the OPA bundle changes — subPath mounts do NOT hot-reload.\n"
                    "    # Kept in sync by gen-vop-opa-bundle.sh (do not hand-edit).\n"
                    f'    openbank.tech/policy-checksum: "{checksum}"\n'
                ),
                doc,
                count=1,
            )
        if n == 0:
            sys.exit("vop-service Rollout found but could not stamp policy-checksum annotation")
        docs[i] = new
        patched += n

if patched == 0:
    sys.exit("vop-service Rollout not found in payments-services.yaml")
open(path, "w").write("\n---\n".join(docs))
PY
  echo "patched $ROLLOUT (vop-service Rollout) annotation → $CHECKSUM"
fi
