#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents-opa-data.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# VoP REST extension (ADR-0171, ADR-0034 Phase 5).
VOP_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# VoP REST extension (ADR-0171 — Verification of Payee, Reg. (EU) 2024/886 Art. 5c).
# Extends openbank.rest with the vop-domain allow reason.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.
#
# Action gated (VopResource):
#   vop.verify — check a payee name against an IBAN (POST /api/v1/vop/verify)
#
# The action prefix is deliberately `vop`, matching the module name openbank-vop-service, so
# `money_path_scopes` in the base rest.rego derives "vop" and actually matches. Contrast
# gen-sepa-instant-opa-bundle.sh, whose real prefix is `sctInstPayment` while the derived scope
# is "sepa-instant" — a mismatch that silently stops four_eyes_required firing for that rail
# (issue #395). Naming this `vop.create` or `payeeVerification.*` would reintroduce that bug.
#
# Base rest.rego grants operator-read-any / compliance-read-any for *.read + *.list. `vop.verify`
# is neither, so it has no base coverage — that is the gap this extension fills.
#
# NOTE on why this is a *write-shaped* action with a read's consequences: vop.verify mints
# nothing and changes no money state, but it is not a `*.read` either — it is a name oracle
# (docs/threat-models/openbank-vop-service.md). Authorization deliberately does NOT try to bound
# the oracle: a payer must be able to check a payee they do not own, so any read-role holder may
# call it. The enumeration control is the per-requester rate limit (VopRateLimitFilter) plus the
# response asymmetry (never echo a name on NO_MATCH), not this rule.

package openbank.rest

import rego.v1

# Operators, admins, the payments desk and viewers may verify a payee. The admin-ui payments
# console initiates with the signed-in operator's OWN bearer token (BFF pattern, ADR-0080 P1).
# ROLE_VIEWER is included because verification is a pre-payment check, not a money movement —
# the same role set the resource's own @RolesAllowed declares.
allowed_reasons contains "operator-vop-verify" if {
	input.principal.type == "HUMAN"
	some role in {"ROLE_VIEWER", "ROLE_OPERATOR", "ROLE_ADMIN", "ROLE_PAYMENTS"}
	role in input.principal.roles
	input.action == "vop.verify"
}

# M2M: the payment rails verify a payee before execution. Gated on the Keycloak
# client_credentials convention (`service-account-*` preferred_username), which the
# AuthorizeInterceptor classifies as HUMAN — there is no SERVICE principal type, and a rule gated
# on one is unreachable dead code (rules.yaml: authz_policy.principal_type_service_unreachable).
#
# Deliberately scoped to vop.verify ONLY, never a `vop.` family prefix: this is the sole action
# today, and a family grant would silently pre-authorise any future write/config action (e.g. a
# threshold flip, which the threat model flags as the change with real fraud consequence).
#
# Deliberately NOT scoped to one hardcoded client id: more than one rail legitimately verifies a
# payee (sepa-instant, sepa-payment, domestic-payment, psd2), and unlike device.enroll this is not
# an account-takeover primitive. It IS a name oracle, which is why the rate limit — not a
# per-caller allow-list — is the control that bounds it.
allowed_reasons contains "m2m-vop-verify" if {
	input.principal.type == "HUMAN"
	startswith(input.principal.id, "service-account-")
	input.action == "vop.verify"
}
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$VOP_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/vop-opa-bundle.yaml

{
  echo "# GENERATED by gen-vop-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + vop_rest_ext.rego + agents.rego + agents-opa-data.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: vop-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: vop-service"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  vop_rest_ext.rego: |"
  echo "$VOP_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-sepa-instant-opa-bundle.sh).
#
# Document-scoped, and it EXITS NON-ZERO if the vop-service Rollout is missing:
# payments-services.yaml holds every payments rail, so a bare sed would stamp this checksum onto
# all of them, and a silent no-op would leave pods serving a stale policy with no signal.
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
if [ -f "$ROLLOUT" ]; then
  CHECKSUM="$CHECKSUM" ROLLOUT="$ROLLOUT" python3 - << 'PY'
import os, re, sys

path = os.environ["ROLLOUT"]
checksum = os.environ["CHECKSUM"]
text = open(path).read()

docs = text.split("\n---\n")
patched = 0
for i, doc in enumerate(docs):
    if re.search(r"^kind: Rollout$", doc, re.M) and re.search(r"^  name: vop-service$", doc, re.M):
        if 'openbank.tech/policy-checksum: "' in doc:
            new, n = re.subn(
                r'(openbank\.tech/policy-checksum: ")[^"]*(")',
                rf"\g<1>{checksum}\g<2>",
                doc,
            )
        else:
            new, n = re.subn(
                r'(  labels:\n(?:.*\n)*?    app\.kubernetes\.io/part-of: payments\n)',
                lambda m: m.group(1) + (
                    "  annotations:\n"
                    "    # Rolls the pods when the OPA bundle changes — subPath mounts do NOT hot-reload.\n"
                    "    # Kept in sync by gen-vop-opa-bundle.sh (do not hand-edit).\n"
                    f'    openbank.tech/policy-checksum: "{checksum}"\n'
                ),
                doc,
                count=1,
            )
        if n == 0:
            sys.exit("vop-service Rollout found but could not stamp policy-checksum annotation")
        docs[i] = new
        patched += n

if patched == 0:
    sys.exit("vop-service Rollout not found in payments-services.yaml")
open(path, "w").write("\n---\n".join(docs))
PY
  echo "patched $ROLLOUT (vop-service Rollout) annotation → $CHECKSUM"
fi
