#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# SEPA-payment REST extension lives in sepa_payment_rest_ext.rego (standalone since 2026-08-05,
# #3734 — the heredoc could not be opa-tested; tests: sepa_payment_rest_ext_test.rego).
EXT_REGO=$REPO/openbank-infra/gitops/components/payments/sepa_payment_rest_ext.rego
CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$EXT_REGO")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/sepa-payment-opa-bundle.yaml

{
  echo "# GENERATED by gen-sepa-payment-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + sepa_payment_rest_ext.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: sepa-payment-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: sepa-payment"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  sepa_payment_rest_ext.rego: |"
  sed 's/^/    /' "$EXT_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-sca-opa-bundle.sh). The
# payments component hosts SEVERAL workloads in one file, so the substitution is
# scoped to the sepa-payment Rollout document only — a blanket sed would stomp the
# checksum of any sibling workload that later gets its own bundle.
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
if [ -f "$ROLLOUT" ]; then
  CHECKSUM="$CHECKSUM" ROLLOUT="$ROLLOUT" python3 - << 'PY'
import os, re, sys

path = os.environ["ROLLOUT"]
checksum = os.environ["CHECKSUM"]
text = open(path).read()

docs = text.split("\n---\n")
patched = 0
for i, doc in enumerate(docs):
    if re.search(r"^kind: Rollout$", doc, re.M) and re.search(r"^  name: sepa-payment$", doc, re.M):
        new, n = re.subn(
            r'(openbank\.tech/policy-checksum: ")[^"]*(")',
            rf"\g<1>{checksum}\g<2>",
            doc,
        )
        if n == 0:
            sys.exit("sepa-payment Rollout found but no policy-checksum annotation to stamp")
        docs[i] = new
        patched += n

if patched == 0:
    sys.exit("sepa-payment Rollout not found in payments-services.yaml")
open(path, "w").write("\n---\n".join(docs))
PY
  echo "patched $ROLLOUT (sepa-payment Rollout) annotation → $CHECKSUM"
fi
