#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Card-issuance REST extension (ADR-0034 Phase 5 bootstrap, issue #938) — no OPA enforcement
# infrastructure existed for this service before this bootstrap. card-issuance-service deploys
# into the shared `payments` namespace/ArgoCD app (payments-services.yaml), not its own — this
# generator lives alongside that manifest for the same reason the other payments/* bundles do.
CARD_ISSUANCE_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# Card-issuance-service REST extension (ADR-0034 Phase 5 bootstrap, issue #938).
# Extends openbank.rest with card-domain allow reasons.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.
#
# Actions gated (CardResource):
#   card.create    — issueCard
#   card.list      — listAll, listByAccount (#accountId), listByParty (#partyId)
#   card.read      — getCard (#id)
#   card.activate  — activate (#id)
#   card.block     — block (#id) — ROLE_OPERATOR/ROLE_ADMIN/ROLE_COMPLIANCE (@RolesAllowed is a
#                    disjunction: ROLE_COMPLIANCE widens the caller set, it does not narrow it)
#   card.suspend   — suspend (#id) — customer-edge calls this on a customer's OWN card
#                    (self-service freeze, /customer/v1/cards/{id}/freeze)
#   card.resume    — resume (#id) — same, customer self-service unfreeze
#
# Base rest.rego already grants operator-read-any (ROLE_OPERATOR/ROLE_ADMIN) for card.list/.read
# — no extension needed for those. The remaining actions have no generic base-rego grant.
#
# Verified caller: customer-edge calls card.list/card.suspend/card.resume on the customer's own
# card via the shared `openbank-services` Keycloak client (service-account-openbank-services,
# whose realmRoles include ROLE_OPERATOR) — see CustomerEdgeResource.kt cardAction(). Per the
# documented fleet-wide limitation (rules.yaml authz_policy.principal_type_service_unreachable),
# AuthorizeInterceptor cannot distinguish this M2M caller from a real human operator holding
# ROLE_OPERATOR, so granting the role necessarily covers both — same stance as consent-service's
# service-consent-m2m rule.

package openbank.rest

import rego.v1

# Operators/admins may create, activate, block, suspend, or resume a card — mirroring
# CardResource's @RolesAllowed on each method. block() is included: its
# @RolesAllowed("ROLE_OPERATOR", "ROLE_ADMIN", "ROLE_COMPLIANCE") is a disjunction (any one role
# admits the caller), so ROLE_COMPLIANCE is an ADDITIONAL grantee, not an extra requirement.
# Omitting card.block here made the policy strictly narrower than the resource it guards: every
# card.block by ROLE_OPERATOR/ROLE_ADMIN would 403 the moment AUTHZ_ENFORCE flips to true,
# disabling the fraud response for a lost/stolen card for the only admin identity in the realm
# (admin@openbank.local holds OPERATOR/ADMIN/VIEWER, not COMPLIANCE).
allowed_reasons contains "operator-card-write" if {
	input.principal.type == "HUMAN"
	some role in {"ROLE_OPERATOR", "ROLE_ADMIN"}
	role in input.principal.roles
	input.action in {"card.create", "card.activate", "card.block", "card.suspend", "card.resume"}
}

# Blocking a card (fraud/compliance hold) is also grantable to ROLE_COMPLIANCE alone — a
# compliance officer who holds neither ROLE_OPERATOR nor ROLE_ADMIN can still block, matching the
# third role in CardResource's @RolesAllowed on block().
allowed_reasons contains "compliance-card-block" if {
	input.principal.type == "HUMAN"
	"ROLE_COMPLIANCE" in input.principal.roles
	input.action == "card.block"
}
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$CARD_ISSUANCE_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/card-issuance-opa-bundle.yaml

{
  echo "# GENERATED by gen-card-issuance-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + card_issuance_rest_ext.rego + agents.rego + agents.yaml + rules.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: card-issuance-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: card-issuance-service"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  card_issuance_rest_ext.rego: |"
  echo "$CARD_ISSUANCE_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# The checksum annotation for card-issuance-service's pod template lives inline inside the
# combined payments-services.yaml manifest. A blind sed across the whole multi-service file
# would touch every other service's annotation too, so scope the substitution to this
# service's own Rollout block — same awk pattern as the sibling payments generators.
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
if [ -f "$ROLLOUT" ]; then
  awk -v checksum="$CHECKSUM" '
    # card-issuance-service is a Deployment, not a Rollout like its payments siblings.
    /^kind: (Rollout|Deployment)$/ { pending_rollout = 1; print; next }
    pending_rollout && /^  name: card-issuance-service$/ { in_card_rollout = 1; pending_rollout = 0; print; next }
    pending_rollout && /^  name:/ { pending_rollout = 0 }
    /^---$/ { in_card_rollout = 0 }
    in_card_rollout && /openbank\.tech\/policy-checksum:/ {
      sub(/openbank\.tech\/policy-checksum: "[^"]*"/, "openbank.tech/policy-checksum: \"" checksum "\"")
    }
    { print }
  ' "$ROLLOUT" > "${ROLLOUT}.tmp" && mv "${ROLLOUT}.tmp" "$ROLLOUT"
  echo "patched $ROLLOUT card-issuance-service Deployment annotation -> $CHECKSUM"
fi
