#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Swift-service REST extension — SWIFT message lifecycle allow reasons (ADR-0034
# Phase 5, issue #266).
SWIFT_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# Swift-service REST extension (ADR-0034 Phase 5, issue #266).
# Extends openbank.rest with SWIFT-domain allow reasons.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.
#
# Actions gated (SwiftResource):
#   swift.send        — submit a new SWIFT message for dispatch (POST /api/v1/swift)
#   swift.read         — get a message by id
#   swift.list         — list messages (all / by status)
#   swift.acknowledge   — record ACK from the receiving bank
#   swift.reject        — record a rejection from the receiving bank
#
# Base rest.rego already grants: operator-read-any / compliance-read-any for
# swift.read + swift.list (no tenant/attribute check needed for either). SWIFT
# messages carry no per-resource tenant attribute (unlike sepa/domestic-payment),
# so operator-on-own-tenant never fires here — write actions need their own rule.

package openbank.rest

import rego.v1

# Operators and admins may drive the full SWIFT message lifecycle — send, ack,
# reject (the ops-desk path: manual correspondent-bank ACK/NAK entry, resending
# a held message). Read/list already ride on operator-read-any / compliance-read-any
# in base rest.rego; this rule only needs to cover the WRITE verbs.
allowed_reasons contains "operator-swift-write" if {
	input.principal.type == "HUMAN"
	some role in {"ROLE_OPERATOR", "ROLE_ADMIN"}
	role in input.principal.roles
	some verb in {"send", "acknowledge", "reject"}
	input.action == sprintf("swift.%s", [verb])
}

# NOTE — deliberately NO M2M rule (residual risk, see PR description): a repo-wide
# sweep found no in-repo REST client or Kafka consumer calling openbank-swift-service
# today (send/list/read/ack/reject all stay human-only).
#
# CORRECTNESS NOTE for whoever adds one later: AuthorizeInterceptor.principalType()
# (openbank-libs-runtime) only ever emits "ANONYMOUS", "AI_AGENT", or "HUMAN" — it
# NEVER emits "SERVICE". A rule gated on `input.principal.type == "SERVICE"` (the
# pattern base rest.rego's own edge-service-notification rule and the sca/consent/
# domestic-payment ext.rego templates all use) is DEAD CODE today — it can never
# match, so it silently grants nothing despite reading like a real M2M allow. OIDC
# client-credentials M2M callers (e.g. customer-edge) DO hit this same interceptor,
# but arrive typed HUMAN with principal.id set to the client's service-account
# subject (commonly "service-account-<client-name>", e.g.
# "service-account-openbank-services" for the shared backend client — most backend
# services share this one client, so it is NOT a strong per-caller identity). A real
# M2M rule here must gate on `input.principal.type == "HUMAN"` AND an identity check
# on `input.principal.id` (plus its roles), NOT `principal.type == "SERVICE"`. Until
# base rest.rego's own SERVICE-gated rules are fixed fleet-wide, do NOT copy that
# pattern from the sca/consent/domestic-payment ext.rego files — they carry the same
# latent bug.
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$SWIFT_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/swift-opa-bundle.yaml

{
  echo "# GENERATED by gen-swift-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + swift_rest_ext.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: swift-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: swift-service"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  swift_rest_ext.rego: |"
  echo "$SWIFT_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-sca-opa-bundle.sh). The
# swift Rollout lives inside the SHARED payments-services.yaml (domestic-payment,
# sepa-payment, settlement, etc. also live there) — anchor STRICTLY on the
# `kind: Rollout` document that is immediately followed by `name: swift-service`
# (the Service/canary-Service documents later in the file share the same `name:
# swift-service` line but are NOT preceded by `kind: Rollout`), so this can never
# stomp a sibling service's checksum or the wrong document.
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
if [ -f "$ROLLOUT" ]; then
  awk -v checksum="$CHECKSUM" '
    /^kind: Rollout$/ { pending_rollout = 1; print; next }
    pending_rollout && /^  name: swift-service$/ { in_swift_rollout = 1; pending_rollout = 0; print; next }
    pending_rollout && /^  name:/ { pending_rollout = 0 }
    /^---$/ { in_swift_rollout = 0 }
    in_swift_rollout && /openbank\.tech\/policy-checksum:/ {
      sub(/openbank\.tech\/policy-checksum: "[^"]*"/, "openbank.tech/policy-checksum: \"" checksum "\"")
    }
    { print }
  ' "$ROLLOUT" > "${ROLLOUT}.tmp" && mv "${ROLLOUT}.tmp" "$ROLLOUT"
  echo "patched $ROLLOUT swift-service Rollout annotation -> $CHECKSUM"
fi
