#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents-opa-data.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Card-processing REST extension (ADR-0283 phase 1, #8809). card-processing-service deploys into
# the shared `payments` namespace/ArgoCD app (payments-services.yaml), not its own — this generator
# lives alongside that manifest for the same reason every other payments/* bundle does.
#
# The extension is a standalone .rego file rather than an inline heredoc so that `opa test` can load
# and cover it directly (issue #1322) — see card_processing_rest_ext_test.rego in this directory,
# which pins both halves of every rule: what it allows AND what it refuses. A heredoc has nothing on
# disk for `opa test` to discover.
CARD_PROCESSING_REST_EXT=$REPO/openbank-infra/gitops/components/payments/card_processing_rest_ext.rego

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$CARD_PROCESSING_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/card-processing-opa-bundle.yaml

{
  echo "# GENERATED by gen-card-processing-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + card_processing_rest_ext.rego + agents.rego + agents-opa-data.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: card-processing-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: card-processing-service"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  card_processing_rest_ext.rego: |"
  sed 's/^/    /' "$CARD_PROCESSING_REST_EXT" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# The checksum annotation for card-processing-service's pod template lives inline inside the
# combined payments-services.yaml manifest. A blind sed across the whole multi-service file
# would touch every other service's annotation too, so scope the substitution to this
# service's own Rollout block — same awk pattern as the sibling payments generators.
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
if [ -f "$ROLLOUT" ]; then
  awk -v checksum="$CHECKSUM" '
    # card-processing-service is a Deployment, not a Rollout like its payments siblings.
    /^kind: (Rollout|Deployment)$/ { pending_rollout = 1; print; next }
    pending_rollout && /^  name: card-processing-service$/ { in_card_rollout = 1; pending_rollout = 0; print; next }
    pending_rollout && /^  name:/ { pending_rollout = 0 }
    /^---$/ { in_card_rollout = 0 }
    in_card_rollout && /openbank\.tech\/policy-checksum:/ {
      sub(/openbank\.tech\/policy-checksum: "[^"]*"/, "openbank.tech/policy-checksum: \"" checksum "\"")
    }
    { print }
  ' "$ROLLOUT" > "${ROLLOUT}.tmp" && mv "${ROLLOUT}.tmp" "$ROLLOUT"
  echo "patched $ROLLOUT card-processing-service Deployment annotation -> $CHECKSUM"
fi
