#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Standing-order REST extension (ADR-0034 Phase 5 bootstrap, issue #1797) — standing-order-service
# enforced @Authorize with no OPA sidecar to ask, so its one @Authorize endpoint
# (standingOrder.pause) failed closed. This generator wires the PDP, mirroring the card-issuance
# bootstrap. standing-order-service deploys into the shared `payments` namespace/ArgoCD app
# (payments-services.yaml), not its own — this generator lives alongside that manifest for the
# same reason the other payments/* bundles do.
#
# Extension extracted to a standalone .rego (issue #1322) so `opa test` can load and cover it —
# see standing_order_rest_ext_test.rego in this same directory.
STANDING_ORDER_REST_EXT=$REPO/openbank-infra/gitops/components/payments/standing_order_rest_ext.rego

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(cat "$STANDING_ORDER_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/payments/standing-order-opa-bundle.yaml

{
  echo "# GENERATED by gen-standing-order-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + standing_order_rest_ext.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: standing-order-opa-bundle"
  echo "  namespace: payments"
  echo "  labels:"
  echo "    app.kubernetes.io/name: standing-order-service"
  echo "    app.kubernetes.io/part-of: payments"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  standing_order_rest_ext.rego: |"
  sed 's/^/    /' "$STANDING_ORDER_REST_EXT" | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# The checksum annotation for standing-order-service's pod template lives inline inside the
# combined payments-services.yaml manifest. A blind sed across the whole multi-service file
# would touch every other service's annotation too, so scope the substitution to this
# service's own Deployment block — same awk pattern as the sibling payments generators.
ROLLOUT=$REPO/openbank-infra/gitops/components/payments/payments-services.yaml
if [ -f "$ROLLOUT" ]; then
  awk -v checksum="$CHECKSUM" '
    # standing-order-service is a Deployment, not a Rollout like its payments siblings.
    /^kind: (Rollout|Deployment)$/ { pending_rollout = 1; print; next }
    pending_rollout && /^  name: standing-order-service$/ { in_so_rollout = 1; pending_rollout = 0; print; next }
    pending_rollout && /^  name:/ { pending_rollout = 0 }
    /^---$/ { in_so_rollout = 0 }
    in_so_rollout && /openbank\.tech\/policy-checksum:/ {
      sub(/openbank\.tech\/policy-checksum: "[^"]*"/, "openbank.tech/policy-checksum: \"" checksum "\"")
    }
    { print }
  ' "$ROLLOUT" > "${ROLLOUT}.tmp" && mv "${ROLLOUT}.tmp" "$ROLLOUT"
  echo "patched $ROLLOUT standing-order-service Deployment annotation -> $CHECKSUM"
fi
