// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

package com.openbank.aml.contract

import au.com.dius.pact.provider.junit5.HttpTestTarget
import au.com.dius.pact.provider.junit5.PactVerificationContext
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider
import au.com.dius.pact.provider.junitsupport.IgnoreNoPactsToVerify
import au.com.dius.pact.provider.junitsupport.Provider
import au.com.dius.pact.provider.junitsupport.State
import au.com.dius.pact.provider.junitsupport.loader.PactFolder
import io.quarkus.test.common.QuarkusTestResource
import io.quarkus.test.junit.QuarkusTest
import io.quarkus.test.security.TestSecurity
import org.eclipse.microprofile.config.inject.ConfigProperty
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.TestTemplate
import org.junit.jupiter.api.extension.ExtendWith

/**
 * Provider-side Pact verification for aml-service — its FIRST contract coverage of any kind
 * (issue #2255, dimension C3: an `openapi.yaml` existed but nothing replayed a consumer contract,
 * while two services call this API in production).
 *
 * Reads the consumer pacts from the git-pact folder (`@PactFolder`, resolved relative to this
 * module's working directory at `../pacts` = the monorepo-root `pacts/` dir) and replays every
 * interaction whose provider is `openbank-aml-service` against the running Quarkus test instance.
 * This always runs — no broker, no gate, no CI secret (ADR-0063 chose git-pact over a Pact Broker
 * for exactly this reason: zero new infra dependency).
 *
 * Verified today: `openbank-fx-service` -> `POST /api/v1/aml/cases`, generated by
 * `AmlCaseCreationPactConsumerTest` in openbank-fx-service. If that test's contract changes,
 * regenerate the pact JSON (`./gradlew :openbank-fx-service:test --tests
 * "*AmlCaseCreationPactConsumerTest*"`) and commit
 * `pacts/openbank-fx-service-openbank-aml-service.json` in the same PR, or this test verifies a
 * stale contract.
 *
 * **This must remain the ONLY `@Provider("openbank-aml-service")` class in the repo.** Two classes
 * sharing a provider name both pull every pact for that provider and collide (`rules.yaml:`
 * ADR-0029 D3 note); a second interaction type belongs in `@BeforeEach` target selection here, not
 * in a new class.
 *
 * `@IgnoreNoPactsToVerify(ignoreIoErrors)` makes a missing/unreadable pact file a skip rather than
 * a failure — relevant if the folder is ever emptied ahead of a broker migration.
 *
 * Authentication: `POST /api/v1/aml/cases` is `@RolesAllowed("ROLE_OPERATOR", "ROLE_ADMIN",
 * "ROLE_COMPLIANCE")`. `@TestSecurity` cannot annotate a `@TestTemplate` method, so it is applied at
 * class level and Pact replays every interaction as that principal. Note the POST — unlike the
 * `@GET` reads — does NOT accept `ROLE_SERVICE`, so the caller's Keycloak client must carry an
 * operator-grade role; the pact cannot assert that, only that the endpoint honours the contract once
 * the caller is authorised.
 */
@QuarkusTest
@QuarkusTestResource(com.openbank.aml.it.PostgresRedisTestResource::class)
@TestSecurity(user = "pact-verifier", roles = ["ROLE_OPERATOR", "ROLE_COMPLIANCE"])
@Provider("openbank-aml-service")
@PactFolder("../pacts")
@IgnoreNoPactsToVerify(ignoreIoErrors = "true")
class AmlPactProviderVerificationTest {

    @ConfigProperty(name = "quarkus.http.test-port", defaultValue = "8081")
    lateinit var testPort: String

    @BeforeEach
    fun configureTarget(context: PactVerificationContext?) {
        context?.target = HttpTestTarget("localhost", testPort.toInt())
        context?.addStateChangeHandlers(this)
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider::class)
    fun verifyPacts(context: PactVerificationContext?) {
        context?.verifyInteraction()
    }

    /**
     * State: "no AML case exists for the FX conversion idempotency key".
     *
     * No seeding needed, and none is possible from here without tripping a documented footgun: the
     * fresh Testcontainer Postgres + Valkey carry neither the case row nor the Redis idempotency
     * entry, so `AmlCaseService.createCase` takes the create branch and answers `201 Created`.
     *
     * Deliberately NOT asserted by seeding the other direction (a pre-existing case, i.e. the
     * idempotent-replay branch): both stores are reached through `suspend` reactive APIs
     * (`IdempotencyStore`, reactive Panache), which cannot be driven from a plain JUnit
     * state-change callback without a Vert.x context — the HR000068 trap. The replay path is also
     * invisible to the consumer, which returns the raw `Response` and reads no field of it, so it
     * would be provider-internal behaviour with no consumer expectation to pin. It stays covered by
     * this service's own ITs.
     *
     * Re-running the suite against a warm container is still safe: `createCase` is idempotent on
     * both the Redis key and `findByIdempotencyKey`, and every path answers 201.
     */
    @State("no AML case exists for the FX conversion idempotency key")
    fun stateNoExistingCaseForIdempotencyKey() {
        // Intentionally empty — see the KDoc above.
    }
}
