// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

package com.openbank.aml.contract

import au.com.dius.pact.provider.junit5.HttpTestTarget
import au.com.dius.pact.provider.junit5.PactVerificationContext
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider
import au.com.dius.pact.provider.junitsupport.IgnoreNoPactsToVerify
import au.com.dius.pact.provider.junitsupport.Provider
import au.com.dius.pact.provider.junitsupport.State
import au.com.dius.pact.provider.junitsupport.loader.PactFolder
import com.openbank.libs.testing.containers.PostgresRedisTestResource
import io.quarkus.test.common.QuarkusTestResource
import io.quarkus.test.common.ResourceArg
import io.quarkus.test.junit.QuarkusTest
import io.quarkus.test.security.TestIdentityAssociation
import io.quarkus.test.security.TestSecurity
import jakarta.inject.Inject
import org.eclipse.microprofile.config.inject.ConfigProperty
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.TestTemplate
import org.junit.jupiter.api.extension.ExtendWith

/**
 * Provider-side Pact verification for aml-service — its FIRST contract coverage of any kind
 * (issue #2255, dimension C3: an `openapi.yaml` existed but nothing replayed a consumer contract,
 * while two services call this API in production).
 *
 * Reads the consumer pacts from the git-pact folder (`@PactFolder`, resolved relative to this
 * module's working directory at `../pacts` = the monorepo-root `pacts/` dir) and replays every
 * interaction whose provider is `openbank-aml-service` against the running Quarkus test instance.
 * This always runs — no broker, no gate, no CI secret (ADR-0063 chose git-pact over a Pact Broker
 * for exactly this reason: zero new infra dependency).
 *
 * Verified today: `openbank-fx-service` -> `POST /api/v1/aml/cases`, generated by
 * `AmlCaseCreationPactConsumerTest` in openbank-fx-service. If that test's contract changes,
 * regenerate the pact JSON (`./gradlew :openbank-fx-service:test --tests
 * "*AmlCaseCreationPactConsumerTest*"`) and commit
 * `pacts/openbank-fx-service-openbank-aml-service.json` in the same PR, or this test verifies a
 * stale contract.
 *
 * **This is the git-pact half of the sanctioned pair.** Its counterpart is
 * [AmlPactBrokerProviderVerificationTest], a `@PactBroker` class gated on `pactbroker.url` that
 * runs only on main-push and PUBLISHES its result — which is what `can-i-deploy` reads, and what
 * this class structurally cannot do. Before that class existed, aml-service had never published a
 * version on main and every fx-service deploy was blocked on the missing verification.
 *
 * That is the only permitted second `@Provider("openbank-aml-service")` class. The collision
 * ADR-0029 D3 warns about is two BROKER-sourced classes both pulling every pact, or HTTP and
 * MESSAGE targets fighting over the same `@BeforeEach`; both classes here use `HttpTestTarget`
 * exclusively and read from different sources. A further interaction TYPE still belongs in
 * `@BeforeEach` target selection here, not in a third class — and any `@State` added here must be
 * added to the broker class too, or the broker replay fails with MissingStateChangeMethod and
 * publishes a failure.
 *
 * `@IgnoreNoPactsToVerify(ignoreIoErrors)` makes a missing/unreadable pact file a skip rather than
 * a failure — relevant if the folder is ever emptied ahead of a broker migration.
 *
 * Authentication: `POST /api/v1/aml/cases` is `@RolesAllowed("ROLE_OPERATOR", "ROLE_ADMIN",
 * "ROLE_COMPLIANCE")`. `@TestSecurity` cannot annotate a `@TestTemplate` method, so it is applied at
 * class level and Pact replays every interaction as that principal. Note the POST — unlike the
 * `@GET` reads — does NOT accept `ROLE_API`, so the caller's Keycloak client must carry an
 * operator-grade role; the pact cannot assert that, only that the endpoint honours the contract once
 * the caller is authorised.
 */
@QuarkusTest
@QuarkusTestResource(
    value = PostgresRedisTestResource::class,
    initArgs = [ResourceArg(name = "db", value = "openbank_aml_it")],
)
@TestSecurity(user = "pact-verifier", roles = ["ROLE_OPERATOR", "ROLE_COMPLIANCE"])
@Provider("openbank-aml-service")
@PactFolder("../pacts")
@IgnoreNoPactsToVerify(ignoreIoErrors = "true")
class AmlPactProviderVerificationTest {

    @ConfigProperty(name = "quarkus.http.test-port", defaultValue = "8081")
    lateinit var testPort: String

    /**
     * The class-level `@TestSecurity` authenticates every request, which would turn a consumer's
     * 401/403 interaction green-by-accident into a mismatch — or, worse, hide a provider that
     * stopped enforcing authz. For [NO_IDENTITY_STATE] the test identity is cleared in
     * `verifyPacts`, so the request arrives anonymous, exactly as the consumer encoded it.
     */
    @Inject
    lateinit var testIdentity: TestIdentityAssociation

    @BeforeEach
    fun configureTarget(context: PactVerificationContext?) {
        context?.target = HttpTestTarget("localhost", testPort.toInt())
        context?.addStateChangeHandlers(this)
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider::class)
    fun verifyPacts(context: PactVerificationContext?) {
        if (context?.interaction?.providerStates?.any { it.name == NO_IDENTITY_STATE } == true) {
            testIdentity.setTestIdentity(null)
        }
        context?.verifyInteraction()
    }

    /**
     * State: "no AML case exists for the FX conversion idempotency key".
     *
     * No seeding needed, and none is possible from here without tripping a documented footgun: the
     * fresh Testcontainer Postgres + Valkey carry neither the case row nor the Redis idempotency
     * entry, so `AmlCaseService.createCase` takes the create branch and answers `201 Created`.
     *
     * Deliberately NOT asserted by seeding the other direction (a pre-existing case, i.e. the
     * idempotent-replay branch): both stores are reached through `suspend` reactive APIs
     * (`IdempotencyStore`, reactive Panache), which cannot be driven from a plain JUnit
     * state-change callback without a Vert.x context — the HR000068 trap. The replay path is also
     * invisible to the consumer, which returns the raw `Response` and reads no field of it, so it
     * would be provider-internal behaviour with no consumer expectation to pin. It stays covered by
     * this service's own ITs.
     *
     * Re-running the suite against a warm container is still safe: `createCase` is idempotent on
     * both the Redis key and `findByIdempotencyKey`, and every path answers 201.
     */
    @State("no AML case exists for the FX conversion idempotency key")
    fun stateNoExistingCaseForIdempotencyKey() {
        // Intentionally empty — see the KDoc above.
    }

    /**
     * The negative-auth case (ADR-0279 #3): a request with no identity must be refused, not
     * silently authorised. No committed consumer pact currently exercises this provider state —
     * the handler exists so the boundary is pinned into the contract per the fleet-wide convention
     * ([com.openbank.lending.contract.LoanBookPactState.NO_IDENTITY]) and so a future consumer
     * interaction encoding it verifies immediately without a provider-side change.
     */
    @State(NO_IDENTITY_STATE)
    fun noIdentity() {
        // Intentionally empty: the state IS the absence of an identity (see verifyPacts).
    }

    private companion object {
        const val NO_IDENTITY_STATE = "no valid identity is presented"
    }
}
