apiVersion: v1
kind: Namespace
metadata:
  name: referral
  labels:
    openbank.io/plane: app
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
