// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OpenBank contributors. Licensed under the Apache License, Version 2.0.
// See LICENSE in the repository root or https://www.apache.org/licenses/LICENSE-2.0 for details.

import { NextResponse } from 'next/server'
import { promises as fs } from 'fs'
import path from 'path'

// ── Security KPIs: Prometheus text exposition of the CI-generated snapshot ───
//
// Same source as the sibling JSON route (../route.ts): the weekly
// security-kpis.json baked into the image by .github/workflows/security-kpis.yml.
// This endpoint exists because the console is READ-ONLY for humans — the numbers
// had no path into Prometheus, so no alert and no Grafana panel could see them.
// Scraped via servicemonitor-admin-ui.yaml (observability); alerting rules live
// in prometheus-rules-security-kpis.yaml.
//
// House rules honored here:
//   * ADR-0056 graceful degradation: ALWAYS HTTP 200. A missing/corrupt snapshot
//     or an unavailable collector means the series is OMITTED, never rendered as
//     0 — a 0 would read as "no overdue credentials" and silence the very alert
//     (SecurityKpiSnapshotStale) that exists to catch a dead pipeline. Absence is
//     the honest signal.
//   * No new dependency: the text format is a plain string template.
//   * Every series carries the const label team="security" (Alertmanager routes
//     on it), matching the team label on the PrometheusRule alerts.

export const dynamic = 'force-dynamic'
export const revalidate = 0

const TEAM_LABEL = '{team="security"}'

interface Gauge {
  name: string
  help: string
  value: number
}

function isNum(v: unknown): v is number {
  return typeof v === 'number' && Number.isFinite(v)
}

function snapshotFile(): string {
  return process.env.OPENBANK_SECURITY_KPIS
    ?? path.resolve(process.cwd(), 'security-kpis.json')
}

// Extract the gauges that the snapshot actually supports today. Each collector
// degrades independently (`available: false` + reason), so each mapping checks
// its own section and field — a field that is not a finite number is omitted.
// NOT exported: a route module may export only Next.js' Route export fields
// (webpack fails the build on anything else; Turbopack dev tolerates it, which
// is how #3262/#3611 shipped — gate route-exports enforces this).
function gaugesFromSnapshot(kpis: Record<string, unknown>): Gauge[] {
  const out: Gauge[] = []
  const section = (k: string): Record<string, unknown> | null => {
    const s = kpis[k]
    return s && typeof s === 'object' && (s as Record<string, unknown>).available === true
      ? (s as Record<string, unknown>)
      : null
  }
  const push = (name: string, help: string, sec: Record<string, unknown> | null, field: string) => {
    const v = sec?.[field]
    if (isNum(v)) out.push({ name, help, value: v })
  }

  push('openbank_security_kpi_netpol_coverage_pct',
    'Percentage of in-scope components carrying the generated ingress NetworkPolicy.',
    section('netpol'), 'coveragePct')
  push('openbank_security_kpi_dependency_freshness_score',
    'Fleet dependency-freshness score (0-100) from deps-freshness.py against Maven Central.',
    section('freshness'), 'fleetScore')
  push('openbank_security_kpi_credentials_overdue',
    'Static credentials past their declared rotation deadline.',
    section('credentials'), 'overdue')
  push('openbank_security_kpi_credentials_undeclared',
    'Static credentials with no rotation deadline declared.',
    section('credentials'), 'undeclared')
  push('openbank_security_kpi_fuzz_coverage_pct',
    'Percentage of in-scope API-fuzz operations actually exercised by the latest fleet run.',
    section('fuzz'), 'coveragePct')
  push('openbank_security_kpi_fuzz_tested_operations',
    'In-scope API-fuzz operations exercised by the latest fleet run.',
    section('fuzz'), 'tested')
  push('openbank_security_kpi_fuzz_in_scope_operations',
    'API-fuzz operations in scope for the latest fleet run.',
    section('fuzz'), 'inScope')
  push('openbank_security_kpi_threat_models_stale',
    'Money-path threat models untouched for more than 90 days.',
    section('threatModels'), 'staleCount')
  push('openbank_security_kpi_dependabot_oldest_open_days',
    'Age in days of the oldest open Critical/High Dependabot alert.',
    section('mttr'), 'oldestOpenDays')

  // Staleness anchor for SecurityKpiSnapshotStale: when the weekly publisher stops
  // landing, every gauge above freezes at its last value — only this timestamp
  // still says the snapshot is old.
  const generatedAt = kpis.generatedAt
  if (typeof generatedAt === 'string') {
    const ts = Date.parse(generatedAt)
    if (Number.isFinite(ts)) {
      out.push({
        name: 'openbank_security_kpi_generated_timestamp_seconds',
        help: 'Unix timestamp when the security-kpis.json snapshot was generated by CI.',
        value: Math.floor(ts / 1000),
      })
    }
  }
  return out
}

export async function GET(): Promise<NextResponse> {
  let gauges: Gauge[] = []
  try {
    const raw = await fs.readFile(snapshotFile(), 'utf-8')
    gauges = gaugesFromSnapshot(JSON.parse(raw) as Record<string, unknown>)
  } catch {
    // Absent/corrupt snapshot: still 200, with zero series. Prometheus records the
    // target as up with no samples; SecurityKpiSnapshotStale/absent() semantics
    // surface the gap instead of a scrape error storm.
    gauges = []
  }

  const lines: string[] = []
  for (const g of gauges) {
    lines.push(`# HELP ${g.name} ${g.help}`)
    lines.push(`# TYPE ${g.name} gauge`)
    lines.push(`${g.name}${TEAM_LABEL} ${g.value}`)
  }
  return new NextResponse(lines.join('\n') + '\n', {
    status: 200,
    headers: { 'Content-Type': 'text/plain; version=0.0.4; charset=utf-8' },
  })
}
