#!/usr/bin/env bash
# Generate docs/adr/README.md — the ADR index. DERIVED DATA: never hand-edit the
# README; edit the ADRs (or this script) and re-run `bash docs/adr/gen-index.sh`.
#
# Status parsing tolerates the three historical conventions (`Status:`, `**Status:**`,
# `| Status | … |`) and the new two-axis front-matter (`Decision-Status:` /
# `Delivery-Status:` from TEMPLATE.md). New ADRs should use the two-axis form.
set -euo pipefail
cd "$(dirname "$0")"

# Fail loudly on duplicate ADR numbers -- a self-colliding registry is exactly the
# "governance-as-code that cannot govern itself" footgun this index exists to prevent.
dupes=$(ls [0-9]*.md | sed -E 's/-.*//' | sort | uniq -d)
if [ -n "$dupes" ]; then
  echo "ERROR: duplicate ADR number(s): $dupes" >&2
  exit 1
fi

OUT=README.md
{
  echo "# Architecture Decision Records — index"
  echo
  echo "_Generated by \`docs/adr/gen-index.sh\` — do not hand-edit. Re-run after adding or"
  echo "changing an ADR._ Start reading at [ADR-0001](0001-record-architecture-decisions.md);"
  echo "governance is [0029](0029-versioning-release-and-governance-as-code.md) /"
  echo "[0030](0030-supply-chain-security-and-ssdlc-hardening.md). Create a new ADR with"
  echo "\`docs/adr/new.sh \"Title\"\` — it allocates a collision-free number (across local,"
  echo "\`origin/main\`, and open PRs) and scaffolds [TEMPLATE.md](TEMPLATE.md) with the canonical"
  echo "two-axis **Decision-Status** / **Delivery-Status** front-matter."
  echo
  echo "| ADR | Title | Decision | Delivery | Repos |"
  echo "|----:|-------|----------|----------|-------|"

  for f in $(ls [0-9]*.md | sort); do
    num=${f%%-*}
    h1=$(grep -m1 '^# ' "$f" | perl -CSD -pe 's/^#\s+//; s/^ADR-\d+\s+[\x{2014}\x{2013}-]\s+//; s/^\d+\.\s+//')

    decision=$(grep -m1 -iE '^[*_ ]*Decision-Status[*_ ]*:' "$f" | sed -E 's/.*[Dd]ecision-[Ss]tatus[*_ ]*:[* ]*//; s/<!--.*-->//; s/ *$//' || true)
    if [ -z "$decision" ]; then
      # fall back to legacy single Status: line / **Status:** / | Status | … |
      decision=$(grep -m1 -iE '^[*_| ]*Status[*_ |]*[:|]' "$f" \
        | sed -E 's/^[*_| ]*Status[*_ ]*[:|]+[*_ ]*//; s/\|.*$//; s/[*_ ]*$//; s/^[*_ ]*//' || true)
    fi
    # tolerate plain / bold / table (| Delivery-Status | … |) encodings
    delivery=$(grep -m1 -iE '^[*_| ]*Delivery-Status[*_ |]*[:|]' "$f" \
      | sed -E 's/^[*_| ]*Delivery-Status[*_ ]*[:|]+[*_ ]*//; s/<!--.*-->//; s/\|.*$//; s/[*_ ]*$//; s/^[*_ ]*//' || true)
    # ADR-0147: optional cross-repo delivery pointer. Only match a live (non-comment)
    # line — the TEMPLATE.md example is inside an HTML comment and must not match.
    repos=$(grep -m1 -E '^Delivery-Repos:' "$f" | sed -E 's/^Delivery-Repos:[* ]*//; s/ *$//' || true)

    [ -z "$decision" ] && decision="—"
    [ -z "$delivery" ] && delivery="—"
    [ -z "$repos" ] && repos="—"
    # collapse to a short token for the table (first sentence / before parenthesis)
    decision_short=$(echo "$decision" | sed -E 's/ *\(.*$//; s/ on [0-9].*$//' | cut -c1-40)
    printf '| [%s](%s) | %s | %s | %s | %s |\n' "$num" "$f" "$h1" "$decision_short" "$delivery" "$repos"
  done

  # Numbering gaps: computed from the actual file list, not hand-typed, so this
  # note can't rot into a stale claim if a gap is ever filled or a new one opens.
  numbers=$(ls [0-9]*.md | sed -E 's/-.*//' | sort -n)
  gaps=""
  prev=""
  for n in $numbers; do
    n10=$((10#$n))
    if [ -n "$prev" ] && [ "$n10" -gt "$((prev + 1))" ]; then
      g=$((prev + 1))
      while [ "$g" -lt "$n10" ]; do
        gaps="$gaps $(printf '%04d' "$g")"
        g=$((g + 1))
      done
    fi
    prev=$n10
  done
  if [ -n "$gaps" ]; then
    echo
    echo "---"
    echo
    echo "**Numbering gaps:**$gaps do not correspond to a file in this repo's history —"
    echo "confirmed by \`git log --diff-filter=A\` across all branches, not just an absent"
    echo "current file. One of them, ADR-0132, is named in a 2026-06 commit message"
    echo "(\"fix(customer-edge): add per-party rate-limit config key (ADR-0132)\") with no"
    echo "corresponding merged ADR file, which does not by itself explain the other five."
    echo "No decision record in this repo accounts for the gap; treat it as an open"
    echo "question for whoever holds the pre-public-launch history, not a deliberate"
    echo "reservation."
  fi
} > "$OUT"

echo "Wrote $OUT ($(grep -c '^| \[' "$OUT") ADRs indexed)."
