#!/usr/bin/env bash
# Generate docs/adr/README.md — the ADR index. DERIVED DATA: never hand-edit the
# README; edit the ADRs (or this script) and re-run `bash docs/adr/gen-index.sh`.
#
# Status parsing tolerates the three historical conventions (`Status:`, `**Status:**`,
# `| Status | … |`) and the new two-axis front-matter (`Decision-Status:` /
# `Delivery-Status:` from TEMPLATE.md). New ADRs should use the two-axis form.
set -euo pipefail
cd "$(dirname "$0")"

OUT=README.md
{
  echo "# Architecture Decision Records — index"
  echo
  echo "_Generated by \`docs/adr/gen-index.sh\` — do not hand-edit. Re-run after adding or"
  echo "changing an ADR._ Start reading at [ADR-0001](0001-record-architecture-decisions.md);"
  echo "governance is [0029](0029-versioning-release-and-governance-as-code.md) /"
  echo "[0030](0030-supply-chain-security-and-ssdlc-hardening.md). Create a new ADR with"
  echo "\`docs/adr/new.sh \"Title\"\` — it allocates a collision-free number (across local,"
  echo "\`origin/main\`, and open PRs) and scaffolds [TEMPLATE.md](TEMPLATE.md) with the canonical"
  echo "two-axis **Decision-Status** / **Delivery-Status** front-matter."
  echo
  echo "| ADR | Title | Decision | Delivery |"
  echo "|----:|-------|----------|----------|"

  for f in $(ls [0-9]*.md | sort); do
    num=${f%%-*}
    h1=$(grep -m1 '^# ' "$f" | perl -CSD -pe 's/^#\s+//; s/^ADR-\d+\s+[\x{2014}\x{2013}-]\s+//; s/^\d+\.\s+//')

    decision=$(grep -m1 -iE '^[*_ ]*Decision-Status[*_ ]*:' "$f" | sed -E 's/.*[Dd]ecision-[Ss]tatus[*_ ]*:[* ]*//; s/<!--.*-->//; s/ *$//' || true)
    if [ -z "$decision" ]; then
      # fall back to legacy single Status: line / **Status:** / | Status | … |
      decision=$(grep -m1 -iE '^[*_| ]*Status[*_ |]*[:|]' "$f" \
        | sed -E 's/^[*_| ]*Status[*_ ]*[:|]+[*_ ]*//; s/\|.*$//; s/[*_ ]*$//; s/^[*_ ]*//' || true)
    fi
    # tolerate plain / bold / table (| Delivery-Status | … |) encodings
    delivery=$(grep -m1 -iE '^[*_| ]*Delivery-Status[*_ |]*[:|]' "$f" \
      | sed -E 's/^[*_| ]*Delivery-Status[*_ ]*[:|]+[*_ ]*//; s/<!--.*-->//; s/\|.*$//; s/[*_ ]*$//; s/^[*_ ]*//' || true)

    [ -z "$decision" ] && decision="—"
    [ -z "$delivery" ] && delivery="—"
    # collapse to a short token for the table (first sentence / before parenthesis)
    decision_short=$(echo "$decision" | sed -E 's/ *\(.*$//; s/ on [0-9].*$//' | cut -c1-40)
    printf '| [%s](%s) | %s | %s | %s |\n' "$num" "$f" "$h1" "$decision_short" "$delivery"
  done
} > "$OUT"

echo "Wrote $OUT ($(grep -c '^| \[' "$OUT") ADRs indexed)."
