#!/usr/bin/env bash
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"

REST_REGO=$REPO/openbank-libs/governance/policies/rest.rego
AGENTS_REGO=$REPO/openbank-infra/opa/policies/agents.rego
AGENTS_YAML=$REPO/openbank-libs/governance/agents.yaml
RULES_YAML=$REPO/openbank-libs/governance/rules-opa-data.yaml
MANIFEST=$REPO/openbank-infra/opa/bundle.manifest

# Sanctions REST extension (ADR-0034 Phase 5 bootstrap, issue #938 follow-up) — no OPA
# enforcement infrastructure existed for this service before this bootstrap.
SANCTIONS_REST_EXT=$(cat << 'REGO'
# SPDX-License-Identifier: Apache-2.0
# Sanctions-service REST extension (ADR-0034 Phase 5 bootstrap, issue #938 follow-up).
# Extends openbank.rest with sanctions-domain allow reasons.
# Mounted alongside rest.rego in the same OPA bundle — OPA merges same-package rules.
#
# Actions gated (SanctionsResource / SanctionsListResource):
#   sanctions.list    — listAll / hits / pending
#   sanctions.read    — get by id (#id)
#   sanctions.create  — screen (POST /screen); resourceless M2M write, already granted to
#                       any service-account-* caller by base rest.rego's m2m-sanctions-screening
#   sanctions.clear   — review (POST /review); decide a screening hit (renamed from
#                       sanctions.review, issue #938 follow-up). Four-eyes gated (rules.yaml
#                       four_eyes.verbs) — a wrongly-cleared true positive is a real sanctions
#                       violation. No ROLE_SERVICE on this endpoint, confirmed no M2M caller.
#   sanctions.update  — edit a watchlist entry (#listType)
#   sanctions.trigger — refresh one list (#listType) or all lists
#
# Actions gated (ApprovalResource, ADR-0155):
#   sanctions.approval.decide — a DIFFERENT operator decides a paused sanctions.clear request (#id)
#
# Base rest.rego already grants: operator-read-any / compliance-read-any for sanctions.list +
# sanctions.read, and m2m-sanctions-screening for any service-account-* caller on
# sanctions.create only (deliberately NOT the whole family — sanctions.clear/.update/.trigger
# are real operator judgment calls and must stay human-only).

package openbank.rest

import rego.v1

# Operators and admins may perform ANY sanctions write — the ops/compliance console path
# (run a screen, decide a hit, edit a watchlist entry, refresh a feed).
allowed_reasons contains "operator-sanctions-write" if {
	input.principal.type == "HUMAN"
	some role in {"ROLE_OPERATOR", "ROLE_ADMIN"}
	role in input.principal.roles
	startswith(input.action, "sanctions.")
}
REGO
)

CHECKSUM=$(printf '%s\n' \
    "$(cat "$REST_REGO")" \
    "$(echo "$SANCTIONS_REST_EXT")" \
    "$(cat "$AGENTS_REGO")" \
    "$(cat "$AGENTS_YAML")" \
    "$(cat "$RULES_YAML")" \
    "$(cat "$MANIFEST")" | \
  (command -v sha256sum >/dev/null 2>&1 && sha256sum || shasum -a 256) | cut -c1-16)

OUT=$REPO/openbank-infra/gitops/components/sanctions-service/sanctions-opa-bundle.yaml

{
  echo "# GENERATED by gen-sanctions-opa-bundle.sh — do not hand-edit."
  echo "# Source: rest.rego + sanctions_rest_ext.rego + agents.rego + agents.yaml + rules-opa-data.yaml + bundle.manifest"
  echo "apiVersion: v1"
  echo "kind: ConfigMap"
  echo "metadata:"
  echo "  name: sanctions-opa-bundle"
  echo "  namespace: sanctions"
  echo "  labels:"
  echo "    app.kubernetes.io/name: sanctions-service"
  echo "    app.kubernetes.io/part-of: sanctions"
  echo "  annotations:"
  echo "    openbank.tech/policy-checksum: \"$CHECKSUM\""
  echo "data:"
  echo "  rest.rego: |"
  sed 's/^/    /' "$REST_REGO" | sed 's/[[:space:]]*$//'
  echo "  sanctions_rest_ext.rego: |"
  echo "$SANCTIONS_REST_EXT" | sed 's/^/    /' | sed 's/[[:space:]]*$//'
  echo "  agents.rego: |"
  sed 's/^/    /' "$AGENTS_REGO" | sed 's/[[:space:]]*$//'
  echo "  agents-data.yaml: |"
  sed 's/^/    /' "$AGENTS_YAML" | sed 's/[[:space:]]*$//'
  echo "  rules-data.yaml: |"
  sed 's/^/    /' "$RULES_YAML" | sed 's/[[:space:]]*$//'
  echo "  manifest.json: |"
  sed 's/^/    /' "$MANIFEST" | sed 's/[[:space:]]*$//'
  printf '\n'
} > "$OUT"

echo "wrote $OUT (checksum $CHECKSUM)"

# Sync the Rollout pod-roll annotation so a policy change always triggers a rollout
# (subPath mounts do NOT hot-reload — same pattern as gen-anacredit-opa-bundle.sh).
ROLLOUT=$REPO/openbank-infra/gitops/components/sanctions-service/sanctions-service.yaml
if [ -f "$ROLLOUT" ]; then
  sed -i.bak "s|openbank.tech/policy-checksum: \"[^\"]*\"|openbank.tech/policy-checksum: \"$CHECKSUM\"|" "$ROLLOUT"
  rm -f "${ROLLOUT}.bak"
  echo "patched $ROLLOUT annotation → $CHECKSUM"
fi
