CREATE SEQUENCE IF NOT EXISTS "parties_SEQ"           INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS "party_documents_SEQ"   INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS "party_outbox_SEQ"      INCREMENT BY 50;
