DROP SEQUENCE IF EXISTS "parties_SEQ";
DROP SEQUENCE IF EXISTS "party_documents_SEQ";
DROP SEQUENCE IF EXISTS "party_outbox_SEQ";

CREATE SEQUENCE IF NOT EXISTS parties_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS party_documents_seq INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS party_outbox_seq INCREMENT BY 50;
