# SPDX-License-Identifier: Apache-2.0
# Projects the OIDC client secret for tpp-registry-service from OpenBao (Vault KV) into the
# tpp-registry namespace so the Deployment can reference it via secretKeyRef.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tpp-registry-service-oidc
  namespace: tpp-registry
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: tpp-registry-service-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: tpp-registry-service
        property: OIDC_CLIENT_SECRET
